#### Module 5 — M05_02 Runtime Restore, KPI Derivation and Healthy Validation

**Structured filename:** `M05_02_Runtime_Restore_KPI_Derivation_and_Healthy_Validation_v1.ipynb`

This notebook is the second executable stage of **Module 5 — Agentic Telecom AI** in the Telecom AI Engineering Platform.

> **North Star:** The LLM orchestrates. Deterministic telemetry supplies network truth. Standards knowledge provides grounding. ML supplies probabilistic evidence. Policy controls actions. Verification closes the loop.


##### Introduction — Goal

The goal of M05_02 is to restore the **frozen M05_01 foundation and canonical healthy telemetry without rebuilding them**, derive the two formal 3GPP TS 28.554 5G RAN Accessibility KPIs deterministically from standardized PM observations, and establish a validated healthy control baseline for downstream Module 5 experiments.

The notebook must finish with an auditable result proving that the corrected M05_01 V1.2/V1.1 lineage can support mathematically valid formal KPI derivation.


##### Introduction — Specific Research Question

> **Can the corrected and frozen M05_01 telemetry foundation be independently restored and used to derive mathematically valid Partial and Total DRB Accessibility KPIs across the complete 92-day healthy baseline?**

M05_02 is therefore a deterministic validation notebook. It does **not** introduce an LLM, ML inference, fault injection, incident truth, autonomous actions or policy decisions.


##### Introduction — Authoritative Inputs

M05_02 restores only the final M05_01 sources:

```text
Frozen foundation bundle V1.2
/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_01/foundation/foundation_bundle_v1_2

Canonical healthy telemetry V1.1
/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_01/telemetry/healthy_baseline_v1_1
```

The earlier telemetry V1 lineage and the intermediate V1.1 freeze are explicitly superseded and must not be accepted as restore sources.


##### Introduction — Root-of-Trust Identities

```text
M05_01 freeze V1.2 semantic SHA
4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968

Foundation bundle index semantic SHA
55c8ef51f905945fb825fad3bb35b932ccf7e140f5ffe9d85d3430071ff7143b

Foundation bundle index artifact SHA
bdeee58930d9a13334640132e7a12fa9ace6222a19cfc2c8626e1fd430fd9b8f

Foundation persistence semantic SHA
936b605cb1ce3c2d2b2977fed537df65c5e61e19e26ff655f89b27b919d62879

Telemetry qualification semantic SHA
fc3c38f980209b1d5a9504b30f98efa6636ba7eedc153ef4f4d1e7bb49be156a

Canonical manifest artifact SHA
e856ffe3f7ed97e6ad4592e999e5fd3adf5993f80ac72cdada1f374ab6543411

Canonical telemetry semantic SHA
c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7
```


##### Introduction — Formal KPI Scope

M05_02 derives the two formal Accessibility KPIs already frozen in the M05_01 standards foundation:

1. **Partial DRB Accessibility for UE Services — TS 28.554 Clause 6.2.4**
2. **Total DRB Accessibility for UE Services — TS 28.554 Clause 6.2.7**

The derivation uses the exact standardized PM dependencies and exclusions represented in the frozen M05_01 knowledge supplement. The formal KPI values were intentionally **not persisted by M05_01**.


##### Introduction — Implementation Plan

```text
1. Bootstrap runtime and freeze the M05_02 restore contract
2. Mount Google Drive and locate authoritative M05_01 sources
3. Verify foundation bundle index and persistence receipt
4. Verify all 11 foundation artifacts + 4 authoritative control artifacts
5. Authorize the V1.2/V1.1 control lineage and reject superseded V1
6. Verify canonical telemetry manifest and semantic identity
7. Verify all 92 Parquet partitions and row inventory
8. Inspect the long-form telemetry schema and runtime metric inventory
9. Restore the formal KPI knowledge contract
10. Qualify exact PM dependencies, dimensions and entity scope
11. Aggregate RRC / NG control-plane counters
12. Aggregate DRB counters by 5QI
13. Derive Partial DRB Accessibility
14. Derive Total-RRC / RRC-Resume ratios and validate hierarchy
15. Derive Total DRB Accessibility
16. Validate KPI completeness, denominators and mathematical bounds
17. Establish cell-level and SubNetwork healthy baseline summaries
18. Persist derived KPI outputs to Google Drive
19. Persist the M05_02 validation receipt and result manifest
20. Close M05_02 and hand off the validated baseline to M05_03
```


##### Introduction — Validation Philosophy

M05_02 distinguishes **standardized mathematical validity** from **synthetic operating expectations**.

Formal validation checks include:
- exact formula dependency availability;
- dimensional alignment;
- attempt/success hierarchy;
- Added-DRB non-negativity;
- Resume/fallback/re-establishment hierarchy;
- positive denominators;
- finite KPI values;
- KPI range of 0–100%;
- complete expected cell × interval × 5QI coverage.

No arbitrary vendor threshold is introduced as a 3GPP requirement. Descriptive healthy-baseline statistics are recorded separately from standards-based pass/fail checks.


##### Introduction — Execution Environment

This notebook is designed for **Google Colab** and does **not require a GPU**. The workload is deterministic JSON/Parquet verification and SQL-style aggregation over the 92-day telemetry baseline.

DuckDB is used to scan and aggregate the long-form Parquet telemetry without loading all 18.8 million observations into pandas memory at once.


##### Introduction — Expected Outputs

M05_02 will persist a new versioned result set under:

```text
/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_02/
```

Expected outputs:

```text
kpi/
  module5_m05_02_nr_cell_cu_accessibility_kpis_v1.parquet
  module5_m05_02_subnetwork_accessibility_kpis_v1.parquet

manifests/
  module5_m05_02_kpi_derivation_manifest_v1.json
  module5_m05_02_validation_receipt_v1.json
```

M05_01 artifacts remain immutable.


##### Introduction — Completion Gate

M05_02 is complete only when the deterministic restore, derivation, validation and persistence chain succeeds. The key terminal gates are:

```text
M05_02_RESTORE_CONTRACT_DEFINED = True
M05_02_FOUNDATION_RESTORE_PASS = True
M05_02_TELEMETRY_RESTORE_PASS = True
M05_02_FORMULA_BINDING_PASS = True
M05_02_PARTIAL_KPI_PASS = True
M05_02_TOTAL_KPI_PASS = True
M05_02_FORMAL_KPI_VALIDATION_PASS = True
M05_02_HEALTHY_VALIDATION_PASS = True
M05_02_KPI_FILES_PERSISTED = True
M05_02_PERSISTENCE_PASS = True
M05_02_CLOSEOUT_PASS = True
```

Supporting internal gates (source discovery, bundle verification, canonical-manifest verification, runtime-view initialization, KPI-knowledge restore and counter aggregation) must also pass before these terminal gates can be reached.

Only then should Module 5 proceed to **M05_03 — Sionna Radio Reference Validation**.


<a id="cell-01"></a>
##### Cell 01 — Runtime Bootstrap and Authoritative Restore Contract

Defines the immutable M05_02 root-of-trust identities, Google Drive locations, helper functions and superseded-lineage rejection policy. No M05_01 artifact is modified.


In [1]:
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import os
import sys

MODULE_ID = "M05_02"
NOTEBOOK_VERSION = "V1"

EXPECTED = {
    "m05_01_freeze_semantic_sha256":
        "4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968",
    "foundation_bundle_index_semantic_sha256":
        "55c8ef51f905945fb825fad3bb35b932ccf7e140f5ffe9d85d3430071ff7143b",
    "foundation_bundle_index_artifact_sha256":
        "bdeee58930d9a13334640132e7a12fa9ace6222a19cfc2c8626e1fd430fd9b8f",
    "foundation_persistence_semantic_sha256":
        "936b605cb1ce3c2d2b2977fed537df65c5e61e19e26ff655f89b27b919d62879",
    "telemetry_qualification_semantic_sha256":
        "fc3c38f980209b1d5a9504b30f98efa6636ba7eedc153ef4f4d1e7bb49be156a",
    "canonical_manifest_artifact_sha256":
        "e856ffe3f7ed97e6ad4592e999e5fd3adf5993f80ac72cdada1f374ab6543411",
    "canonical_dataset_semantic_sha256":
        "c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7",
}

SUPERSEDED = {
    "telemetry_v1_semantic_sha256":
        "d6b75444faf53d602edf952f4620fe02f2f3a4ea68431a4889e4829adf008f4d",
    "freeze_v1_semantic_sha256":
        "3a519602da5e211df684786441c41669fbfdaac1c0d13254d18187ad5ce874e8",
}

DRIVE_M05_01_ROOT = Path(
    "/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_01"
)
FOUNDATION_BUNDLE_DIR = (
    DRIVE_M05_01_ROOT / "foundation" / "foundation_bundle_v1_2"
)
TELEMETRY_DIR = (
    DRIVE_M05_01_ROOT / "telemetry" / "healthy_baseline_v1_1"
)

DRIVE_M05_02_ROOT = Path(
    "/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_02"
)
M05_02_KPI_DIR = DRIVE_M05_02_ROOT / "kpi"
M05_02_MANIFEST_DIR = DRIVE_M05_02_ROOT / "manifests"

def sha256_file(path, chunk_size=1024 * 1024):
    path = Path(path)
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            hasher.update(chunk)
    return hasher.hexdigest()

def canonical_sha256(payload):
    raw = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()

def load_json(path):
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)

def embedded_semantic_sha(payload):
    return (
        payload.get("semantic_sha256")
        or payload.get("taxonomy_semantic_sha256")
    )

print("=" * 108)
print("MODULE 5 — M05_02 CELL 01 — AUTHORITATIVE RESTORE CONTRACT")
print("=" * 108)
print(f"Python version                      : {sys.version.split()[0]}")
print(f"Foundation bundle                  : {FOUNDATION_BUNDLE_DIR}")
print(f"Canonical telemetry                : {TELEMETRY_DIR}")
print(f"M05_02 output root                 : {DRIVE_M05_02_ROOT}")
print("Superseded telemetry V1 permitted  : NO")
print("Kaggle restore permitted           : NO")
print("GPU required                       : NO")
print("=" * 108)

M05_02_RESTORE_CONTRACT_DEFINED = True


MODULE 5 — M05_02 CELL 01 — AUTHORITATIVE RESTORE CONTRACT
Python version                      : 3.13.15
Foundation bundle                  : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_01/foundation/foundation_bundle_v1_2
Canonical telemetry                : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_01/telemetry/healthy_baseline_v1_1
M05_02 output root                 : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_02
Superseded telemetry V1 permitted  : NO
Kaggle restore permitted           : NO
GPU required                       : NO


###### Cell 01 — Observation

The M05_02 runtime restore contract was established successfully using the final **M05_01 V1.2 foundation bundle** and **V1.1 canonical healthy telemetry** as the only authorized inputs.

The superseded V1 telemetry lineage and Kaggle restore path are explicitly excluded, while M05_02 is configured to write its outputs to a separate Google Drive location. The deterministic restore and KPI-validation workflow requires **no GPU**.

> **`M05_02_RESTORE_CONTRACT_DEFINED=True` — the authoritative restore contract and downstream output boundary are established.**


<a id="cell-02"></a>
##### Cell 02 — Mount Google Drive and Locate Authoritative Sources

Mounts Google Drive and requires both final M05_01 restore sources to exist before any derivation work begins.


In [2]:
if not globals().get("M05_02_RESTORE_CONTRACT_DEFINED", False):
    raise RuntimeError("Cell 02 requires Cell 01.")

from google.colab import drive
drive.mount("/content/drive")

required_paths = {
    "foundation_bundle_v1_2": FOUNDATION_BUNDLE_DIR,
    "healthy_baseline_v1_1": TELEMETRY_DIR,
    "bundle_index": FOUNDATION_BUNDLE_DIR / "foundation_bundle_index.json",
    "foundation_persistence_receipt":
        FOUNDATION_BUNDLE_DIR / "foundation_persistence_receipt.json",
    "canonical_manifest": TELEMETRY_DIR / "manifest.json",
}

missing = [
    name
    for name, path in required_paths.items()
    if not path.exists()
]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 02 — GOOGLE DRIVE SOURCE DISCOVERY")
print("=" * 108)
for name, path in required_paths.items():
    print(f"{name:<34} : {'FOUND' if path.exists() else 'MISSING'}")
print("-" * 108)
print(f"Missing authoritative paths         : {len(missing)}")

if missing:
    raise FileNotFoundError(
        "Authoritative M05_01 restore source missing: "
        + ", ".join(missing)
    )

M05_02_DRIVE_SOURCE_DISCOVERY_PASS = True
print("M05_02_DRIVE_SOURCE_DISCOVERY_PASS : True")


Mounted at /content/drive
MODULE 5 — M05_02 CELL 02 — GOOGLE DRIVE SOURCE DISCOVERY
foundation_bundle_v1_2             : FOUND
healthy_baseline_v1_1              : FOUND
bundle_index                       : FOUND
foundation_persistence_receipt     : FOUND
canonical_manifest                 : FOUND
------------------------------------------------------------------------------------------------------------
Missing authoritative paths         : 0
M05_02_DRIVE_SOURCE_DISCOVERY_PASS : True


###### Cell 02 — Observation

Google Drive mounted successfully and all required M05_01 restore sources were located, including the **V1.2 foundation bundle**, **V1.1 healthy telemetry**, bundle index, foundation persistence receipt and canonical telemetry manifest.

No authoritative paths were missing, therefore **`M05_02_DRIVE_SOURCE_DISCOVERY_PASS=True`** and the notebook can proceed from source discovery to root-of-trust verification.

<a id="cell-03"></a>
##### Cell 03 — Verify Foundation Bundle Index and Persistence Receipt

Validates the foundation bundle index by exact byte SHA and semantic SHA, then verifies the final V1.2 foundation-persistence receipt.


In [3]:
if not globals().get("M05_02_DRIVE_SOURCE_DISCOVERY_PASS", False):
    raise RuntimeError("Cell 03 requires Cell 02.")

BUNDLE_INDEX_PATH = FOUNDATION_BUNDLE_DIR / "foundation_bundle_index.json"
FOUNDATION_PERSISTENCE_RECEIPT_PATH = (
    FOUNDATION_BUNDLE_DIR / "foundation_persistence_receipt.json"
)

bundle_index_artifact_sha = sha256_file(BUNDLE_INDEX_PATH)
BUNDLE_INDEX = load_json(BUNDLE_INDEX_PATH)

bundle_semantic_content = {
    key: value
    for key, value in BUNDLE_INDEX.items()
    if key not in {"created_utc", "semantic_sha256"}
}
bundle_index_semantic_recomputed = canonical_sha256(bundle_semantic_content)

FOUNDATION_PERSISTENCE_RECEIPT = load_json(
    FOUNDATION_PERSISTENCE_RECEIPT_PATH
)

checks = {
    "bundle_index_artifact_sha":
        bundle_index_artifact_sha
        == EXPECTED["foundation_bundle_index_artifact_sha256"],
    "bundle_index_embedded_semantic_sha":
        BUNDLE_INDEX.get("semantic_sha256")
        == EXPECTED["foundation_bundle_index_semantic_sha256"],
    "bundle_index_recomputed_semantic_sha":
        bundle_index_semantic_recomputed
        == EXPECTED["foundation_bundle_index_semantic_sha256"],
    "foundation_persistence_semantic_sha":
        FOUNDATION_PERSISTENCE_RECEIPT.get("semantic_sha256")
        == EXPECTED["foundation_persistence_semantic_sha256"],
    "bundle_version_v1_2":
        BUNDLE_INDEX.get("bundle_version") == "V1.2",
    "indexed_artifact_count_15":
        BUNDLE_INDEX.get("indexed_artifact_count") == 15,
    "superseded_artifacts_excluded":
        BUNDLE_INDEX.get("superseded_artifacts_included") is False,
}

failed = [name for name, passed in checks.items() if not passed]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 03 — FOUNDATION BUNDLE ROOT VERIFICATION")
print("=" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print(f"Indexed foundation artifacts        : {BUNDLE_INDEX.get('foundation_artifact_count')}")
print(f"Indexed control artifacts           : {BUNDLE_INDEX.get('control_artifact_count')}")
print(f"Indexed artifacts total             : {BUNDLE_INDEX.get('indexed_artifact_count')}")

if failed:
    raise RuntimeError(
        "Foundation bundle root verification failed: "
        + ", ".join(failed)
    )

M05_02_BUNDLE_ROOT_PASS = True
print("M05_02_BUNDLE_ROOT_PASS             : True")


MODULE 5 — M05_02 CELL 03 — FOUNDATION BUNDLE ROOT VERIFICATION
PASS    bundle_index_artifact_sha
PASS    bundle_index_embedded_semantic_sha
PASS    bundle_index_recomputed_semantic_sha
PASS    foundation_persistence_semantic_sha
PASS    bundle_version_v1_2
PASS    indexed_artifact_count_15
PASS    superseded_artifacts_excluded
------------------------------------------------------------------------------------------------------------
Indexed foundation artifacts        : 11
Indexed control artifacts           : 4
Indexed artifacts total             : 15
M05_02_BUNDLE_ROOT_PASS             : True


###### Cell 03 — Observation

The M05_01 **foundation bundle V1.2 root-of-trust verification passed successfully**.

The bundle index matched its expected byte-level SHA, embedded semantic SHA and independently recomputed semantic identity. The foundation persistence receipt also matched the frozen semantic identity, while the bundle inventory confirmed **11 foundation artifacts and 4 authoritative control artifacts**, with superseded artifacts excluded.

> **`M05_02_BUNDLE_ROOT_PASS=True` — the V1.2 bundle root is authenticated and can now be used to verify each frozen artifact individually.**

<a id="cell-04"></a>
##### Cell 04 — Verify All Frozen Foundation and Control Artifacts

Walks the explicit bundle inventory and independently verifies every indexed file against its frozen artifact SHA and, where available, embedded semantic SHA.


In [4]:
if not globals().get("M05_02_BUNDLE_ROOT_PASS", False):
    raise RuntimeError("Cell 04 requires Cell 03.")

BUNDLE_ENTRIES = BUNDLE_INDEX["files"]

verification_rows = []
failures = []

for entry in BUNDLE_ENTRIES:
    path = FOUNDATION_BUNDLE_DIR / entry["bundle_relative_path"]
    exists = path.exists()

    observed_artifact_sha = sha256_file(path) if exists else None
    artifact_pass = (
        exists
        and observed_artifact_sha == entry["artifact_sha256"]
    )

    expected_semantic = entry.get("semantic_sha256")
    observed_semantic = None
    semantic_pass = True

    if exists and expected_semantic is not None:
        payload = load_json(path)
        observed_semantic = embedded_semantic_sha(payload)
        semantic_pass = observed_semantic == expected_semantic

    passed = exists and artifact_pass and semantic_pass

    verification_rows.append({
        "classification": entry["classification"],
        "role": entry["role"],
        "exists": exists,
        "artifact_pass": artifact_pass,
        "semantic_pass": semantic_pass,
        "passed": passed,
    })

    if not passed:
        failures.append(entry["role"])

foundation_count = sum(
    row["classification"] == "FOUNDATION"
    for row in verification_rows
)
control_count = sum(
    row["classification"] == "CONTROL"
    for row in verification_rows
)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 04 — COMPLETE BUNDLE INVENTORY VERIFICATION")
print("=" * 108)
print(f"Foundation artifacts                : {foundation_count}")
print(f"Control artifacts                   : {control_count}")
print(f"Total indexed artifacts             : {len(verification_rows)}")
print(f"Verification failures               : {len(failures)}")
if failures:
    print(f"Failed roles                        : {failures}")

if foundation_count != 11 or control_count != 4:
    raise RuntimeError("Unexpected V1.2 bundle inventory size.")

if failures:
    raise RuntimeError(
        "Frozen bundle artifact verification failed: "
        + ", ".join(failures)
    )

M05_02_FOUNDATION_BUNDLE_FILES_PASS = True
print("M05_02_FOUNDATION_BUNDLE_FILES_PASS : True")


MODULE 5 — M05_02 CELL 04 — COMPLETE BUNDLE INVENTORY VERIFICATION
Foundation artifacts                : 11
Control artifacts                   : 4
Total indexed artifacts             : 15
Verification failures               : 0
M05_02_FOUNDATION_BUNDLE_FILES_PASS : True


###### Cell 04 — Observation

All artifacts contained in the authenticated M05_01 V1.2 foundation bundle were verified successfully.

The bundle contained the expected **11 foundation artifacts and 4 authoritative control artifacts**, and every indexed file passed its configured artifact and semantic identity checks with **zero verification failures**.

> **`M05_02_FOUNDATION_BUNDLE_FILES_PASS=True` — the complete frozen foundation bundle is internally consistent and trusted for runtime restoration.**

<a id="cell-05"></a>
##### Cell 05 — Authorize Corrected Control Lineage and Reject Superseded V1

Loads the authoritative freeze, reconciliation, telemetry qualification and Drive-persistence controls by role, verifies their identities, and confirms that only V1.2/V1.1 may continue.


In [5]:
if not globals().get("M05_02_FOUNDATION_BUNDLE_FILES_PASS", False):
    raise RuntimeError("Cell 05 requires Cell 04.")

ENTRY_BY_ROLE = {
    entry["role"]: entry
    for entry in BUNDLE_ENTRIES
}

def bundle_path_for_role(role):
    if role not in ENTRY_BY_ROLE:
        raise KeyError(f"Bundle role not found: {role}")
    return (
        FOUNDATION_BUNDLE_DIR
        / ENTRY_BY_ROLE[role]["bundle_relative_path"]
    )

FREEZE = load_json(
    bundle_path_for_role("authoritative_freeze_v1_2")
)
RECONCILIATION = load_json(
    bundle_path_for_role("foundation_identity_reconciliation_v1_2")
)
TELEMETRY_QUALIFICATION = load_json(
    bundle_path_for_role("telemetry_qualification")
)
TELEMETRY_PERSISTENCE = load_json(
    bundle_path_for_role("google_drive_telemetry_persistence")
)

freeze_sha = FREEZE.get("semantic_sha256")
qualification_sha = TELEMETRY_QUALIFICATION.get("semantic_sha256")

serialized_controls = json.dumps(
    {
        "freeze": FREEZE,
        "reconciliation": RECONCILIATION,
        "qualification": TELEMETRY_QUALIFICATION,
        "telemetry_persistence": TELEMETRY_PERSISTENCE,
    },
    sort_keys=True,
)

lineage_checks = {
    "authoritative_freeze_v1_2":
        freeze_sha == EXPECTED["m05_01_freeze_semantic_sha256"],
    "telemetry_qualification_v1_1":
        qualification_sha == EXPECTED["telemetry_qualification_semantic_sha256"],
    "superseded_telemetry_sha_not_authorized":
        SUPERSEDED["telemetry_v1_semantic_sha256"] not in (
            FREEZE.get("authoritative_dataset_semantic_sha256", ""),
        ),
    "superseded_freeze_not_current":
        freeze_sha != SUPERSEDED["freeze_v1_semantic_sha256"],
    "canonical_v1_1_identity_present":
        EXPECTED["canonical_dataset_semantic_sha256"] in serialized_controls,
}

failed = [
    name
    for name, passed in lineage_checks.items()
    if not passed
]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 05 — CONTROL-LINEAGE AUTHORIZATION")
print("=" * 108)
for name, passed in lineage_checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print(f"Authorized freeze semantic SHA      : {freeze_sha}")
print(f"Authorized telemetry semantic SHA   : {EXPECTED['canonical_dataset_semantic_sha256']}")
print("Superseded V1 restore               : REJECTED")

if failed:
    raise RuntimeError(
        "Control-lineage authorization failed: "
        + ", ".join(failed)
    )

M05_02_FOUNDATION_RESTORE_PASS = True
print("M05_02_FOUNDATION_RESTORE_PASS      : True")


MODULE 5 — M05_02 CELL 05 — CONTROL-LINEAGE AUTHORIZATION
PASS    authoritative_freeze_v1_2
PASS    telemetry_qualification_v1_1
PASS    superseded_telemetry_sha_not_authorized
PASS    superseded_freeze_not_current
PASS    canonical_v1_1_identity_present
------------------------------------------------------------------------------------------------------------
Authorized freeze semantic SHA      : 4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968
Authorized telemetry semantic SHA   : c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7
Superseded V1 restore               : REJECTED
M05_02_FOUNDATION_RESTORE_PASS      : True


###### Cell 05 — Observation

The corrected M05_01 control lineage was authorized successfully. The **V1.2 foundation freeze** and **V1.1 canonical healthy telemetry** were confirmed as the current authoritative sources, while the superseded V1 telemetry and freeze identities were explicitly rejected.

> **`M05_02_FOUNDATION_RESTORE_PASS=True` — M05_02 is now formally bound to the corrected M05_01 lineage.**

<a id="cell-06"></a>
##### Cell 06 — Verify Canonical Telemetry Manifest and Semantic Identity

Verifies the canonical manifest byte hash, recomputes the dataset semantic hash using the original M05_01 semantic-hash contract, and checks the frozen 92-day healthy-baseline design constraints.


In [6]:
if not globals().get("M05_02_FOUNDATION_RESTORE_PASS", False):
    raise RuntimeError("Cell 06 requires Cell 05.")

CANONICAL_MANIFEST_PATH = TELEMETRY_DIR / "manifest.json"
CANONICAL_MANIFEST = load_json(CANONICAL_MANIFEST_PATH)

manifest_artifact_sha = sha256_file(CANONICAL_MANIFEST_PATH)

semantic_manifest_content = {
    "dataset_version": CANONICAL_MANIFEST["dataset_version"],
    "generator_seed": CANONICAL_MANIFEST["generator_seed"],
    "window": CANONICAL_MANIFEST["window"],
    "topology": CANONICAL_MANIFEST["topology"],
    "observability": CANONICAL_MANIFEST["observability"],
    "rows": CANONICAL_MANIFEST["rows"],
    "daily_semantic_hashes": [
        {
            "date": item["date"],
            "semantic_sha256": item["semantic_sha256"],
        }
        for item in CANONICAL_MANIFEST["daily_partitions"]
    ],
    "qualification_provenance":
        CANONICAL_MANIFEST["qualification_provenance"],
    "provenance":
        CANONICAL_MANIFEST["provenance"],
    "design_constraints":
        CANONICAL_MANIFEST["design_constraints"],
}

recomputed_dataset_semantic_sha = canonical_sha256(
    semantic_manifest_content
)

constraints = CANONICAL_MANIFEST["design_constraints"]

checks = {
    "manifest_artifact_sha":
        manifest_artifact_sha
        == EXPECTED["canonical_manifest_artifact_sha256"],
    "manifest_embedded_semantic_sha":
        CANONICAL_MANIFEST.get("semantic_sha256")
        == EXPECTED["canonical_dataset_semantic_sha256"],
    "dataset_semantic_sha_recomputed":
        recomputed_dataset_semantic_sha
        == EXPECTED["canonical_dataset_semantic_sha256"],
    "dataset_version_v1_1":
        CANONICAL_MANIFEST.get("dataset_version")
        == "MODULE5_HEALTHY_TELEMETRY_V1_1",
    "canonical_dataset":
        constraints.get("canonical_dataset") is True,
    "healthy_baseline_only":
        constraints.get("healthy_baseline_only") is True,
    "formal_kpi_not_generated":
        constraints.get("formal_ts_28_554_kpi_generated_independently") is False,
    "formal_kpi_deferred":
        constraints.get("formal_kpi_derivation_deferred") is True,
    "fault_not_injected":
        constraints.get("fault_injected") is False,
}

failed = [name for name, passed in checks.items() if not passed]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 06 — CANONICAL MANIFEST VERIFICATION")
print("=" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print(f"Dataset version                     : {CANONICAL_MANIFEST['dataset_version']}")
print(f"Rows                                : {CANONICAL_MANIFEST['rows']['total_rows']:,}")
print(f"Daily partitions                    : {len(CANONICAL_MANIFEST['daily_partitions'])}")
print(f"PM intervals                        : {CANONICAL_MANIFEST['window']['interval_count']:,}")
print(f"PM interval minutes                 : {CANONICAL_MANIFEST['window']['pm_interval_minutes']}")

if failed:
    raise RuntimeError(
        "Canonical manifest verification failed: "
        + ", ".join(failed)
    )

M05_02_CANONICAL_MANIFEST_PASS = True
print("M05_02_CANONICAL_MANIFEST_PASS      : True")


MODULE 5 — M05_02 CELL 06 — CANONICAL MANIFEST VERIFICATION
PASS    manifest_artifact_sha
PASS    manifest_embedded_semantic_sha
PASS    dataset_semantic_sha_recomputed
PASS    dataset_version_v1_1
PASS    canonical_dataset
PASS    healthy_baseline_only
PASS    formal_kpi_not_generated
PASS    formal_kpi_deferred
PASS    fault_not_injected
------------------------------------------------------------------------------------------------------------
Dataset version                     : MODULE5_HEALTHY_TELEMETRY_V1_1
Rows                                : 18,829,824
Daily partitions                    : 92
PM intervals                        : 8,832
PM interval minutes                 : 15
M05_02_CANONICAL_MANIFEST_PASS      : True


###### Cell 06 — Observation

The canonical M05_01 V1.1 telemetry manifest passed all identity and design-constraint checks.

The manifest matched its expected artifact SHA, embedded semantic SHA and independently recomputed dataset semantic identity. It also confirmed the expected **92-day / 18,829,824-row / 8,832-interval / 15-minute** healthy baseline, with no fault injection and no precomputed formal TS 28.554 KPI values.

> **`M05_02_CANONICAL_MANIFEST_PASS=True` — the canonical telemetry manifest is authenticated and the dataset is authorized for physical partition verification.**

<a id="cell-07"></a>
##### Cell 07 — Verify 92-Day Parquet Partition Inventory

Checks every canonical daily Parquet file against the manifest byte hash and row count, then verifies total rows, standardized/operational row accounting and the healthy event-channel artifact.


In [7]:
if not globals().get("M05_02_CANONICAL_MANIFEST_PASS", False):
    raise RuntimeError("Cell 07 requires Cell 06.")

import pyarrow.parquet as pq

partition_failures = []
observed_total_rows = 0

for number, entry in enumerate(
    CANONICAL_MANIFEST["daily_partitions"],
    start=1,
):
    path = TELEMETRY_DIR / entry["relative_path"]

    if not path.exists():
        partition_failures.append(
            f"{entry['date']}: missing"
        )
        continue

    observed_sha = sha256_file(path)
    metadata_rows = pq.ParquetFile(path).metadata.num_rows
    observed_total_rows += int(metadata_rows)

    if observed_sha != entry["parquet_sha256"]:
        partition_failures.append(
            f"{entry['date']}: SHA mismatch"
        )

    if int(metadata_rows) != int(entry["rows"]):
        partition_failures.append(
            f"{entry['date']}: row mismatch"
        )

EVENT_CHANNEL_PATH = TELEMETRY_DIR / CANONICAL_MANIFEST[
    "event_channel"
]["relative_path"]

event_channel_pass = (
    EVENT_CHANNEL_PATH.exists()
    and sha256_file(EVENT_CHANNEL_PATH)
    == CANONICAL_MANIFEST["event_channel"]["sha256"]
)

expected_total_rows = int(
    CANONICAL_MANIFEST["rows"]["total_rows"]
)

checks = {
    "daily_partition_count_92":
        len(CANONICAL_MANIFEST["daily_partitions"]) == 92,
    "partition_byte_and_row_identity":
        len(partition_failures) == 0,
    "total_row_identity":
        observed_total_rows == expected_total_rows,
    "healthy_event_channel_identity":
        event_channel_pass,
}

failed = [name for name, passed in checks.items() if not passed]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 07 — PARQUET INVENTORY VERIFICATION")
print("=" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print(f"Verified partitions                 : {len(CANONICAL_MANIFEST['daily_partitions'])}")
print(f"Observed total rows                 : {observed_total_rows:,}")
print(f"Expected total rows                 : {expected_total_rows:,}")
print(f"Partition failures                  : {len(partition_failures)}")

if partition_failures:
    print(partition_failures[:10])

if failed:
    raise RuntimeError(
        "Canonical partition verification failed: "
        + ", ".join(failed)
    )

M05_02_TELEMETRY_RESTORE_PASS = True
print("M05_02_TELEMETRY_RESTORE_PASS       : True")


MODULE 5 — M05_02 CELL 07 — PARQUET INVENTORY VERIFICATION
PASS    daily_partition_count_92
PASS    partition_byte_and_row_identity
PASS    total_row_identity
PASS    healthy_event_channel_identity
------------------------------------------------------------------------------------------------------------
Verified partitions                 : 92
Observed total rows                 : 18,829,824
Expected total rows                 : 18,829,824
Partition failures                  : 0
M05_02_TELEMETRY_RESTORE_PASS       : True


###### Cell 07 — Observation

The complete 92-day canonical healthy telemetry dataset was verified successfully at the physical partition level.

All **92 daily Parquet partitions** matched their expected byte identities and row counts, producing the exact canonical total of **18,829,824 rows** with zero partition failures. The associated healthy event-channel artifact also passed integrity verification.

> **`M05_02_TELEMETRY_RESTORE_PASS=True` — the frozen V1.1 telemetry dataset is fully restored and physically validated for KPI processing.**

<a id="cell-08"></a>
##### Cell 08 — Initialize DuckDB and Inspect Canonical Telemetry Schema

Creates a read-only logical view over the canonical Parquet partitions, confirms the long-form observation schema and inventories standardized versus operational metric families without loading the dataset into pandas.


In [8]:
if not globals().get("M05_02_TELEMETRY_RESTORE_PASS", False):
    raise RuntimeError("Cell 08 requires Cell 07.")

import importlib.util
import subprocess

if importlib.util.find_spec("duckdb") is None:
    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "duckdb>=1.1,<2",
    ])

import duckdb

DUCKDB_PATH = Path("/content/module5_m05_02_runtime.duckdb")
if DUCKDB_PATH.exists():
    DUCKDB_PATH.unlink()

con = duckdb.connect(str(DUCKDB_PATH))
con.execute("PRAGMA threads=4")

parquet_glob = str(
    TELEMETRY_DIR / "date=*" / "observations.parquet"
).replace("\\", "/")

con.execute(f"""
CREATE OR REPLACE VIEW telemetry AS
SELECT *
FROM read_parquet(
    '{parquet_glob}',
    union_by_name=true
)
""")

schema_df = con.execute(
    "DESCRIBE telemetry"
).df()

inventory_df = con.execute("""
SELECT
    is_standardized_metric,
    COUNT(*) AS rows,
    COUNT(DISTINCT metric_name) AS metric_families,
    COUNT(DISTINCT entity_id) AS entities,
    MIN(interval_start_utc) AS first_interval,
    MAX(interval_start_utc) AS last_interval
FROM telemetry
GROUP BY is_standardized_metric
ORDER BY is_standardized_metric DESC
""").df()

required_columns = {
    "metric_name",
    "is_standardized_metric",
    "entity_id",
    "entity_type",
    "site_id",
    "cu_domain_id",
    "interval_start_utc",
    "value_int",
    "value_float",
    "dimension_cause",
    "dimension_5qi",
}

observed_columns = set(schema_df["column_name"])
missing_columns = sorted(required_columns - observed_columns)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 08 — TELEMETRY RUNTIME INSPECTION")
print("=" * 108)
print("\nRequired schema columns")
print("-" * 108)
print(f"Missing required columns             : {missing_columns}")
print("\nMetric inventory")
print("-" * 108)
print(inventory_df.to_string(index=False))

if missing_columns:
    raise RuntimeError(
        "Canonical telemetry schema is missing required columns: "
        + ", ".join(missing_columns)
    )

M05_02_RUNTIME_VIEW_PASS = True
print("\nM05_02_RUNTIME_VIEW_PASS            : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 08 — TELEMETRY RUNTIME INSPECTION

Required schema columns
------------------------------------------------------------------------------------------------------------
Missing required columns             : []

Metric inventory
------------------------------------------------------------------------------------------------------------
 is_standardized_metric     rows  metric_families  entities            first_interval             last_interval
                   True 12983040               21        60 2026-06-01 00:00:00+00:00 2026-08-31 23:45:00+00:00
                  False  5846784               45        90 2026-06-01 00:00:00+00:00 2026-08-31 23:45:00+00:00

M05_02_RUNTIME_VIEW_PASS            : True


###### Cell 08 — Observation

The complete canonical telemetry was exposed successfully through the DuckDB analytical view, with **no required schema columns missing**.

The runtime identified **12,983,040 standardized observations across 21 metric families** and **5,846,784 operational observations across 45 metric families**, together accounting for the full **18,829,824-row** dataset. Both categories span the complete healthy baseline from **1 June to 31 August 2026**.

> **`M05_02_RUNTIME_VIEW_PASS=True` — the telemetry is now available as a structured SQL-queryable analytical dataset for formal KPI derivation.**

<a id="cell-09"></a>
##### Cell 09 — Restore Formal KPI Knowledge Contract

Loads the frozen Cell 05 KPI knowledge supplement from the verified bundle and extracts the Partial and Total DRB Accessibility formula contracts and exclusions.


In [9]:
if not globals().get("M05_02_RUNTIME_VIEW_PASS", False):
    raise RuntimeError("Cell 09 requires Cell 08.")

KPI_SUPPLEMENT_PATH = bundle_path_for_role(
    "cell05_kpi_supplement"
)
KPI_SUPPLEMENT = load_json(KPI_SUPPLEMENT_PATH)

KPI_FORMULAS = KPI_SUPPLEMENT["kpi_formula_knowledge"]

required_kpis = {
    "partial_drb_accessibility",
    "total_drb_accessibility",
}

missing_kpis = sorted(
    required_kpis - set(KPI_FORMULAS)
)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 09 — FORMAL KPI KNOWLEDGE RESTORE")
print("=" * 108)

for kpi_id in sorted(required_kpis):
    if kpi_id not in KPI_FORMULAS:
        continue

    record = KPI_FORMULAS[kpi_id]
    print(f"\n{kpi_id}")
    print("-" * 108)
    print(f"Name           : {record['kpi_name']}")
    print(f"Specification  : {record['specification']}")
    print(f"Clause         : {record['clause']}")
    print(f"Dependencies   : {len(record['required_measurements'])}")
    for measurement in record["required_measurements"]:
        print(f"  - {measurement}")

if missing_kpis:
    raise RuntimeError(
        "Frozen KPI formula contract incomplete: "
        + ", ".join(missing_kpis)
    )

M05_02_KPI_KNOWLEDGE_RESTORE_PASS = True
print("\nM05_02_KPI_KNOWLEDGE_RESTORE_PASS  : True")


MODULE 5 — M05_02 CELL 09 — FORMAL KPI KNOWLEDGE RESTORE

partial_drb_accessibility
------------------------------------------------------------------------------------------------------------
Name           : Partial DRB Accessibility for UE Services
Specification  : TS 28.554
Clause         : 6.2.4
Dependencies   : 6
  - RRC.ConnEstabAtt.Cause
  - RRC.ConnEstabSucc.Cause
  - UECNTX.ConnEstabAtt.Cause
  - UECNTX.ConnEstabSucc.Cause
  - DRB.EstabAtt.5QI
  - DRB.EstabSucc.5QI

total_drb_accessibility
------------------------------------------------------------------------------------------------------------
Name           : Total DRB Accessibility for UE Services
Specification  : TS 28.554
Clause         : 6.2.7
Dependencies   : 16
  - RRC.ConnEstabAtt.Cause
  - RRC.ConnEstabSucc.Cause
  - UECNTX.ConnEstabAtt.Cause
  - UECNTX.ConnEstabSucc.Cause
  - DRB.InitialEstabAtt.5QI
  - DRB.InitialEstabSucc.5QI
  - DRB.EstabAtt.5QI
  - DRB.EstabSucc.5QI
  - DRB.ResumeAtt.5QI
  - DRB.ResumeSucc.5Q

###### Cell 09 — Observation

The frozen M05_01 KPI knowledge contract was restored successfully for both formal TS 28.554 Accessibility KPIs.

**Partial DRB Accessibility (§6.2.4)** requires six RRC, NG and DRB establishment measurements, while **Total DRB Accessibility (§6.2.7)** expands the dependency set to 16 measurements covering initial establishment, resume, fallback-to-setup and re-establishment behaviour.

> **`M05_02_KPI_KNOWLEDGE_RESTORE_PASS=True` — the standards-grounded KPI definitions are now available for binding to the canonical telemetry.**

<a id="cell-10"></a>
##### Cell 10 — Qualify Knowledge-to-Telemetry PM Bindings, Dimensions and Entity Scope

Binds every PM dependency from the restored TS 28.554 KPI knowledge contract to the canonical telemetry schema, including explicit reviewed aliases where foundation and telemetry naming differ. It then validates metric availability, 5QI and cause dimensions, NRCellCU scope, and the absence of RNA-update Resume causes in the healthy synthetic baseline.

In [11]:
# ============================================================
# MODULE 5 — M05_02
# CELL 10 — KNOWLEDGE-TO-TELEMETRY PM BINDING QUALIFICATION
# ============================================================

if not globals().get(
    "M05_02_KPI_KNOWLEDGE_RESTORE_PASS",
    False,
):
    raise RuntimeError(
        "Cell 10 requires Cell 09."
    )


# ============================================================
# 1. DERIVE FORMAL PM DEPENDENCIES FROM THE RESTORED
#    STANDARDS-GROUNDED KPI KNOWLEDGE CONTRACT
# ============================================================

FORMAL_KPI_IDS = (
    "partial_drb_accessibility",
    "total_drb_accessibility",
)

knowledge_required_metrics = sorted({
    measurement
    for kpi_id in FORMAL_KPI_IDS
    for measurement
    in KPI_FORMULAS[kpi_id]["required_measurements"]
})


# ============================================================
# 2. EXPLICIT REVIEWED PM NAME ALIASES
# ============================================================
#
# The frozen KPI knowledge artifact preserves TS 28.554
# formula naming for the two RRC Resume measurements:
#
#   RRC.ResumeAtt.cause
#   RRC.ResumeSucc.cause
#
# The canonical synthetic telemetry uses normalized internal names:
#
#   RRC.ResumeAtt.Cause
#   RRC.ResumeSucc.Cause
#
# TS 28.552 itself uses the lowercase `.cause` form for these
# Resume measurements. The uppercase `Cause` variants are an
# explicit internal canonicalization in the M05_01 telemetry schema.
#
# No generic case normalisation is performed.
# Only explicitly reviewed aliases are permitted.
# ============================================================

EXPLICIT_PM_ALIASES = {
    "RRC.ResumeAtt.cause":
        "RRC.ResumeAtt.Cause",

    "RRC.ResumeSucc.cause":
        "RRC.ResumeSucc.Cause",
}


# ============================================================
# 3. BUILD KNOWLEDGE -> TELEMETRY BINDINGS
# ============================================================

KNOWLEDGE_TO_TELEMETRY_BINDINGS = {
    measurement:
        EXPLICIT_PM_ALIASES.get(
            measurement,
            measurement,
        )
    for measurement
    in knowledge_required_metrics
}

FORMAL_TELEMETRY_METRICS = set(
    KNOWLEDGE_TO_TELEMETRY_BINDINGS.values()
)


# ============================================================
# 4. INVENTORY STANDARDIZED METRICS ACTUALLY AVAILABLE
#    IN THE CANONICAL TELEMETRY
# ============================================================

observed_formal_metrics = set(
    con.execute(
        """
        SELECT DISTINCT metric_name
        FROM telemetry
        WHERE is_standardized_metric = TRUE
        """
    )
    .fetchnumpy()["metric_name"]
    .tolist()
)

missing_metrics = sorted(
    FORMAL_TELEMETRY_METRICS
    - observed_formal_metrics
)

binding_failures = sorted(
    knowledge_measurement
    for (
        knowledge_measurement,
        telemetry_metric,
    )
    in KNOWLEDGE_TO_TELEMETRY_BINDINGS.items()
    if telemetry_metric
    not in observed_formal_metrics
)


# ============================================================
# 5. BUILD CAUSE AND 5QI METRIC GROUPS DIRECTLY FROM
#    THE BOUND TELEMETRY DEPENDENCY SET
# ============================================================

cause_metrics = sorted(
    metric
    for metric in FORMAL_TELEMETRY_METRICS
    if metric.lower().endswith(".cause")
)

fiveqi_metrics = sorted(
    metric
    for metric in FORMAL_TELEMETRY_METRICS
    if metric.endswith(".5QI")
)


def sql_string_list(values):
    return ", ".join(
        "'"
        + value.replace("'", "''")
        + "'"
        for value in values
    )


cause_metrics_sql = sql_string_list(
    cause_metrics
)

fiveqi_metrics_sql = sql_string_list(
    fiveqi_metrics
)

formal_metrics_sql = sql_string_list(
    sorted(FORMAL_TELEMETRY_METRICS)
)


# ============================================================
# 6. INSPECT CAUSE DIMENSIONS
# ============================================================

cause_df = con.execute(
    f"""
    SELECT
        metric_name,

        LIST(
            DISTINCT dimension_cause
            ORDER BY dimension_cause
        )
        FILTER (
            WHERE dimension_cause IS NOT NULL
        ) AS causes

    FROM telemetry

    WHERE metric_name IN (
        {cause_metrics_sql}
    )

    GROUP BY metric_name

    ORDER BY metric_name
    """
).df()


# ============================================================
# 7. INSPECT 5QI DIMENSIONS
# ============================================================

fiveqi_df = con.execute(
    f"""
    SELECT
        metric_name,

        LIST(
            DISTINCT CAST(
                dimension_5qi AS VARCHAR
            )
            ORDER BY CAST(
                dimension_5qi AS VARCHAR
            )
        )
        FILTER (
            WHERE dimension_5qi IS NOT NULL
        ) AS five_qi

    FROM telemetry

    WHERE metric_name IN (
        {fiveqi_metrics_sql}
    )

    GROUP BY metric_name

    ORDER BY metric_name
    """
).df()


# ============================================================
# 8. VERIFY ENTITY SCOPE
# ============================================================

scope_df = con.execute(
    f"""
    SELECT
        metric_name,

        LIST(
            DISTINCT entity_type
            ORDER BY entity_type
        ) AS entity_types

    FROM telemetry

    WHERE metric_name IN (
        {formal_metrics_sql}
    )

    GROUP BY metric_name

    ORDER BY metric_name
    """
).df()


# ============================================================
# 9. EXPLICIT ENTITY-SCOPE NORMALISATION
# ============================================================
#
# Foundation / standards-facing knowledge representation:
#
#   NRCellCU
#
# Canonical telemetry EntityType enum representation:
#
#   NR_CELL_CU
#
# They represent the same logical managed-object scope.
# We preserve both representations and explicitly bind them.
# ============================================================

FOUNDATION_NR_CELL_CU_SCOPE = (
    "NRCellCU"
)

CANONICAL_NR_CELL_CU_ENTITY_TYPE = (
    "NR_CELL_CU"
)

ENTITY_SCOPE_BINDINGS = {
    FOUNDATION_NR_CELL_CU_SCOPE:
        CANONICAL_NR_CELL_CU_ENTITY_TYPE
}


# ============================================================
# 10. INSPECT RRC RESUME CAUSES
# ============================================================
#
# TS 28.554 requires exclusion of Resume causes associated
# with RNA update from the RRC Resume success-rate component.
#
# The current synthetic V1.1 baseline is expected to contain
# no such cause.
# ============================================================

observed_resume_causes = set(
    con.execute(
        """
        SELECT DISTINCT
            dimension_cause

        FROM telemetry

        WHERE
            metric_name =
                'RRC.ResumeAtt.Cause'

            AND dimension_cause
                IS NOT NULL
        """
    )
    .fetchnumpy()["dimension_cause"]
    .tolist()
)

rna_like_causes = sorted(
    cause
    for cause in observed_resume_causes
    if "rna" in str(cause).lower()
)


# ============================================================
# 11. CONSOLIDATE OBSERVED 5QI VALUES
# ============================================================

expected_5qi = {
    "1",
    "5",
    "9",
}

observed_5qi = set()

for values in fiveqi_df["five_qi"]:

    if values is not None:

        observed_5qi.update(
            str(value)
            for value in values
        )


# ============================================================
# 12. QUALIFICATION GATES
# ============================================================

checks = {

    "knowledge_dependency_count_16":
        len(
            knowledge_required_metrics
        ) == 16,

    "explicit_alias_count_2":
        len(
            EXPLICIT_PM_ALIASES
        ) == 2,

    "all_knowledge_dependencies_bound":
        len(
            binding_failures
        ) == 0,

    "all_formal_metrics_present":
        len(
            missing_metrics
        ) == 0,

    "expected_5qi_dimension":
        observed_5qi
        == expected_5qi,

    "no_rna_update_causes_in_synthetic_v1_1":
        len(
            rna_like_causes
        ) == 0,

    "complete_entity_scope_inventory":
        len(
            scope_df
        )
        == len(
            FORMAL_TELEMETRY_METRICS
        ),

    "all_formula_metrics_nr_cell_cu":
        (
            len(
                scope_df
            )
            == len(
                FORMAL_TELEMETRY_METRICS
            )

            and all(
                list(
                    entity_types
                )
                == [
                    CANONICAL_NR_CELL_CU_ENTITY_TYPE
                ]

                for entity_types
                in scope_df["entity_types"]
            )
        ),
}


failed = [
    name
    for name, passed
    in checks.items()
    if not passed
]


# ============================================================
# 13. REPORT KNOWLEDGE -> TELEMETRY BINDINGS
# ============================================================

print("=" * 108)

print(
    "MODULE 5 — M05_02 CELL 10 — "
    "KNOWLEDGE-TO-TELEMETRY PM "
    "BINDING QUALIFICATION"
)

print("=" * 108)


print(
    "\nKnowledge -> telemetry bindings"
)

print("-" * 108)


for knowledge_measurement in (
    knowledge_required_metrics
):

    telemetry_metric = (
        KNOWLEDGE_TO_TELEMETRY_BINDINGS[
            knowledge_measurement
        ]
    )

    binding_type = (
        "ALIAS"
        if knowledge_measurement
        in EXPLICIT_PM_ALIASES
        else "EXACT"
    )

    print(
        f"{binding_type:<6} "
        f"{knowledge_measurement:<40} "
        f"-> {telemetry_metric}"
    )


# ============================================================
# 14. REPORT ENTITY-SCOPE BINDING
# ============================================================

print(
    "\nEntity-scope binding"
)

print("-" * 108)

print(
    f"Foundation knowledge scope          : "
    f"{FOUNDATION_NR_CELL_CU_SCOPE}"
)

print(
    f"Canonical telemetry entity type     : "
    f"{CANONICAL_NR_CELL_CU_ENTITY_TYPE}"
)

print(
    "Scope interpretation                : "
    "EQUIVALENT"
)


# ============================================================
# 15. REPORT OBSERVED FORMULA-METRIC ENTITY SCOPES
# ============================================================

print(
    "\nObserved formula metric entity scopes"
)

print("-" * 108)

print(
    scope_df.to_string(
        index=False
    )
)


# ============================================================
# 16. REPORT QUALIFICATION CHECKS
# ============================================================

print(
    "\nQualification checks"
)

print("-" * 108)

for name, passed in checks.items():

    print(
        f"{'PASS' if passed else 'FAIL':<7} "
        f"{name}"
    )


print("-" * 108)

print(
    f"Knowledge dependencies              : "
    f"{len(knowledge_required_metrics)}"
)

print(
    f"Bound telemetry metrics             : "
    f"{len(FORMAL_TELEMETRY_METRICS)}"
)

print(
    f"Explicit reviewed PM aliases        : "
    f"{len(EXPLICIT_PM_ALIASES)}"
)

print(
    f"Explicit entity-scope bindings      : "
    f"{len(ENTITY_SCOPE_BINDINGS)}"
)

print(
    f"Missing telemetry metrics           : "
    f"{missing_metrics}"
)

print(
    f"Binding failures                    : "
    f"{binding_failures}"
)

print(
    f"Observed 5QI values                 : "
    f"{sorted(observed_5qi)}"
)

print(
    f"Observed Resume causes              : "
    f"{sorted(observed_resume_causes)}"
)

print(
    f"RNA-like Resume causes              : "
    f"{rna_like_causes}"
)


# ============================================================
# 17. FINAL GATE
# ============================================================

if failed:

    raise RuntimeError(
        "Knowledge-to-telemetry PM "
        "binding qualification failed: "
        + ", ".join(
            failed
        )
    )


M05_02_FORMULA_BINDING_PASS = True


print(
    "\nM05_02_FORMULA_BINDING_PASS         : True"
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 10 — KNOWLEDGE-TO-TELEMETRY PM BINDING QUALIFICATION

Knowledge -> telemetry bindings
------------------------------------------------------------------------------------------------------------
EXACT  DRB.EstabAtt.5QI                         -> DRB.EstabAtt.5QI
EXACT  DRB.EstabSucc.5QI                        -> DRB.EstabSucc.5QI
EXACT  DRB.InitialEstabAtt.5QI                  -> DRB.InitialEstabAtt.5QI
EXACT  DRB.InitialEstabSucc.5QI                 -> DRB.InitialEstabSucc.5QI
EXACT  DRB.ResumeAtt.5QI                        -> DRB.ResumeAtt.5QI
EXACT  DRB.ResumeSucc.5QI                       -> DRB.ResumeSucc.5QI
EXACT  RRC.ConnEstabAtt.Cause                   -> RRC.ConnEstabAtt.Cause
EXACT  RRC.ConnEstabSucc.Cause                  -> RRC.ConnEstabSucc.Cause
EXACT  RRC.ReEstabFallbackToSetupAtt            -> RRC.ReEstabFallbackToSetupAtt
EXACT  RRC.ReEstabSuccWithoutUeContext          -> RRC.ReEstabSuccWithoutUeContext
ALIAS  RRC.ResumeAtt.cause                

###### Cell 10 — Observation

The standards-grounded KPI knowledge contract was successfully bound to the canonical telemetry dataset.

All **16 formal TS 28.554 dependencies** were located in the standardized telemetry, with two explicitly reviewed standard-to-canonical PM-name aliases and one explicit entity-scope normalization between the foundation representation **`NRCellCU`** and canonical telemetry representation **`NR_CELL_CU`**. Every required metric was confirmed at the NRCellCU scope.

The expected **5QI dimensions {1, 5, 9}** were present, while the observed RRC Resume causes were `mo-Data`, `mo-Signalling` and `mt-Access`, with no RNA-update cause requiring exclusion.

> **`M05_02_FORMULA_BINDING_PASS=True` — the formal KPI definitions and canonical telemetry are now fully qualified for deterministic Accessibility calculation.**


<a id="cell-11"></a>
##### Cell 11 — Aggregate RRC and NG Control-Plane Counters

Scans the canonical Parquet telemetry and builds a compact per-NRCellCU/per-15-minute control-plane table for direct RRC setup, NG setup, Resume fallback and re-establishment counters.


In [12]:
if not globals().get("M05_02_FORMULA_BINDING_PASS", False):
    raise RuntimeError("Cell 11 requires Cell 10.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_control AS
SELECT
    entity_id,
    ANY_VALUE(site_id) AS site_id,
    ANY_VALUE(cu_domain_id) AS cu_domain_id,
    interval_start_utc,

    SUM(CASE
        WHEN metric_name = 'RRC.ConnEstabAtt.Cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS rrc_conn_att_service,

    SUM(CASE
        WHEN metric_name = 'RRC.ConnEstabSucc.Cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS rrc_conn_succ_service,

    SUM(CASE
        WHEN metric_name = 'UECNTX.ConnEstabAtt.Cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS ng_att_service,

    SUM(CASE
        WHEN metric_name = 'UECNTX.ConnEstabSucc.Cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS ng_succ_service,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeAtt.Cause'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_att,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeSucc.Cause'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_succ,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeFallbackToSetupAtt.cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_fallback_att_service,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeSuccByFallback.cause'
         AND dimension_cause <> 'mo-Signalling'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_fallback_succ_service,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeFallbackToSetupAtt.cause'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_fallback_att_all,

    SUM(CASE
        WHEN metric_name = 'RRC.ResumeSuccByFallback.cause'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS resume_fallback_succ_all,

    SUM(CASE
        WHEN metric_name = 'RRC.ReEstabFallbackToSetupAtt'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS reestab_fallback_att,

    SUM(CASE
        WHEN metric_name = 'RRC.ReEstabSuccWithoutUeContext'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS reestab_succ_without_ctx

FROM telemetry
WHERE metric_name IN (
    'RRC.ConnEstabAtt.Cause',
    'RRC.ConnEstabSucc.Cause',
    'UECNTX.ConnEstabAtt.Cause',
    'UECNTX.ConnEstabSucc.Cause',
    'RRC.ResumeAtt.Cause',
    'RRC.ResumeSucc.Cause',
    'RRC.ResumeFallbackToSetupAtt.cause',
    'RRC.ResumeSuccByFallback.cause',
    'RRC.ReEstabFallbackToSetupAtt',
    'RRC.ReEstabSuccWithoutUeContext'
)
GROUP BY entity_id, interval_start_utc
""")

control_summary = con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT entity_id) AS cells,
    COUNT(DISTINCT interval_start_utc) AS intervals,
    MIN(rrc_conn_att_service) AS min_rrc_attempts,
    MIN(ng_att_service) AS min_ng_attempts
FROM m05_02_control
""").df()

print("=" * 108)
print("MODULE 5 — M05_02 CELL 11 — CONTROL-PLANE AGGREGATION")
print("=" * 108)
print(control_summary.to_string(index=False))

if int(control_summary.loc[0, "min_rrc_attempts"]) <= 0:
    raise RuntimeError("Non-positive RRC service-attempt denominator found.")

if int(control_summary.loc[0, "min_ng_attempts"]) <= 0:
    raise RuntimeError("Non-positive NG service-attempt denominator found.")

M05_02_CONTROL_AGG_PASS = True
print("\nM05_02_CONTROL_AGG_PASS             : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 11 — CONTROL-PLANE AGGREGATION
  rows  cells  intervals  min_rrc_attempts  min_ng_attempts
264960     30       8832             231.0            230.0

M05_02_CONTROL_AGG_PASS             : True


###### Cell 11 — Observation

The RRC and UE-associated NG control-plane counters were aggregated successfully across the complete healthy baseline.

The resulting table contains exactly **264,960 cell-interval records**, corresponding to **30 NRCellCU entities × 8,832 fifteen-minute intervals**. All RRC and NG service-attempt denominators remained positive, with minimum observed values of **231 RRC attempts** and **230 NG attempts**.

> **`M05_02_CONTROL_AGG_PASS=True` — the control-plane components required for formal Accessibility derivation are complete and mathematically usable.**


<a id="cell-12"></a>
##### Cell 12 — Aggregate DRB Counters by 5QI

Builds the per-cell/per-interval/per-5QI Initial DRB, total DRB and DRB Resume counter table, then reconstructs Added DRB attempts/successes as Total minus Initial.


In [13]:
if not globals().get("M05_02_CONTROL_AGG_PASS", False):
    raise RuntimeError("Cell 12 requires Cell 11.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_drb AS
SELECT
    entity_id,
    ANY_VALUE(site_id) AS site_id,
    ANY_VALUE(cu_domain_id) AS cu_domain_id,
    interval_start_utc,
    CAST(dimension_5qi AS VARCHAR) AS five_qi,

    SUM(CASE
        WHEN metric_name = 'DRB.InitialEstabAtt.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS initial_att,

    SUM(CASE
        WHEN metric_name = 'DRB.InitialEstabSucc.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS initial_succ,

    SUM(CASE
        WHEN metric_name = 'DRB.EstabAtt.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS estab_att,

    SUM(CASE
        WHEN metric_name = 'DRB.EstabSucc.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS estab_succ,

    SUM(CASE
        WHEN metric_name = 'DRB.ResumeAtt.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS drb_resume_att,

    SUM(CASE
        WHEN metric_name = 'DRB.ResumeSucc.5QI'
        THEN COALESCE(CAST(value_int AS DOUBLE), value_float)
        ELSE 0 END) AS drb_resume_succ

FROM telemetry
WHERE metric_name IN (
    'DRB.InitialEstabAtt.5QI',
    'DRB.InitialEstabSucc.5QI',
    'DRB.EstabAtt.5QI',
    'DRB.EstabSucc.5QI',
    'DRB.ResumeAtt.5QI',
    'DRB.ResumeSucc.5QI'
)
GROUP BY entity_id, interval_start_utc, dimension_5qi
""")

con.execute("""
ALTER TABLE m05_02_drb
ADD COLUMN added_att DOUBLE
""")
con.execute("""
UPDATE m05_02_drb
SET added_att = estab_att - initial_att
""")

con.execute("""
ALTER TABLE m05_02_drb
ADD COLUMN added_succ DOUBLE
""")
con.execute("""
UPDATE m05_02_drb
SET added_succ = estab_succ - initial_succ
""")

drb_diag = con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT entity_id) AS cells,
    COUNT(DISTINCT interval_start_utc) AS intervals,
    COUNT(DISTINCT five_qi) AS five_qi_values,
    SUM(CASE WHEN added_att < 0 THEN 1 ELSE 0 END) AS negative_added_att,
    SUM(CASE WHEN added_succ < 0 THEN 1 ELSE 0 END) AS negative_added_succ,
    SUM(CASE WHEN added_succ > added_att THEN 1 ELSE 0 END) AS added_succ_gt_att
FROM m05_02_drb
""").df()

print("=" * 108)
print("MODULE 5 — M05_02 CELL 12 — DRB AGGREGATION")
print("=" * 108)
print(drb_diag.to_string(index=False))

if any(
    int(drb_diag.loc[0, col]) != 0
    for col in [
        "negative_added_att",
        "negative_added_succ",
        "added_succ_gt_att",
    ]
):
    raise RuntimeError(
        "Corrected Added-DRB hierarchy failed."
    )

M05_02_DRB_AGG_PASS = True
print("\nM05_02_DRB_AGG_PASS                 : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 12 — DRB AGGREGATION
  rows  cells  intervals  five_qi_values  negative_added_att  negative_added_succ  added_succ_gt_att
794880     30       8832               3                 0.0                  0.0                0.0

M05_02_DRB_AGG_PASS                 : True


###### Cell 12 — Observation

The DRB counters were aggregated successfully across the complete healthy baseline at **NRCellCU × 15-minute interval × 5QI** granularity.

The resulting table contains exactly **794,880 records**, corresponding to **30 cells × 8,832 intervals × 3 configured 5QI values**. The corrected DRB hierarchy remained valid throughout the full dataset, with **zero negative Added-DRB attempts, zero negative Added-DRB successes and zero cases where Added-DRB successes exceeded attempts**.

> **`M05_02_DRB_AGG_PASS=True` — the corrected V1.1 DRB counter relationships are preserved across the complete canonical baseline and are ready for formal KPI derivation.**


<a id="cell-13"></a>
##### Cell 13 — Derive Partial DRB Accessibility

Implements TS 28.554 Clause 6.2.4: RRC setup success ratio × UE-associated NG-connection success ratio × DRB establishment success ratio × 100, excluding `mo-Signalling` from RRC and NG cause sums.


In [14]:
if not globals().get("M05_02_DRB_AGG_PASS", False):
    raise RuntimeError("Cell 13 requires Cell 12.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_partial AS
SELECT
    d.entity_id,
    d.site_id,
    d.cu_domain_id,
    d.interval_start_utc,
    d.five_qi,

    c.rrc_conn_succ_service
        / NULLIF(c.rrc_conn_att_service, 0)
        AS partial_rrc_setup_sr,

    c.ng_succ_service
        / NULLIF(c.ng_att_service, 0)
        AS ng_connection_sr,

    d.estab_succ
        / NULLIF(d.estab_att, 0)
        AS drb_establishment_sr,

    100.0
        * (c.rrc_conn_succ_service
            / NULLIF(c.rrc_conn_att_service, 0))
        * (c.ng_succ_service
            / NULLIF(c.ng_att_service, 0))
        * (d.estab_succ
            / NULLIF(d.estab_att, 0))
        AS partial_drb_accessibility_pct

FROM m05_02_drb AS d
JOIN m05_02_control AS c
USING (entity_id, interval_start_utc)
""")

partial_diag = con.execute("""
SELECT
    COUNT(*) AS rows,
    SUM(CASE
        WHEN partial_drb_accessibility_pct IS NULL
        THEN 1 ELSE 0 END) AS null_kpi,
    SUM(CASE
        WHEN NOT isfinite(partial_drb_accessibility_pct)
        THEN 1 ELSE 0 END) AS nonfinite_kpi,
    SUM(CASE
        WHEN partial_drb_accessibility_pct < 0
          OR partial_drb_accessibility_pct > 100
        THEN 1 ELSE 0 END) AS range_failures,
    MIN(partial_drb_accessibility_pct) AS min_pct,
    AVG(partial_drb_accessibility_pct) AS mean_pct,
    MAX(partial_drb_accessibility_pct) AS max_pct
FROM m05_02_partial
""").df()

print("=" * 108)
print("MODULE 5 — M05_02 CELL 13 — PARTIAL DRB ACCESSIBILITY")
print("=" * 108)
print(partial_diag.round(6).to_string(index=False))

partial_failures = sum(
    int(partial_diag.loc[0, col])
    for col in ["null_kpi", "nonfinite_kpi", "range_failures"]
)

if partial_failures:
    raise RuntimeError(
        "Partial DRB Accessibility validation failed."
    )

M05_02_PARTIAL_KPI_PASS = True
print("\nM05_02_PARTIAL_KPI_PASS             : True")


MODULE 5 — M05_02 CELL 13 — PARTIAL DRB ACCESSIBILITY
  rows  null_kpi  nonfinite_kpi  range_failures   min_pct  mean_pct  max_pct
794880       0.0            0.0             0.0 92.044707 99.323222    100.0

M05_02_PARTIAL_KPI_PASS             : True


###### Cell 13 — Observation

Partial DRB Accessibility was derived successfully for the complete healthy baseline using the formal TS 28.554 §6.2.4 calculation.

All **794,880 cell-interval-5QI KPI records** were finite and remained within the valid **0–100%** range, with no null or invalid values. The healthy baseline produced a mean Partial DRB Accessibility of **99.3232%**, ranging from **92.0447% to 100.0000%**.

> **`M05_02_PARTIAL_KPI_PASS=True` — formal Partial DRB Accessibility derivation is mathematically valid across the complete canonical baseline.**


<a id="cell-14"></a>
##### Cell 14 — Derive Total-RRC and RRC-Resume Success Ratios

Implements the supporting TS 28.554 Clause 6.2.7 RRC ratios and independently repeats the corrected Resume/fallback/re-establishment hierarchy validation before Total Accessibility is allowed.


In [15]:
if not globals().get("M05_02_PARTIAL_KPI_PASS", False):
    raise RuntimeError("Cell 14 requires Cell 13.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_control_ratios AS
SELECT
    *,

    (
        rrc_conn_succ_service
        + resume_fallback_succ_service
        + reestab_succ_without_ctx
    )
    /
    NULLIF(
        rrc_conn_att_service
        + resume_fallback_att_service
        + reestab_fallback_att,
        0
    ) AS rrc_total_setup_sr,

    resume_succ
    /
    NULLIF(
        resume_att - resume_fallback_att_all,
        0
    ) AS rrc_resume_sr,

    resume_att - resume_succ AS resume_direct_failures,

    (
        resume_att
        - resume_succ
        - resume_fallback_succ_all
    ) AS resume_residual_failure

FROM m05_02_control
""")

hierarchy_diag = con.execute("""
SELECT
    SUM(CASE
        WHEN resume_fallback_att_all > resume_direct_failures
        THEN 1 ELSE 0 END) AS fallback_att_gt_direct_failures,

    SUM(CASE
        WHEN resume_fallback_succ_all > resume_fallback_att_all
        THEN 1 ELSE 0 END) AS fallback_succ_gt_att,

    SUM(CASE
        WHEN resume_succ + resume_fallback_succ_all > resume_att
        THEN 1 ELSE 0 END) AS resume_total_succ_gt_att,

    SUM(CASE
        WHEN resume_residual_failure < 0
        THEN 1 ELSE 0 END) AS negative_resume_residual,

    SUM(CASE
        WHEN reestab_fallback_att > resume_residual_failure
        THEN 1 ELSE 0 END) AS reestab_att_gt_residual,

    SUM(CASE
        WHEN reestab_succ_without_ctx > reestab_fallback_att
        THEN 1 ELSE 0 END) AS reestab_succ_gt_att,

    SUM(CASE
        WHEN rrc_total_setup_sr IS NULL
          OR NOT isfinite(rrc_total_setup_sr)
          OR rrc_total_setup_sr < 0
          OR rrc_total_setup_sr > 1
        THEN 1 ELSE 0 END) AS rrc_total_ratio_failures,

    SUM(CASE
        WHEN rrc_resume_sr IS NULL
          OR NOT isfinite(rrc_resume_sr)
          OR rrc_resume_sr < 0
          OR rrc_resume_sr > 1
        THEN 1 ELSE 0 END) AS rrc_resume_ratio_failures

FROM m05_02_control_ratios
""").df()

ratio_summary = con.execute("""
SELECT
    MIN(rrc_total_setup_sr) * 100 AS rrc_total_min_pct,
    AVG(rrc_total_setup_sr) * 100 AS rrc_total_mean_pct,
    MAX(rrc_total_setup_sr) * 100 AS rrc_total_max_pct,
    MIN(rrc_resume_sr) * 100 AS rrc_resume_min_pct,
    AVG(rrc_resume_sr) * 100 AS rrc_resume_mean_pct,
    MAX(rrc_resume_sr) * 100 AS rrc_resume_max_pct
FROM m05_02_control_ratios
""").df()

print("=" * 108)
print("MODULE 5 — M05_02 CELL 14 — RRC TOTAL / RESUME FORMAL RATIOS")
print("=" * 108)
print("\nHierarchy diagnostics")
print("-" * 108)
print(hierarchy_diag.to_string(index=False))
print("\nRatio summary")
print("-" * 108)
print(ratio_summary.round(6).to_string(index=False))

if int(hierarchy_diag.sum(axis=1).iloc[0]) != 0:
    raise RuntimeError(
        "RRC Resume/re-establishment hierarchy or ratio validation failed."
    )

M05_02_RRC_TOTAL_RESUME_PASS = True
print("\nM05_02_RRC_TOTAL_RESUME_PASS        : True")


MODULE 5 — M05_02 CELL 14 — RRC TOTAL / RESUME FORMAL RATIOS

Hierarchy diagnostics
------------------------------------------------------------------------------------------------------------
 fallback_att_gt_direct_failures  fallback_succ_gt_att  resume_total_succ_gt_att  negative_resume_residual  reestab_att_gt_residual  reestab_succ_gt_att  rrc_total_ratio_failures  rrc_resume_ratio_failures
                             0.0                   0.0                       0.0                       0.0                      0.0                  0.0                       0.0                        0.0

Ratio summary
------------------------------------------------------------------------------------------------------------
 rrc_total_min_pct  rrc_total_mean_pct  rrc_total_max_pct  rrc_resume_min_pct  rrc_resume_mean_pct  rrc_resume_max_pct
         97.979798           99.720327              100.0           98.755187            99.967471               100.0

M05_02_RRC_TOTAL_RESUME_PASS    

###### Cell 14 — Observation

The supporting Total-RRC and RRC Resume success ratios required by TS 28.554 §6.2.7 were derived successfully across the complete healthy baseline.

All Resume, fallback-to-setup and re-establishment hierarchy checks passed with **zero violations**, confirming that attempts, successes and residual-failure relationships remain internally consistent. The Total-RRC success ratio averaged **99.7203%** with a minimum of **97.9798%**, while the RRC Resume success ratio averaged **99.9675%** with a minimum of **98.7552%**.

> **`M05_02_RRC_TOTAL_RESUME_PASS=True` — the control-plane hierarchy and supporting ratios required for Total DRB Accessibility are mathematically valid and ready for final KPI derivation.**


<a id="cell-15"></a>
##### Cell 15 — Derive Total DRB Accessibility

Implements TS 28.554 Clause 6.2.7 using Initial DRB service-intent adjustment, Added DRB attempts, DRB Resume service-intent adjustment, Total-RRC setup SR, NG SR and RRC Resume SR.


In [16]:
if not globals().get("M05_02_RRC_TOTAL_RESUME_PASS", False):
    raise RuntimeError("Cell 15 requires Cell 14.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_total AS
SELECT
    d.entity_id,
    d.site_id,
    d.cu_domain_id,
    d.interval_start_utc,
    d.five_qi,

    d.initial_att,
    d.initial_succ,
    d.added_att,
    d.added_succ,
    d.drb_resume_att,
    d.drb_resume_succ,

    c.rrc_total_setup_sr,
    c.ng_succ_service / NULLIF(c.ng_att_service, 0)
        AS ng_connection_sr,
    c.rrc_resume_sr,

    d.initial_att
        /
        NULLIF(
            c.rrc_total_setup_sr
            * (c.ng_succ_service / NULLIF(c.ng_att_service, 0)),
            0
        )
        AS initial_service_intent,

    d.drb_resume_att
        /
        NULLIF(c.rrc_resume_sr, 0)
        AS resume_service_intent,

    (
        d.initial_succ
        + d.added_succ
        + d.drb_resume_succ
    ) AS total_success_numerator,

    (
        d.initial_att
            /
            NULLIF(
                c.rrc_total_setup_sr
                * (c.ng_succ_service / NULLIF(c.ng_att_service, 0)),
                0
            )
        + d.added_att
        + d.drb_resume_att / NULLIF(c.rrc_resume_sr, 0)
    ) AS total_service_intent_denominator,

    100.0
        * (
            d.initial_succ
            + d.added_succ
            + d.drb_resume_succ
        )
        /
        NULLIF(
            (
                d.initial_att
                    /
                    NULLIF(
                        c.rrc_total_setup_sr
                        * (c.ng_succ_service / NULLIF(c.ng_att_service, 0)),
                        0
                    )
                + d.added_att
                + d.drb_resume_att / NULLIF(c.rrc_resume_sr, 0)
            ),
            0
        )
        AS total_drb_accessibility_pct

FROM m05_02_drb AS d
JOIN m05_02_control_ratios AS c
USING (entity_id, interval_start_utc)
""")

total_diag = con.execute("""
SELECT
    COUNT(*) AS rows,
    SUM(CASE
        WHEN total_service_intent_denominator <= 0
        THEN 1 ELSE 0 END) AS denominator_failures,
    SUM(CASE
        WHEN total_drb_accessibility_pct IS NULL
        THEN 1 ELSE 0 END) AS null_kpi,
    SUM(CASE
        WHEN NOT isfinite(total_drb_accessibility_pct)
        THEN 1 ELSE 0 END) AS nonfinite_kpi,
    SUM(CASE
        WHEN total_drb_accessibility_pct < 0
          OR total_drb_accessibility_pct > 100
        THEN 1 ELSE 0 END) AS range_failures,
    MIN(total_drb_accessibility_pct) AS min_pct,
    AVG(total_drb_accessibility_pct) AS mean_pct,
    MAX(total_drb_accessibility_pct) AS max_pct
FROM m05_02_total
""").df()

print("=" * 108)
print("MODULE 5 — M05_02 CELL 15 — TOTAL DRB ACCESSIBILITY")
print("=" * 108)
print(total_diag.round(6).to_string(index=False))

failure_cols = [
    "denominator_failures",
    "null_kpi",
    "nonfinite_kpi",
    "range_failures",
]

if sum(int(total_diag.loc[0, col]) for col in failure_cols) != 0:
    raise RuntimeError(
        "Total DRB Accessibility validation failed."
    )

M05_02_TOTAL_KPI_PASS = True
print("\nM05_02_TOTAL_KPI_PASS               : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 15 — TOTAL DRB ACCESSIBILITY
  rows  denominator_failures  null_kpi  nonfinite_kpi  range_failures   min_pct  mean_pct  max_pct
794880                   0.0       0.0            0.0             0.0 94.326606  99.52522    100.0

M05_02_TOTAL_KPI_PASS               : True


###### Cell 15 — Observation

Total DRB Accessibility was derived successfully across the complete healthy baseline using the formal TS 28.554 §6.2.7 calculation.

All **794,880 cell-interval-5QI KPI records** had valid positive denominators and produced finite values within the valid **0–100%** range, with no null or mathematical failures. The healthy baseline produced a mean Total DRB Accessibility of **99.5252%**, ranging from **94.3266% to 100.0000%**.

> **`M05_02_TOTAL_KPI_PASS=True` — formal Total DRB Accessibility derivation is mathematically valid across the complete corrected V1.1 baseline.**


<a id="cell-16"></a>
##### Cell 16 — Formal KPI Completeness and Mathematical Validation

Combines both KPI outputs and performs the final formal coverage, range, denominator and Added-DRB checks across the entire 92-day cell × interval × 5QI result space.


In [17]:
if not globals().get("M05_02_TOTAL_KPI_PASS", False):
    raise RuntimeError("Cell 16 requires Cell 15.")

con.execute("""
CREATE OR REPLACE TABLE m05_02_cell_kpis AS
SELECT
    p.entity_id,
    p.site_id,
    p.cu_domain_id,
    p.interval_start_utc,
    p.five_qi,

    p.partial_rrc_setup_sr * 100 AS partial_rrc_setup_sr_pct,
    p.ng_connection_sr * 100 AS ng_connection_sr_pct,
    p.drb_establishment_sr * 100 AS drb_establishment_sr_pct,
    p.partial_drb_accessibility_pct,

    t.rrc_total_setup_sr * 100 AS rrc_total_setup_sr_pct,
    t.rrc_resume_sr * 100 AS rrc_resume_sr_pct,
    t.total_drb_accessibility_pct,

    t.initial_att,
    t.initial_succ,
    t.added_att,
    t.added_succ,
    t.drb_resume_att,
    t.drb_resume_succ,
    t.total_success_numerator,
    t.total_service_intent_denominator

FROM m05_02_partial AS p
JOIN m05_02_total AS t
USING (
    entity_id,
    site_id,
    cu_domain_id,
    interval_start_utc,
    five_qi
)
""")

expected_rows = (
    int(CANONICAL_MANIFEST["topology"]["logical_cells"])
    * int(CANONICAL_MANIFEST["window"]["interval_count"])
    * 3
)

validation_df = con.execute(f"""
SELECT
    COUNT(*) AS observed_rows,
    COUNT(DISTINCT entity_id) AS cells,
    COUNT(DISTINCT interval_start_utc) AS intervals,
    COUNT(DISTINCT five_qi) AS five_qi_values,

    SUM(CASE
        WHEN partial_drb_accessibility_pct < 0
          OR partial_drb_accessibility_pct > 100
        THEN 1 ELSE 0 END) AS partial_range_failures,

    SUM(CASE
        WHEN total_drb_accessibility_pct < 0
          OR total_drb_accessibility_pct > 100
        THEN 1 ELSE 0 END) AS total_range_failures,

    SUM(CASE
        WHEN total_service_intent_denominator <= 0
        THEN 1 ELSE 0 END) AS total_denominator_failures,

    SUM(CASE
        WHEN added_att < 0
          OR added_succ < 0
          OR added_succ > added_att
        THEN 1 ELSE 0 END) AS added_drb_failures

FROM m05_02_cell_kpis
""").df()

formal_checks = {
    "expected_result_rows":
        int(validation_df.loc[0, "observed_rows"]) == expected_rows,
    "logical_cells_30":
        int(validation_df.loc[0, "cells"])
        == int(CANONICAL_MANIFEST["topology"]["logical_cells"]),
    "complete_interval_coverage":
        int(validation_df.loc[0, "intervals"])
        == int(CANONICAL_MANIFEST["window"]["interval_count"]),
    "three_5qi_values":
        int(validation_df.loc[0, "five_qi_values"]) == 3,
    "partial_range_valid":
        int(validation_df.loc[0, "partial_range_failures"]) == 0,
    "total_range_valid":
        int(validation_df.loc[0, "total_range_failures"]) == 0,
    "total_denominators_valid":
        int(validation_df.loc[0, "total_denominator_failures"]) == 0,
    "added_drb_hierarchy_valid":
        int(validation_df.loc[0, "added_drb_failures"]) == 0,
}

failed = [name for name, passed in formal_checks.items() if not passed]

print("=" * 108)
print("MODULE 5 — M05_02 CELL 16 — FORMAL KPI VALIDATION")
print("=" * 108)
for name, passed in formal_checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print(f"Expected result rows                 : {expected_rows:,}")
print(f"Observed result rows                 : {int(validation_df.loc[0, 'observed_rows']):,}")

if failed:
    raise RuntimeError(
        "Formal KPI validation failed: "
        + ", ".join(failed)
    )

M05_02_FORMAL_KPI_VALIDATION_PASS = True
print("M05_02_FORMAL_KPI_VALIDATION_PASS  : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 16 — FORMAL KPI VALIDATION
PASS    expected_result_rows
PASS    logical_cells_30
PASS    complete_interval_coverage
PASS    three_5qi_values
PASS    partial_range_valid
PASS    total_range_valid
PASS    total_denominators_valid
PASS    added_drb_hierarchy_valid
------------------------------------------------------------------------------------------------------------
Expected result rows                 : 794,880
Observed result rows                 : 794,880
M05_02_FORMAL_KPI_VALIDATION_PASS  : True


###### Cell 16 — Observation

The combined formal Accessibility KPI dataset passed all completeness and mathematical validation checks.

The observed result set contains exactly **794,880 records**, matching the expected **30 NRCellCU entities × 8,832 fifteen-minute intervals × 3 5QI values**. Both Partial and Total DRB Accessibility remained within the valid 0–100% range, all Total-Accessibility denominators were valid, and the corrected Added-DRB hierarchy remained intact.

> **`M05_02_FORMAL_KPI_VALIDATION_PASS=True` — the complete formal KPI result set is structurally complete and mathematically valid across the full 92-day healthy baseline.**


<a id="cell-17"></a>
##### Cell 17 — Establish Healthy Cell and SubNetwork Baselines

Produces descriptive healthy-baseline KPI statistics and applies the TS 28.554 SubNetwork rule by averaging NRCellCU KPI values. These summaries are observational; no arbitrary 3GPP pass threshold is introduced.


In [18]:
if not globals().get("M05_02_FORMAL_KPI_VALIDATION_PASS", False):
    raise RuntimeError("Cell 17 requires Cell 16.")

healthy_summary_df = con.execute("""
SELECT
    five_qi,

    MIN(partial_drb_accessibility_pct) AS partial_min_pct,
    QUANTILE_CONT(partial_drb_accessibility_pct, 0.05) AS partial_p05_pct,
    AVG(partial_drb_accessibility_pct) AS partial_mean_pct,
    QUANTILE_CONT(partial_drb_accessibility_pct, 0.95) AS partial_p95_pct,
    MAX(partial_drb_accessibility_pct) AS partial_max_pct,

    MIN(total_drb_accessibility_pct) AS total_min_pct,
    QUANTILE_CONT(total_drb_accessibility_pct, 0.05) AS total_p05_pct,
    AVG(total_drb_accessibility_pct) AS total_mean_pct,
    QUANTILE_CONT(total_drb_accessibility_pct, 0.95) AS total_p95_pct,
    MAX(total_drb_accessibility_pct) AS total_max_pct

FROM m05_02_cell_kpis
GROUP BY five_qi
ORDER BY five_qi
""").df()

con.execute("""
CREATE OR REPLACE TABLE m05_02_subnetwork_kpis AS
SELECT
    interval_start_utc,
    five_qi,
    AVG(partial_drb_accessibility_pct)
        AS partial_drb_accessibility_pct,
    AVG(total_drb_accessibility_pct)
        AS total_drb_accessibility_pct,
    COUNT(*) AS contributing_nr_cell_cu
FROM m05_02_cell_kpis
GROUP BY interval_start_utc, five_qi
ORDER BY interval_start_utc, five_qi
""")

subnetwork_diag = con.execute("""
SELECT
    COUNT(*) AS rows,
    MIN(contributing_nr_cell_cu) AS min_contributing_cells,
    MAX(contributing_nr_cell_cu) AS max_contributing_cells,
    MIN(partial_drb_accessibility_pct) AS partial_min_pct,
    AVG(partial_drb_accessibility_pct) AS partial_mean_pct,
    MAX(partial_drb_accessibility_pct) AS partial_max_pct,
    MIN(total_drb_accessibility_pct) AS total_min_pct,
    AVG(total_drb_accessibility_pct) AS total_mean_pct,
    MAX(total_drb_accessibility_pct) AS total_max_pct
FROM m05_02_subnetwork_kpis
""").df()

expected_cells = int(
    CANONICAL_MANIFEST["topology"]["logical_cells"]
)

subnetwork_complete = (
    int(subnetwork_diag.loc[0, "min_contributing_cells"]) == expected_cells
    and
    int(subnetwork_diag.loc[0, "max_contributing_cells"]) == expected_cells
)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 17 — HEALTHY BASELINE")
print("=" * 108)
print("\nCell-level descriptive baseline by 5QI")
print("-" * 108)
print(healthy_summary_df.round(6).to_string(index=False))
print("\nSubNetwork baseline")
print("-" * 108)
print(subnetwork_diag.round(6).to_string(index=False))
print("-" * 108)
print(f"All SubNetwork points use {expected_cells} cells : {subnetwork_complete}")

if not subnetwork_complete:
    raise RuntimeError(
        "SubNetwork averaging has incomplete NRCellCU coverage."
    )

M05_02_HEALTHY_VALIDATION_PASS = True
print("M05_02_HEALTHY_VALIDATION_PASS     : True")


MODULE 5 — M05_02 CELL 17 — HEALTHY BASELINE

Cell-level descriptive baseline by 5QI
------------------------------------------------------------------------------------------------------------
five_qi  partial_min_pct  partial_p05_pct  partial_mean_pct  partial_p95_pct  partial_max_pct  total_min_pct  total_p05_pct  total_mean_pct  total_p95_pct  total_max_pct
      1        92.044707        98.282295         99.295298        100.00000            100.0      94.326606      98.792968       99.497803      99.942912          100.0
      5        93.448859        98.127181         99.327966        100.00000            100.0      94.631486      98.620864       99.529773     100.000000          100.0
      9        96.298623        98.758266         99.346401         99.85229            100.0      97.881426      99.175102       99.548084      99.874741          100.0

SubNetwork baseline
---------------------------------------------------------------------------------------------------------

###### Cell 17 — Observation

The healthy Accessibility baseline was established successfully at both **NRCellCU** and **SubNetwork** levels.

Across the three configured 5QI classes, mean Partial DRB Accessibility remained between **99.2953% and 99.3464%**, while mean Total DRB Accessibility remained between **99.4978% and 99.5481%**. The SubNetwork aggregation used all **30 contributing cells for every interval and 5QI**, producing mean Partial and Total Accessibility values of **99.3232%** and **99.5252%**, respectively.

The narrower SubNetwork ranges confirm the expected smoothing effect of network-level aggregation relative to individual-cell variation.

> **`M05_02_HEALTHY_VALIDATION_PASS=True` — a complete descriptive healthy baseline is now available for downstream incident and anomaly comparison without imposing arbitrary operational thresholds.**


<a id="cell-18"></a>
##### Cell 18 — Persist Derived KPI Outputs to Google Drive

Writes immutable cell-level and SubNetwork KPI Parquet artifacts to the M05_02 Drive area. Existing files are never silently overwritten: an existing artifact must be byte-identical.


In [19]:
if not globals().get("M05_02_HEALTHY_VALIDATION_PASS", False):
    raise RuntimeError("Cell 18 requires Cell 17.")

import shutil

M05_02_KPI_DIR.mkdir(parents=True, exist_ok=True)
M05_02_MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

LOCAL_STAGE = Path("/content/module5_m05_02_stage")
if LOCAL_STAGE.exists():
    shutil.rmtree(LOCAL_STAGE)
LOCAL_STAGE.mkdir(parents=True)

CELL_KPI_NAME = (
    "module5_m05_02_nr_cell_cu_accessibility_kpis_v1.parquet"
)
SUBNETWORK_KPI_NAME = (
    "module5_m05_02_subnetwork_accessibility_kpis_v1.parquet"
)

local_cell_kpi = LOCAL_STAGE / CELL_KPI_NAME
local_subnetwork_kpi = LOCAL_STAGE / SUBNETWORK_KPI_NAME

con.execute(f"""
COPY (
    SELECT *
    FROM m05_02_cell_kpis
    ORDER BY interval_start_utc, entity_id, five_qi
)
TO '{str(local_cell_kpi).replace("\\", "/")}'
(FORMAT PARQUET, COMPRESSION ZSTD)
""")

con.execute(f"""
COPY (
    SELECT *
    FROM m05_02_subnetwork_kpis
    ORDER BY interval_start_utc, five_qi
)
TO '{str(local_subnetwork_kpi).replace("\\", "/")}'
(FORMAT PARQUET, COMPRESSION ZSTD)
""")

def persist_immutable(source, destination):
    source = Path(source)
    destination = Path(destination)
    source_sha = sha256_file(source)

    if destination.exists():
        destination_sha = sha256_file(destination)
        if destination_sha != source_sha:
            raise FileExistsError(
                "Different artifact already exists: "
                + str(destination)
            )
        operation = "VERIFIED_EXISTING"
    else:
        shutil.copy2(source, destination)
        destination_sha = sha256_file(destination)
        if destination_sha != source_sha:
            raise RuntimeError(
                "Post-copy SHA verification failed: "
                + str(destination)
            )
        operation = "CREATED"

    return {
        "path": str(destination),
        "sha256": source_sha,
        "bytes": int(destination.stat().st_size),
        "operation": operation,
    }

CELL_KPI_PERSISTENCE = persist_immutable(
    local_cell_kpi,
    M05_02_KPI_DIR / CELL_KPI_NAME,
)

SUBNETWORK_KPI_PERSISTENCE = persist_immutable(
    local_subnetwork_kpi,
    M05_02_KPI_DIR / SUBNETWORK_KPI_NAME,
)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 18 — KPI OUTPUT PERSISTENCE")
print("=" * 108)
for label, record in [
    ("NRCellCU KPI", CELL_KPI_PERSISTENCE),
    ("SubNetwork KPI", SUBNETWORK_KPI_PERSISTENCE),
]:
    print(f"\n{label}")
    print("-" * 108)
    print(f"Operation                           : {record['operation']}")
    print(f"Bytes                               : {record['bytes']:,}")
    print(f"SHA-256                             : {record['sha256']}")
    print(f"Path                                : {record['path']}")

M05_02_KPI_FILES_PERSISTED = True
print("\nM05_02_KPI_FILES_PERSISTED         : True")


FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

MODULE 5 — M05_02 CELL 18 — KPI OUTPUT PERSISTENCE

NRCellCU KPI
------------------------------------------------------------------------------------------------------------
Operation                           : CREATED
Bytes                               : 25,720,946
SHA-256                             : 709c9883bad799dec3907624a7590f5e44356d9fef7c00f4446d165fd1b2223f
Path                                : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_02/kpi/module5_m05_02_nr_cell_cu_accessibility_kpis_v1.parquet

SubNetwork KPI
------------------------------------------------------------------------------------------------------------
Operation                           : CREATED
Bytes                               : 382,554
SHA-256                             : 18d5a60ca91139242e85e9f5468346a66bedf70f8736e01507568f2afb9c42ba
Path                                : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_02/kpi/module5_m05_02_subnetwork_

###### Cell 18 — Observation

The validated Accessibility KPI outputs were persisted successfully to Google Drive as reusable downstream Parquet datasets.

The **NRCellCU-level KPI dataset** was created successfully at approximately **25.7 MB**, while the **SubNetwork-level KPI dataset** was created at approximately **0.38 MB**. Both outputs were written with recorded SHA-256 identities, preserving deterministic provenance for downstream Module 5 notebooks.

> **`M05_02_KPI_FILES_PERSISTED=True` — the formal cell-level and SubNetwork Accessibility KPI products are now durably stored and ready for reuse without re-deriving them from the full raw telemetry dataset.**


<a id="cell-19"></a>
##### Cell 19 — Persist KPI Derivation Manifest and Validation Receipt

Creates deterministic M05_02 provenance artifacts binding the final M05_01 root of trust to the derived KPI outputs and all validation gates.


In [20]:
if not globals().get("M05_02_KPI_FILES_PERSISTED", False):
    raise RuntimeError("Cell 19 requires Cell 18.")

summary_records = (
    healthy_summary_df
    .round(10)
    .to_dict(orient="records")
)

manifest_semantic = {
    "artifact_id":
        "module5_m05_02_kpi_derivation_manifest_v1",
    "module_id":
        "M05_02",
    "module_role":
        "RUNTIME_RESTORE_KPI_DERIVATION_HEALTHY_VALIDATION",
    "source_root_of_trust": {
        "m05_01_freeze_semantic_sha256":
            EXPECTED["m05_01_freeze_semantic_sha256"],
        "foundation_bundle_index_semantic_sha256":
            EXPECTED["foundation_bundle_index_semantic_sha256"],
        "canonical_dataset_semantic_sha256":
            EXPECTED["canonical_dataset_semantic_sha256"],
        "canonical_manifest_artifact_sha256":
            EXPECTED["canonical_manifest_artifact_sha256"],
    },
    "formal_kpis": {
        "partial_drb_accessibility": {
            "specification": "TS 28.554",
            "clause": "6.2.4",
        },
        "total_drb_accessibility": {
            "specification": "TS 28.554",
            "clause": "6.2.7",
        },
    },
    "result_scope": {
        "logical_cells":
            int(CANONICAL_MANIFEST["topology"]["logical_cells"]),
        "intervals":
            int(CANONICAL_MANIFEST["window"]["interval_count"]),
        "five_qi_values": ["1", "5", "9"],
        "cell_kpi_rows":
            int(validation_df.loc[0, "observed_rows"]),
        "subnetwork_kpi_rows":
            int(subnetwork_diag.loc[0, "rows"]),
    },
    "outputs": {
        "nr_cell_cu_kpis":
            CELL_KPI_PERSISTENCE,
        "subnetwork_kpis":
            SUBNETWORK_KPI_PERSISTENCE,
    },
    "healthy_baseline_summary_by_5qi":
        summary_records,
    "standards_boundary": {
        "vendor_threshold_applied": False,
        "synthetic_operating_range_treated_as_3gpp_threshold": False,
        "formal_kpi_values_derived_deterministically": True,
    },
}

M05_02_MANIFEST_SEMANTIC_SHA = canonical_sha256(
    manifest_semantic
)

manifest_payload = {
    **manifest_semantic,
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "semantic_sha256": M05_02_MANIFEST_SEMANTIC_SHA,
}

validation_gates = {
    "restore_contract":
        bool(M05_02_RESTORE_CONTRACT_DEFINED),
    "foundation_restore":
        bool(M05_02_FOUNDATION_RESTORE_PASS),
    "telemetry_restore":
        bool(M05_02_TELEMETRY_RESTORE_PASS),
    "formula_binding":
        bool(M05_02_FORMULA_BINDING_PASS),
    "partial_kpi":
        bool(M05_02_PARTIAL_KPI_PASS),
    "total_kpi":
        bool(M05_02_TOTAL_KPI_PASS),
    "formal_kpi_validation":
        bool(M05_02_FORMAL_KPI_VALIDATION_PASS),
    "healthy_validation":
        bool(M05_02_HEALTHY_VALIDATION_PASS),
    "kpi_files_persisted":
        bool(M05_02_KPI_FILES_PERSISTED),
}

receipt_semantic = {
    "artifact_id":
        "module5_m05_02_validation_receipt_v1",
    "module_id":
        "M05_02",
    "kpi_derivation_manifest_semantic_sha256":
        M05_02_MANIFEST_SEMANTIC_SHA,
    "validation_gates":
        validation_gates,
    "all_validation_gates_pass":
        all(validation_gates.values()),
    "authorized_next_stage":
        "M05_03_SIONNA_RADIO_REFERENCE_VALIDATION",
}

M05_02_VALIDATION_RECEIPT_SEMANTIC_SHA = canonical_sha256(
    receipt_semantic
)

receipt_payload = {
    **receipt_semantic,
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "semantic_sha256":
        M05_02_VALIDATION_RECEIPT_SEMANTIC_SHA,
}

MANIFEST_PATH = (
    M05_02_MANIFEST_DIR
    / "module5_m05_02_kpi_derivation_manifest_v1.json"
)
RECEIPT_PATH = (
    M05_02_MANIFEST_DIR
    / "module5_m05_02_validation_receipt_v1.json"
)

def persist_json_immutable(payload, path):
    path = Path(path)
    serialized = (
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
        )
        + "\n"
    )

    if path.exists():
        existing = load_json(path)
        if embedded_semantic_sha(existing) != payload["semantic_sha256"]:
            raise FileExistsError(
                "Different semantic artifact already exists: "
                + str(path)
            )
        operation = "VERIFIED_EXISTING"
    else:
        path.write_text(serialized, encoding="utf-8")
        operation = "CREATED"

    return {
        "path": str(path),
        "operation": operation,
        "artifact_sha256": sha256_file(path),
        "semantic_sha256": payload["semantic_sha256"],
    }

M05_02_MANIFEST_PERSISTENCE = persist_json_immutable(
    manifest_payload,
    MANIFEST_PATH,
)
M05_02_RECEIPT_PERSISTENCE = persist_json_immutable(
    receipt_payload,
    RECEIPT_PATH,
)

M05_02_PERSISTENCE_PASS = (
    receipt_payload["all_validation_gates_pass"]
)

print("=" * 108)
print("MODULE 5 — M05_02 CELL 19 — MANIFEST + VALIDATION RECEIPT")
print("=" * 108)
print(f"KPI manifest semantic SHA           : {M05_02_MANIFEST_SEMANTIC_SHA}")
print(f"Validation receipt semantic SHA     : {M05_02_VALIDATION_RECEIPT_SEMANTIC_SHA}")
print(f"All validation gates pass           : {receipt_payload['all_validation_gates_pass']}")
print(f"M05_02_PERSISTENCE_PASS             : {M05_02_PERSISTENCE_PASS}")

if not M05_02_PERSISTENCE_PASS:
    raise RuntimeError(
        "M05_02 validation receipt contains a failed gate."
    )


MODULE 5 — M05_02 CELL 19 — MANIFEST + VALIDATION RECEIPT
KPI manifest semantic SHA           : 3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e
Validation receipt semantic SHA     : 08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae
All validation gates pass           : True
M05_02_PERSISTENCE_PASS             : True


###### Cell 19 — Observation

The M05_02 KPI derivation manifest and validation receipt were created successfully, completing the provenance chain for the restored telemetry, formal KPI calculations and persisted outputs.

The KPI derivation manifest was assigned semantic SHA **`3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e`**, while the validation receipt was assigned semantic SHA **`08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae`**. All recorded validation gates passed successfully.

> **`M05_02_PERSISTENCE_PASS=True` — the formal Accessibility KPI outputs and their complete validation/provenance record are now durably established for downstream Module 5 use.**


<a id="cell-20"></a>
##### Cell 20 — M05_02 Closeout and M05_03 Handover

Runs the final notebook gate, summarizes the immutable restore/derivation lineage, and authorizes the validated healthy baseline for independent Sionna reference work in M05_03.


In [21]:
required_final_gates = {
    "M05_02_FOUNDATION_RESTORE_PASS":
        globals().get("M05_02_FOUNDATION_RESTORE_PASS", False),
    "M05_02_TELEMETRY_RESTORE_PASS":
        globals().get("M05_02_TELEMETRY_RESTORE_PASS", False),
    "M05_02_FORMULA_BINDING_PASS":
        globals().get("M05_02_FORMULA_BINDING_PASS", False),
    "M05_02_PARTIAL_KPI_PASS":
        globals().get("M05_02_PARTIAL_KPI_PASS", False),
    "M05_02_TOTAL_KPI_PASS":
        globals().get("M05_02_TOTAL_KPI_PASS", False),
    "M05_02_HEALTHY_VALIDATION_PASS":
        globals().get("M05_02_HEALTHY_VALIDATION_PASS", False),
    "M05_02_PERSISTENCE_PASS":
        globals().get("M05_02_PERSISTENCE_PASS", False),
}

failed = [
    name
    for name, passed in required_final_gates.items()
    if not passed
]

M05_02_CLOSEOUT_PASS = len(failed) == 0

print("=" * 108)
print("MODULE 5 — M05_02 CLOSEOUT")
print("=" * 108)

for name, passed in required_final_gates.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")

print("-" * 108)
print(f"M05_01 freeze semantic SHA          : {EXPECTED['m05_01_freeze_semantic_sha256']}")
print(f"Canonical telemetry semantic SHA   : {EXPECTED['canonical_dataset_semantic_sha256']}")
print(f"M05_02 KPI manifest semantic SHA    : {M05_02_MANIFEST_SEMANTIC_SHA}")
print(f"M05_02 validation receipt SHA       : {M05_02_VALIDATION_RECEIPT_SEMANTIC_SHA}")
print("-" * 108)
print(f"M05_02_CLOSEOUT_PASS                : {M05_02_CLOSEOUT_PASS}")
print("Next notebook                       : M05_03_Sionna_Radio_Reference_Validation_v1.ipynb")
print("M05_01 artifacts modified           : NO")
print("Fault injection introduced          : NO")
print("ML / LLM inference introduced       : NO")
print("=" * 108)

if failed:
    raise RuntimeError(
        "M05_02 closeout blocked by: "
        + ", ".join(failed)
    )


MODULE 5 — M05_02 CLOSEOUT
PASS    M05_02_FOUNDATION_RESTORE_PASS
PASS    M05_02_TELEMETRY_RESTORE_PASS
PASS    M05_02_FORMULA_BINDING_PASS
PASS    M05_02_PARTIAL_KPI_PASS
PASS    M05_02_TOTAL_KPI_PASS
PASS    M05_02_HEALTHY_VALIDATION_PASS
PASS    M05_02_PERSISTENCE_PASS
------------------------------------------------------------------------------------------------------------
M05_01 freeze semantic SHA          : 4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968
Canonical telemetry semantic SHA   : c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7
M05_02 KPI manifest semantic SHA    : 3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e
M05_02 validation receipt SHA       : 08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae
------------------------------------------------------------------------------------------------------------
M05_02_CLOSEOUT_PASS                : True
Next notebook                       : M05_03_Sionna_Rad

###### Cell 20 — Observation

M05_02 completed successfully with all required restoration, KPI derivation, healthy-baseline validation and persistence gates passing.

The notebook preserved the authoritative **M05_01 freeze** and **canonical V1.1 telemetry** without modification, and produced a fully validated M05_02 lineage anchored by KPI manifest semantic SHA **`3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e`** and validation receipt semantic SHA **`08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae`**.

No fault injection, ML inference or LLM inference was introduced, preserving M05_02 as a deterministic standards-grounded healthy-reference stage.

> **`M05_02_CLOSEOUT_PASS=True` — the corrected healthy telemetry foundation and formally derived Accessibility KPI baseline are frozen, validated and ready for independent radio-reference validation in `M05_03_Sionna_Radio_Reference_Validation_v1.ipynb`.**


##### M05_02 Handover

When `M05_02_CLOSEOUT_PASS=True`, the resulting KPI artifacts become the **validated healthy control baseline** for the next Module 5 stages.

```text
M05_01
Frozen standards + telemetry foundation
        ↓
M05_02
Restored foundation
+ formal Partial / Total DRB Accessibility
+ healthy KPI control baseline
        ↓
M05_03
Independent Sionna radio reference validation
        ↓
M05_04
Controlled incident generation + benchmark
```

Durable M05_02 output identities:

```text
NRCellCU Accessibility KPI Parquet
SHA-256: 709c9883bad799dec3907624a7590f5e44356d9fef7c00f4446d165fd1b2223f

SubNetwork Accessibility KPI Parquet
SHA-256: 18d5a60ca91139242e85e9f5468346a66bedf70f8736e01507568f2afb9c42ba

KPI derivation manifest semantic SHA
3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e

Validation receipt semantic SHA
08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae
```

Downstream notebooks should **restore and verify these frozen identities rather than replay M05_02**. The full 92-partition physical verification and formal KPI derivation are not repeated unless the authoritative upstream lineage changes.

No downstream notebook should reconstruct M05_02 KPI truth from an LLM. The persisted M05_02 results remain deterministic telemetry-derived evidence.
