# Module 5 — M05_03 Controlled Incidents and Benchmark

**Structured filename:** `M05_03_Controlled_Incidents_and_Benchmark_v1.ipynb`

This notebook is the third executable stage of **Module 5 — Agentic Telecom AI** in the Telecom AI Engineering Platform.

It converts the frozen healthy network foundation into a controlled **telecom investigation benchmark**. Future agents must discover incidents from standards-grounded formula evidence, diagnostic telemetry, topology and chronology rather than from exposed fault labels.

> **North Star:** The LLM orchestrates. Deterministic telemetry supplies network truth. Standards knowledge provides grounding. ML supplies probabilistic evidence. Policy controls actions. Verification closes the loop.


##### Introduction — Goal

The goal of M05_03 is to create a deterministic, auditable and diagnosable set of **5G RAN Accessibility investigation challenges** without modifying the authoritative M05_01 healthy telemetry or the formal M05_02 KPI products.

The notebook will:

- restore the validated M05_01/M05_02 lineage without rebuilding it;
- define a bounded first incident bank within the existing Accessibility causal domain;
- create incident **overlays on copied healthy observation windows**, never on the canonical source;
- preserve mathematically valid standardized PM hierarchies;
- include positive evidence, exclusion evidence, topology context and limited non-causal distractors;
- recompute the two formal Accessibility KPIs from the modified PM counters;
- separate **agent-visible evidence** from **hidden benchmark truth**;
- reserve a held-out evaluation subset;
- and persist immutable benchmark artifacts for the Telemetry MCP and later agent evaluation.


##### Introduction — Specific Research Question

> **Can a controlled synthetic benchmark create realistic 5G RAN Accessibility incidents whose root causes are discoverable from observable evidence, distinguishable from plausible competing hypotheses, mathematically consistent with the formal KPI layer, and hidden from the future agent until independent evaluation?**

M05_03 does **not** evaluate an LLM yet. Its job is to create the challenges the later agent must solve.


##### Introduction — Architectural Boundary

```text
M05_01
Frozen healthy telemetry + causal observability
        │
        ▼
M05_02
Formal Partial / Total DRB Accessibility + healthy baseline
        │
        │ immutable upstream truth
        ▼
M05_03
Controlled incident overlays on copied windows
        │
        ├── agent-visible telemetry / KPIs / events / public cases
        │
        └── PRIVATE hidden truth / development labels / audit
        ▼
M05_04
Telemetry MCP
        ▼
M05_05
Specialist ML MCP
        ▼
M05_06
LangGraph agent investigation
```

**M05_01 and M05_02 remain the sole authoritative healthy network-truth foundation.** M05_03 never writes into their directories.


##### Introduction — Sionna Roadmap Decision

The earlier roadmap placed an independent Sionna radio-reference notebook before incident generation. That experiment is now **deferred**, not rejected.

M05_02 is immutable and therefore its historical `authorized_next_stage` value is preserved. M05_03 records a new roadmap-amendment artifact:

```text
Previous planned next stage : M05_03 Sionna Radio Reference Validation
Decision                    : DEFER
Current M05_03              : Controlled Incidents + Benchmark
Reason                      : preserve a single clear network-truth pipeline;
                              introduce external radio simulation only when a
                              specific radio-physics question requires it
```

No M05_02 artifact is rewritten merely to change the roadmap.


##### Introduction — Benchmark Design Principles

The incident bank follows the causal-observability rules already established in Module 5:

1. **Root cause is hidden.**
2. **Every admitted fault has observable positive evidence.**
3. **Every admitted fault has exclusion evidence** that helps reject nearby hypotheses.
4. **Topology scope matters** — cell, site, CU domain or RAN/Core boundary.
5. **Chronology matters** — pre-incident, active incident and recovery intervals are retained.
6. **Distractors are non-causal** and must not become a second hidden fault.
7. **Formal KPI values are recomputed from PM counters**; they are never directly injected.
8. **Operational thresholds are synthetic design choices**, not represented as 3GPP requirements.
9. **Healthy controls are included** so the future agent can be penalized for inventing incidents.
10. **Evaluation cases are held out** from the development-label artifact.


##### Introduction — Initial Formal Incident Bank

The first benchmark deliberately uses a **bounded subset** of the broader causal catalogue rather than exercising all 37 declared fault concepts at once.

| Family | Primary scope | Main discriminating idea |
|---|---|---|
| `HEALTHY_CONTROL` | full network | natural healthy variability only |
| `RADIO_INTERFERENCE` | cell | SINR/BLER degrade while RSRP/load remain broadly normal |
| `RADIO_RESOURCE_CONGESTION` | site | PRB/load/admission pressure increase while radio quality remains healthy |
| `N2_PACKET_LOSS_LATENCY` | CU domain / N2 path | NG stage degrades with N2 loss/latency evidence while radio/CU-CP remain healthy |
| `CU_CP_PROCESSING_PRESSURE` | CU domain | NG stage degrades with CU-CP CPU/queue/delay evidence while N2 remains healthy |
| `QOS_CONFIGURATION` | cell + 5QI 1 | 5QI-specific DRB degradation correlated with a QoS configuration change |
| `RRC_CONFIGURATION` | cell | RRC establishment degrades after an RRC-profile change while radio/load remain healthy |
| `AMF_FACING_BOUNDARY` | CU-domain boundary | NG stage degrades with RAN-observed AMF reachability/peer evidence while internal RAN/N2 evidence remains healthy |

The AMF case is intentionally **boundary-scoped**. The benchmark must not claim an internal 5GC root cause that the RAN evidence cannot prove.


##### Introduction — Episode and Split Policy

The V1 benchmark contains:

```text
8 case families
× 4 deterministic episodes per family
= 32 benchmark cases

Per family:
3 DEVELOPMENT cases
1 held-out EVAL case
```

Each case contains a **4-hour observation window**:

```text
1 hour healthy pre-window
2 hours active incident window
1 hour recovery window

16 × 15-minute intervals per case
```

The future agent receives the complete 4-hour observation window but does **not** receive the phase boundaries.


##### Introduction — Truth Separation

```text
AGENT-VISIBLE                                      PRIVATE / EVALUATION ONLY
──────────────────────────────────                 ─────────────────────────────
opaque scenario_id                                 root-cause family
observation timestamps                             injected target
telemetry / PM counters                            severity profile
derived KPIs                                       expected diagnosis
events / configuration observations                competing hypotheses
public investigation task                          expected positive evidence
                                                   expected exclusion evidence
                                                   distractor identity
                                                   DEVELOPMENT / EVAL labels
```

The future Telemetry MCP and agent must never load the `private/` directory.


##### Introduction — Expected Outputs

M05_03 persists a new versioned result set under:

```text
/content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_03/

benchmark/
  module5_m05_03_agent_visible_telemetry_v1.parquet
  module5_m05_03_agent_visible_cell_kpis_v1.parquet
  module5_m05_03_agent_visible_subnetwork_kpis_v1.parquet
  module5_m05_03_agent_visible_events_v1.parquet
  module5_m05_03_benchmark_cases_v1.json

private/
  module5_m05_03_ground_truth_v1.json
  module5_m05_03_development_labels_v1.parquet
  module5_m05_03_injection_audit_summary_v1.parquet

manifests/
  module5_m05_03_roadmap_amendment_v1.json
  module5_m05_03_incident_benchmark_manifest_v1.json
  module5_m05_03_validation_receipt_v1.json
```

The `private/` artifacts are retained only for benchmark construction, ML development and independent scoring.


##### Introduction — Completion Gate

M05_03 is complete only when:

```text
✓ upstream M05_01/M05_02 lineage is validated
✓ roadmap amendment is explicitly recorded
✓ required telemetry evidence exists
✓ topology is complete
✓ incident definitions satisfy diagnosability rules
✓ 32 deterministic cases are scheduled without overlap
✓ canonical healthy data is copied, never modified
✓ incident overlays affect only intended active windows
✓ public telemetry contains no hidden-truth fields
✓ formal Accessibility KPIs remain mathematically valid
✓ pre/recovery and healthy-control KPI values reproduce M05_02
✓ every admitted fault has positive + exclusion evidence
✓ public benchmark cases and private truth are separated
✓ EVAL labels are excluded from development labels
✓ outputs are persisted immutably with hashes
✓ M05_03_CLOSEOUT_PASS=True
```


#### Searchable Table of Contents

##### Sections

- [Section 1 — Upstream Trust and Runtime](#section-1-upstream-trust)
- [Section 2 — Benchmark Contract and Topology](#section-2-benchmark-contract)
- [Section 3 — Incident Schedule and Healthy Copies](#section-3-incident-schedule)
- [Section 4 — Controlled Incident Overlays](#section-4-controlled-overlays)
- [Section 5 — Sanitization and Formal KPI Recalculation](#section-5-sanitization-kpi)
- [Section 6 — Causal Diagnosability and Truth Separation](#section-6-diagnosability)
- [Section 7 — Persistence, Manifest and Closeout](#section-7-persistence-closeout)

##### Code Cell Index

| Cell | Purpose | Gate |
|---|---|---|
| 01 | consolidated upstream provenance validation | `M05_03_UPSTREAM_RESTORE_PASS` |
| 02 | roadmap amendment + benchmark contract | `M05_03_BENCHMARK_CONTRACT_PASS` |
| 03 | DuckDB healthy telemetry view + evidence inventory | `M05_03_TELEMETRY_RUNTIME_PASS` |
| 04 | topology inventory + target maps | `M05_03_TOPOLOGY_PASS` |
| 05 | freeze incident-family definitions | `M05_03_INCIDENT_DESIGN_PASS` |
| 06 | deterministic 32-case schedule + splits | `M05_03_EPISODE_SCHEDULE_PASS` |
| 07 | copy healthy 4-hour case windows | `M05_03_BASE_SLICE_PASS` |
| 08 | apply numeric incident overlays | `M05_03_NUMERIC_OVERLAY_PASS` |
| 09 | context/event overlays + non-causal distractors | `M05_03_CONTEXT_OVERLAY_PASS` |
| 10 | sanitize agent-visible evidence + leakage gate | `M05_03_LEAKAGE_PASS` |
| 11 | recompute formal Partial/Total Accessibility | `M05_03_SCENARIO_KPI_PASS` |
| 12 | KPI completeness/math + upstream reproduction | `M05_03_KPI_VALIDATION_PASS` |
| 13 | causal-signature and exclusion-evidence validation | `M05_03_CAUSAL_SIGNATURE_PASS` |
| 14 | diagnosability / competing-hypothesis gate | `M05_03_DIAGNOSABILITY_PASS` |
| 15 | public benchmark cases + private ground truth | `M05_03_TRUTH_SEPARATION_PASS` |
| 16 | DEVELOPMENT/EVAL isolation + ML development labels | `M05_03_SPLIT_ISOLATION_PASS` |
| 17 | immutable output persistence | `M05_03_OUTPUT_PERSISTENCE_PASS` |
| 18 | benchmark manifest + validation receipt | `M05_03_PERSISTENCE_PASS` |
| 19 | closeout and M05_04 handover | `M05_03_CLOSEOUT_PASS` |


<a id="section-1-upstream-trust"></a>
# Section 1 — Upstream Trust and Runtime

M05_03 begins from the validated M05_02 closeout rather than replaying the complete M05_01/M05_02 build.


<a id="cell-01"></a>
##### Cell 01 — Consolidated Upstream Provenance Validation

This cell mounts Google Drive, qualifies DuckDB if required, validates the frozen M05_02 manifest/receipt identities, verifies the two persisted KPI Parquet files, and confirms that the M05_01 canonical telemetry source still exists.

The historical Sionna authorization in the immutable M05_02 receipt is **verified but not treated as the current roadmap**. Cell 02 records the explicit amendment.


In [1]:
from pathlib import Path
from datetime import datetime, timezone, timedelta
import hashlib
import importlib.util
import json
import subprocess
import sys

import numpy as np
import pandas as pd
from google.colab import drive

MODULE_ID = "M05_03"
NOTEBOOK_VERSION = "V1"

drive.mount("/content/drive")

if importlib.util.find_spec("duckdb") is None:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q",
        "duckdb>=1.1,<2",
    ])

import duckdb

PLATFORM_ROOT = Path(
    "/content/drive/MyDrive/Telecom_AI_Engineering_Platform"
)
M05_01_ROOT = PLATFORM_ROOT / "Module_5" / "M05_01"
M05_02_ROOT = PLATFORM_ROOT / "Module_5" / "M05_02"
M05_03_ROOT = PLATFORM_ROOT / "Module_5" / "M05_03"

TELEMETRY_DIR = (
    M05_01_ROOT / "telemetry" / "healthy_baseline_v1_1"
)
M05_02_KPI_DIR = M05_02_ROOT / "kpi"
M05_02_MANIFEST_DIR = M05_02_ROOT / "manifests"

NR_CELL_KPI_PATH = (
    M05_02_KPI_DIR
    / "module5_m05_02_nr_cell_cu_accessibility_kpis_v1.parquet"
)
SUBNETWORK_KPI_PATH = (
    M05_02_KPI_DIR
    / "module5_m05_02_subnetwork_accessibility_kpis_v1.parquet"
)
M05_02_MANIFEST_PATH = (
    M05_02_MANIFEST_DIR
    / "module5_m05_02_kpi_derivation_manifest_v1.json"
)
M05_02_RECEIPT_PATH = (
    M05_02_MANIFEST_DIR
    / "module5_m05_02_validation_receipt_v1.json"
)

M05_03_BENCHMARK_DIR = M05_03_ROOT / "benchmark"
M05_03_PRIVATE_DIR = M05_03_ROOT / "private"
M05_03_MANIFEST_DIR = M05_03_ROOT / "manifests"

EXPECTED = {
    "m05_01_freeze_semantic_sha256":
        "4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968",
    "canonical_telemetry_semantic_sha256":
        "c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7",
    "m05_02_kpi_manifest_semantic_sha256":
        "3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e",
    "m05_02_validation_receipt_semantic_sha256":
        "08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae",
    "nr_cell_kpi_sha256":
        "709c9883bad799dec3907624a7590f5e44356d9fef7c00f4446d165fd1b2223f",
    "subnetwork_kpi_sha256":
        "18d5a60ca91139242e85e9f5468346a66bedf70f8736e01507568f2afb9c42ba",
    "historical_authorized_next_stage":
        "M05_03_SIONNA_RADIO_REFERENCE_VALIDATION",
}

def sha256_file(path, chunk_size=1024 * 1024):
    path = Path(path)
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            hasher.update(chunk)
    return hasher.hexdigest()

def canonical_sha256(payload):
    raw = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()

def semantic_sha_from_persisted_json(payload):
    semantic_payload = {
        key: value
        for key, value in payload.items()
        if key not in {"created_utc", "semantic_sha256"}
    }
    return canonical_sha256(semantic_payload)

def load_json(path):
    with Path(path).open("r", encoding="utf-8") as handle:
        return json.load(handle)

required_paths = {
    "canonical_telemetry_dir": TELEMETRY_DIR,
    "m05_02_nr_cell_kpis": NR_CELL_KPI_PATH,
    "m05_02_subnetwork_kpis": SUBNETWORK_KPI_PATH,
    "m05_02_manifest": M05_02_MANIFEST_PATH,
    "m05_02_validation_receipt": M05_02_RECEIPT_PATH,
}
missing_paths = [
    name for name, path in required_paths.items()
    if not path.exists()
]
if missing_paths:
    raise FileNotFoundError(
        "Missing authoritative upstream sources: "
        + ", ".join(missing_paths)
    )

M05_02_MANIFEST = load_json(M05_02_MANIFEST_PATH)
M05_02_RECEIPT = load_json(M05_02_RECEIPT_PATH)

manifest_semantic = semantic_sha_from_persisted_json(
    M05_02_MANIFEST
)
receipt_semantic = semantic_sha_from_persisted_json(
    M05_02_RECEIPT
)
manifest_text = json.dumps(M05_02_MANIFEST, sort_keys=True)

checks = {
    "m05_02_manifest_semantic_identity":
        manifest_semantic
        == EXPECTED["m05_02_kpi_manifest_semantic_sha256"],
    "m05_02_receipt_semantic_identity":
        receipt_semantic
        == EXPECTED["m05_02_validation_receipt_semantic_sha256"],
    "m05_01_freeze_bound_by_m05_02":
        EXPECTED["m05_01_freeze_semantic_sha256"]
        in manifest_text,
    "canonical_telemetry_bound_by_m05_02":
        EXPECTED["canonical_telemetry_semantic_sha256"]
        in manifest_text,
    "nr_cell_kpi_byte_identity":
        sha256_file(NR_CELL_KPI_PATH)
        == EXPECTED["nr_cell_kpi_sha256"],
    "subnetwork_kpi_byte_identity":
        sha256_file(SUBNETWORK_KPI_PATH)
        == EXPECTED["subnetwork_kpi_sha256"],
    "m05_02_all_validation_gates_pass":
        bool(M05_02_RECEIPT.get("all_validation_gates_pass")),
    "m05_02_manifest_bound_by_receipt":
        M05_02_RECEIPT.get(
            "kpi_derivation_manifest_semantic_sha256"
        )
        == EXPECTED["m05_02_kpi_manifest_semantic_sha256"],
    "historical_next_stage_preserved":
        M05_02_RECEIPT.get("authorized_next_stage")
        == EXPECTED["historical_authorized_next_stage"],
}

print("=" * 108)
print("MODULE 5 — M05_03 CELL 01 — CONSOLIDATED UPSTREAM PROVENANCE VALIDATION")
print("=" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print("M05_01 freeze semantic SHA          :", EXPECTED["m05_01_freeze_semantic_sha256"])
print("Canonical telemetry semantic SHA   :", EXPECTED["canonical_telemetry_semantic_sha256"])
print("M05_02 KPI manifest semantic SHA    :", manifest_semantic)
print("M05_02 validation receipt SHA       :", receipt_semantic)
print("Historical authorized next stage   :", M05_02_RECEIPT.get("authorized_next_stage"))
print("Current roadmap amendment           : CELL 02")
print("Full M05_01/M05_02 rebuild replayed : NO")
print("GPU required                        : NO")
print("=" * 108)

failed = [name for name, passed in checks.items() if not passed]
if failed:
    raise RuntimeError(
        "M05_03 upstream restore blocked by: "
        + ", ".join(failed)
    )

M05_03_UPSTREAM_RESTORE_PASS = True
print("\nM05_03_UPSTREAM_RESTORE_PASS        :", M05_03_UPSTREAM_RESTORE_PASS)


Mounted at /content/drive
MODULE 5 — M05_03 CELL 01 — CONSOLIDATED UPSTREAM PROVENANCE VALIDATION
PASS    m05_02_manifest_semantic_identity
PASS    m05_02_receipt_semantic_identity
PASS    m05_01_freeze_bound_by_m05_02
PASS    canonical_telemetry_bound_by_m05_02
PASS    nr_cell_kpi_byte_identity
PASS    subnetwork_kpi_byte_identity
PASS    m05_02_all_validation_gates_pass
PASS    m05_02_manifest_bound_by_receipt
PASS    historical_next_stage_preserved
------------------------------------------------------------------------------------------------------------
M05_01 freeze semantic SHA          : 4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968
Canonical telemetry semantic SHA   : c1fb3a49eacd63f45a98986322d536b74d21e585ff8bc49a4649ef11b3b34cd7
M05_02 KPI manifest semantic SHA    : 3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e
M05_02 validation receipt SHA       : 08d12c9564b3d5dff14f4770a3bfbf0d4853df1a3dcbbfd824511102051b66ae
Historical authorized ne

###### Observation

All upstream provenance checks passed. M05_03 successfully verified the frozen M05_01/M05_02 identities and KPI artifacts without rebuilding prior stages. The historical Sionna handover remains preserved and will be formally amended in Cell 02.


<a id="section-2-benchmark-contract"></a>
# Section 2 — Benchmark Contract and Topology


<a id="cell-02"></a>
##### Cell 02 — Roadmap Amendment and Benchmark Contract

This cell records the Sionna deferral as a **new semantic roadmap amendment** and freezes the V1 benchmark policy. It does not rewrite the M05_02 receipt.


In [2]:
if not globals().get("M05_03_UPSTREAM_RESTORE_PASS", False):
    raise RuntimeError("Cell 02 requires Cell 01.")

ROADMAP_AMENDMENT_SEMANTIC = {
    "artifact_id": "module5_m05_03_roadmap_amendment_v1",
    "module_id": "M05_03",
    "previous_authorized_stage":
        M05_02_RECEIPT["authorized_next_stage"],
    "decision": "DEFER_SIONNA",
    "sionna_status": "OPTIONAL_FUTURE_RADIO_REFERENCE",
    "current_stage": "M05_03_CONTROLLED_INCIDENTS_AND_BENCHMARK",
    "reason": (
        "Preserve a single clear M05_01/M05_02 network-truth "
        "foundation and introduce an external radio simulator only "
        "when a specific radio-physics validation question requires it."
    ),
    "m05_02_mutated": False,
}
M05_03_ROADMAP_AMENDMENT_SEMANTIC_SHA = canonical_sha256(
    ROADMAP_AMENDMENT_SEMANTIC
)
ROADMAP_AMENDMENT_PAYLOAD = {
    **ROADMAP_AMENDMENT_SEMANTIC,
    "created_utc": datetime.now(timezone.utc).isoformat(),
    "semantic_sha256": M05_03_ROADMAP_AMENDMENT_SEMANTIC_SHA,
}

CASE_FAMILIES = [
    "HEALTHY_CONTROL",
    "RADIO_INTERFERENCE",
    "RADIO_RESOURCE_CONGESTION",
    "N2_PACKET_LOSS_LATENCY",
    "CU_CP_PROCESSING_PRESSURE",
    "QOS_CONFIGURATION",
    "RRC_CONFIGURATION",
    "AMF_FACING_BOUNDARY",
]

BENCHMARK_POLICY = {
    "benchmark_version": "V1",
    "case_families": CASE_FAMILIES,
    "episodes_per_family": 4,
    "development_episodes_per_family": 3,
    "eval_episodes_per_family": 1,
    "case_window_hours": 4,
    "pre_window_hours": 1,
    "incident_window_hours": 2,
    "recovery_window_hours": 1,
    "pm_interval_minutes": 15,
    "agent_receives_phase_boundaries": False,
    "healthy_control_included": True,
    "canonical_source_mutation_permitted": False,
    "direct_kpi_injection_permitted": False,
    "formal_kpis_recomputed_from_pm": True,
    "sionna_used": False,
    "ml_inference_used": False,
    "llm_inference_used": False,
    "forbidden_agent_visible_fields": [
        "root_cause", "ground_truth", "fault_label",
        "expected_diagnosis", "correct_action", "benchmark_answer",
        "family_internal", "severity", "phase",
        "target_entity", "target_site", "target_cu_domain",
    ],
}

expected_cases = len(CASE_FAMILIES) * BENCHMARK_POLICY["episodes_per_family"]
checks = {
    "eight_case_families": len(CASE_FAMILIES) == 8,
    "thirty_two_total_cases": expected_cases == 32,
    "one_eval_case_per_family":
        BENCHMARK_POLICY["eval_episodes_per_family"] == 1,
    "four_hour_case_window":
        (
            BENCHMARK_POLICY["pre_window_hours"]
            + BENCHMARK_POLICY["incident_window_hours"]
            + BENCHMARK_POLICY["recovery_window_hours"]
        ) == BENCHMARK_POLICY["case_window_hours"],
    "canonical_mutation_forbidden":
        not BENCHMARK_POLICY["canonical_source_mutation_permitted"],
    "direct_kpi_injection_forbidden":
        not BENCHMARK_POLICY["direct_kpi_injection_permitted"],
    "sionna_deferred":
        ROADMAP_AMENDMENT_SEMANTIC["decision"] == "DEFER_SIONNA",
    "m05_02_preserved":
        not ROADMAP_AMENDMENT_SEMANTIC["m05_02_mutated"],
}

print("=" * 108)
print("MODULE 5 — M05_03 CELL 02 — ROADMAP AMENDMENT + BENCHMARK CONTRACT")
print("=" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print("Roadmap amendment semantic SHA     :", M05_03_ROADMAP_AMENDMENT_SEMANTIC_SHA)
print("Case families                      :", len(CASE_FAMILIES))
print("Total benchmark cases              :", expected_cases)
print("DEVELOPMENT / EVAL per family      : 3 / 1")
print("Sionna active in M05_03            : NO")

failed = [name for name, passed in checks.items() if not passed]
if failed:
    raise RuntimeError(
        "M05_03 benchmark contract failed: " + ", ".join(failed)
    )

M05_03_BENCHMARK_CONTRACT_PASS = True
print("\nM05_03_BENCHMARK_CONTRACT_PASS     :", M05_03_BENCHMARK_CONTRACT_PASS)


MODULE 5 — M05_03 CELL 02 — ROADMAP AMENDMENT + BENCHMARK CONTRACT
PASS    eight_case_families
PASS    thirty_two_total_cases
PASS    one_eval_case_per_family
PASS    four_hour_case_window
PASS    canonical_mutation_forbidden
PASS    direct_kpi_injection_forbidden
PASS    sionna_deferred
PASS    m05_02_preserved
------------------------------------------------------------------------------------------------------------
Roadmap amendment semantic SHA     : 49e934eee8af16281615a923248ee29768e5ca9d282cdd194712a0fcb260b057
Case families                      : 8
Total benchmark cases              : 32
DEVELOPMENT / EVAL per family      : 3 / 1
Sionna active in M05_03            : NO

M05_03_BENCHMARK_CONTRACT_PASS     : True


###### Observation

The revised M05_03 roadmap and benchmark contract passed all validation checks. Sionna is formally deferred, while a 32-case benchmark is authorized across 8 case families, with 24 DEVELOPMENT and 8 held-out EVAL scenarios. The contract also protects the frozen M05_01/M05_02 lineage by forbidding canonical telemetry mutation and direct KPI injection.


<a id="cell-03"></a>
##### Cell 03 — Healthy Telemetry Runtime View and Evidence Inventory

DuckDB exposes the frozen 92-day telemetry as a logical query layer. Only the metric families required by the selected benchmark are qualified here.

Event channels are intentionally absent from the healthy dataset and will be created only when a controlled incident legitimately generates an event.


In [3]:
if not globals().get("M05_03_BENCHMARK_CONTRACT_PASS", False):
    raise RuntimeError("Cell 03 requires Cell 02.")

DUCKDB_PATH = Path("/content/module5_m05_03_runtime.duckdb")
if DUCKDB_PATH.exists():
    DUCKDB_PATH.unlink()

con = duckdb.connect(str(DUCKDB_PATH))
con.execute("PRAGMA threads=4")

parquet_glob = str(
    TELEMETRY_DIR / "date=*" / "observations.parquet"
).replace("\\", "/")

con.execute(f"""
CREATE OR REPLACE VIEW healthy_telemetry AS
SELECT *
FROM read_parquet('{parquet_glob}', union_by_name=true)
""")

REQUIRED_STANDARDIZED_METRICS = {
    "RRC.ConnEstabAtt.Cause", "RRC.ConnEstabSucc.Cause",
    "UECNTX.ConnEstabAtt.Cause", "UECNTX.ConnEstabSucc.Cause",
    "DRB.InitialEstabAtt.5QI", "DRB.InitialEstabSucc.5QI",
    "DRB.EstabAtt.5QI", "DRB.EstabSucc.5QI",
    "RRC.ResumeAtt.Cause", "RRC.ResumeSucc.Cause",
    "RRC.ResumeFallbackToSetupAtt.cause",
    "RRC.ResumeSuccByFallback.cause",
    "RRC.ReEstabFallbackToSetupAtt",
    "RRC.ReEstabSuccWithoutUeContext",
    "DRB.ResumeAtt.5QI", "DRB.ResumeSucc.5QI",
}

REQUIRED_OPERATIONAL_METRICS = {
    "radio.rsrp_dbm", "radio.sinr_db",
    "radio.dl_bler_pct", "radio.ul_bler_pct",
    "resource.dl_prb_util_pct", "resource.ul_prb_util_pct",
    "resource.scheduler_pressure_pct",
    "resource.bearer_admission_pressure_pct",
    "load.connected_ues", "load.active_ues",
    "processing.du_cpu_pct",
    "processing.cu_cp_cpu_pct", "processing.cu_cp_memory_pct",
    "processing.cu_cp_control_queue_depth",
    "processing.cu_cp_control_delay_ms",
    "transport.n2_util_pct", "transport.n2_latency_ms",
    "transport.n2_packet_loss_pct",
    "sctp.association_state", "sctp.retransmissions",
    "sctp.heartbeat_failures",
    "boundary.amf_reachable", "boundary.amf_peer_state",
    "boundary.amf_overload_indication",
    "config.qos_profile_state", "config.rrc_profile_state",
}

required_schema_columns = {
    "metric_name", "is_standardized_metric", "entity_id",
    "entity_type", "operational_scope", "site_id", "cu_domain_id",
    "interval_start_utc", "interval_end_utc", "value_kind",
    "value_int", "value_float", "value_bool", "value_text",
    "dimension_cause", "dimension_5qi", "dimension_snssai",
    "metadata_json",
}

schema_df = con.execute("DESCRIBE healthy_telemetry").df()
observed_columns = set(schema_df["column_name"].astype(str))
observed_metrics = set(
    con.execute("SELECT DISTINCT metric_name FROM healthy_telemetry")
    .df()["metric_name"].astype(str)
)

missing_schema = sorted(required_schema_columns - observed_columns)
missing_standardized = sorted(
    REQUIRED_STANDARDIZED_METRICS - observed_metrics
)
missing_operational = sorted(
    REQUIRED_OPERATIONAL_METRICS - observed_metrics
)

runtime_summary = con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT interval_start_utc) AS intervals,
    COUNT(*) / COUNT(DISTINCT interval_start_utc) AS rows_per_interval,
    COUNT(DISTINCT metric_name) AS observed_metric_families,
    MIN(interval_start_utc) AS first_interval,
    MAX(interval_start_utc) AS last_interval
FROM healthy_telemetry
""").df()

ROWS_PER_INTERVAL = int(runtime_summary.loc[0, "rows_per_interval"])

print("=" * 108)
print("MODULE 5 — M05_03 CELL 03 — HEALTHY TELEMETRY RUNTIME + EVIDENCE INVENTORY")
print("=" * 108)
print(runtime_summary.to_string(index=False))
print("-" * 108)
print("Missing schema columns              :", missing_schema)
print("Missing standardized requirements   :", missing_standardized)
print("Missing operational requirements    :", missing_operational)
print("Healthy event rows expected         : 0")
print("Event channels generated in M05_03  : ONLY WHEN INCIDENT REQUIRES")

if missing_schema or missing_standardized or missing_operational:
    raise RuntimeError("M05_03 required telemetry evidence is incomplete.")

M05_03_TELEMETRY_RUNTIME_PASS = True
print("\nM05_03_TELEMETRY_RUNTIME_PASS       :", M05_03_TELEMETRY_RUNTIME_PASS)


MODULE 5 — M05_03 CELL 03 — HEALTHY TELEMETRY RUNTIME + EVIDENCE INVENTORY
    rows  intervals  rows_per_interval  observed_metric_families            first_interval             last_interval
18829824       8832             2132.0                        66 2026-06-01 00:00:00+00:00 2026-08-31 23:45:00+00:00
------------------------------------------------------------------------------------------------------------
Missing schema columns              : []
Missing standardized requirements   : []
Missing operational requirements    : []
Healthy event rows expected         : 0
Event channels generated in M05_03  : ONLY WHEN INCIDENT REQUIRES

M05_03_TELEMETRY_RUNTIME_PASS       : True


###### Observation

The healthy telemetry runtime view was successfully restored from the canonical M05_01 baseline, covering 18,829,824 observations across 8,832 15-minute intervals with the expected 2,132 rows per interval. All required standardized PM and operational evidence families are available with no schema gaps, while healthy event channels remain empty as designed and will only be populated for relevant incident scenarios.

<a id="cell-04"></a>
##### Cell 04 — Topology Inventory and Deterministic Target Maps

This cell reconstructs only the mappings required by the benchmark:

- NRCellCU ↔ NRCellDU within each site;
- site ↔ CU domain;
- CU domain ↔ CU-CP / N2 path / AMF-facing peer.

The mapping is derived from canonical observations rather than recreated from memory.


In [4]:
if not globals().get("M05_03_TELEMETRY_RUNTIME_PASS", False):
    raise RuntimeError("Cell 04 requires Cell 03.")

con.execute("""
CREATE OR REPLACE TABLE m05_03_cell_map AS
WITH
cu AS (
    SELECT DISTINCT entity_id AS nr_cell_cu_id, site_id, cu_domain_id
    FROM healthy_telemetry
    WHERE entity_type = 'NR_CELL_CU'
),
du AS (
    SELECT DISTINCT entity_id AS nr_cell_du_id, site_id, cu_domain_id
    FROM healthy_telemetry
    WHERE entity_type = 'NR_CELL_DU'
),
cu_ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY site_id ORDER BY nr_cell_cu_id
           ) AS sector_rank
    FROM cu
),
du_ranked AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY site_id ORDER BY nr_cell_du_id
           ) AS sector_rank
    FROM du
)
SELECT
    c.site_id, c.cu_domain_id, c.sector_rank,
    c.nr_cell_cu_id, d.nr_cell_du_id
FROM cu_ranked AS c
JOIN du_ranked AS d
  ON c.site_id = d.site_id
 AND c.cu_domain_id = d.cu_domain_id
 AND c.sector_rank = d.sector_rank
ORDER BY c.site_id, c.sector_rank
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_domain_map AS
SELECT
    cu_domain_id,
    MAX(CASE WHEN operational_scope = 'CU_CP' THEN entity_id END) AS cu_cp_id,
    MAX(CASE WHEN operational_scope = 'N2_PATH' THEN entity_id END) AS n2_path_id,
    MAX(CASE WHEN operational_scope = 'AMF_PEER' THEN entity_id END) AS amf_peer_id
FROM healthy_telemetry
WHERE cu_domain_id IS NOT NULL
GROUP BY cu_domain_id
ORDER BY cu_domain_id
""")

CELL_MAP_DF = con.execute("SELECT * FROM m05_03_cell_map").df()
DOMAIN_MAP_DF = con.execute("SELECT * FROM m05_03_domain_map").df()

topology_diag = con.execute("""
SELECT
    COUNT(DISTINCT site_id) AS sites,
    COUNT(DISTINCT nr_cell_cu_id) AS nr_cell_cu,
    COUNT(DISTINCT nr_cell_du_id) AS nr_cell_du,
    COUNT(DISTINCT cu_domain_id) AS cu_domains,
    MIN(sector_rank) AS min_sector_rank,
    MAX(sector_rank) AS max_sector_rank
FROM m05_03_cell_map
""").df()

domain_nulls = int(
    DOMAIN_MAP_DF[["cu_cp_id", "n2_path_id", "amf_peer_id"]]
    .isna().sum().sum()
)

checks = {
    "sites_10": int(topology_diag.loc[0, "sites"]) == 10,
    "nr_cell_cu_30": int(topology_diag.loc[0, "nr_cell_cu"]) == 30,
    "nr_cell_du_30": int(topology_diag.loc[0, "nr_cell_du"]) == 30,
    "cu_domains_2": int(topology_diag.loc[0, "cu_domains"]) == 2,
    "three_sectors_per_site":
        int(topology_diag.loc[0, "min_sector_rank"]) == 1
        and int(topology_diag.loc[0, "max_sector_rank"]) == 3,
    "domain_operational_identities_complete": domain_nulls == 0,
}

print("=" * 108)
print("MODULE 5 — M05_03 CELL 04 — TOPOLOGY INVENTORY")
print("=" * 108)
print(topology_diag.to_string(index=False))
print("\nCU-domain operational identities")
print("-" * 108)
print(DOMAIN_MAP_DF.to_string(index=False))
print("-" * 108)
for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")

failed = [name for name, passed in checks.items() if not passed]
if failed:
    raise RuntimeError(
        "M05_03 topology qualification failed: " + ", ".join(failed)
    )

M05_03_TOPOLOGY_PASS = True
print("\nM05_03_TOPOLOGY_PASS                :", M05_03_TOPOLOGY_PASS)


MODULE 5 — M05_03 CELL 04 — TOPOLOGY INVENTORY
 sites  nr_cell_cu  nr_cell_du  cu_domains  min_sector_rank  max_sector_rank
    10          30          30           2                1                3

CU-domain operational identities
------------------------------------------------------------------------------------------------------------
cu_domain_id cu_cp_id n2_path_id amf_peer_id
CU_DOMAIN_01 CU_CP_01 N2_PATH_01 AMF_PEER_01
CU_DOMAIN_02 CU_CP_02 N2_PATH_02 AMF_PEER_02
------------------------------------------------------------------------------------------------------------
PASS    sites_10
PASS    nr_cell_cu_30
PASS    nr_cell_du_30
PASS    cu_domains_2
PASS    three_sectors_per_site
PASS    domain_operational_identities_complete

M05_03_TOPOLOGY_PASS                : True


###### Observation

The topology inventory passed all checks, confirming 10 sites, 30 NRCellCU, 30 NRCellDU, 3 sectors per site, and 2 CU domains. Shared CU-CP, N2 path, and AMF peer identities are complete, providing the hierarchical scope needed for controlled cell-, site-, and CU-domain-level incident injection and later agent investigation.


<a id="cell-05"></a>
##### Cell 05 — Freeze Incident-Family Definitions

Each fault declares its target component, topology scope, positive evidence, exclusion evidence, nearest competing hypotheses, expected diagnosis and metrics that will actually be modified. This is the formal **incident-admission contract**.


In [5]:
if not globals().get("M05_03_TOPOLOGY_PASS", False):
    raise RuntimeError("Cell 05 requires Cell 04.")

DECLARED_M05_00_FAULT_FAMILIES = {
    "ADMISSION_RESOURCE_PRESSURE","AMF_FACING_BOUNDARY","BEARER_CONTEXT_UNAVAILABLE",
    "CU_CP_PROCESSING_PRESSURE","CU_RESTART_SOFTWARE_EVENT","CU_UP_RESOURCE_PRESSURE",
    "DU_PROCESSING_PRESSURE","FALLBACK_ABNORMALITY","FIVE_QI_SPECIFIC","INTERNAL_INTERFACE",
    "N2_CONGESTION","N2_PACKET_LOSS_LATENCY","N2_PEER_CONFIGURATION","PAGING_MT_ACCESS",
    "POOR_COVERAGE","POOR_RADIO_QUALITY","PRACH_CONFIGURATION","QOS_CONFIGURATION",
    "RACH_CONTENTION","RACH_RESUME_ACCESS","RADIO_DU_ALARM","RADIO_INTERFERENCE",
    "RADIO_RESOURCE_CONGESTION","RADIO_RESUME_DEGRADATION","REESTABLISHMENT_ABNORMALITY",
    "RESUME_CONFIGURATION","RRC_CONFIGURATION","SCTP_INSTABILITY","SNSSAI_SPECIFIC",
    "SOFTWARE_CONFIGURATION_EVENT","SOFTWARE_EVENT","UE_CONTEXT_UNAVAILABLE",
    "UL_INTERFERENCE","UPSTREAM_RACH","UPSTREAM_RRC","UPSTREAM_RRC_NG",
    "UPSTREAM_RRC_RESUME",
}

def spec(component, scope, positive_metrics, exclusion_metrics, competitors,
         diagnosis, *, event_expected=False, target_5qi=None, incident_present=True):
    return {
        "incident_present": incident_present,
        "target_component": component,
        "scope_class": scope,
        "positive_metrics": positive_metrics,
        "direct_change_metrics": [m for m in positive_metrics if not m.startswith("event.")],
        "exclusion_metrics": exclusion_metrics,
        "competing_hypotheses": competitors,
        "expected_diagnosis": diagnosis,
        "event_expected": event_expected,
        "target_5qi": target_5qi,
    }

INCIDENT_FAMILIES = {
    "HEALTHY_CONTROL": spec(
        "HEALTHY_REFERENCE","FULL_NETWORK",[],[],
        ["RADIO_INTERFERENCE","N2_PACKET_LOSS_LATENCY"],
        "No injected incident; evidence is consistent with the healthy control.",
        incident_present=False,
    ),
    "RADIO_INTERFERENCE": spec(
        "RRC_AND_DRB_RADIO_PATH","CELL",
        ["radio.sinr_db","radio.dl_bler_pct","RRC.ConnEstabSucc.Cause","DRB.EstabSucc.5QI"],
        ["radio.rsrp_dbm","resource.dl_prb_util_pct","resource.ul_prb_util_pct"],
        ["POOR_COVERAGE","RADIO_RESOURCE_CONGESTION","DU_PROCESSING_PRESSURE"],
        "Cell-local radio interference / poor SINR condition.",
    ),
    "RADIO_RESOURCE_CONGESTION": spec(
        "RRC_AND_DRB_RESOURCE_PATH","SITE",
        ["resource.dl_prb_util_pct","resource.ul_prb_util_pct","resource.scheduler_pressure_pct",
         "load.connected_ues","DRB.EstabSucc.5QI"],
        ["radio.rsrp_dbm","radio.sinr_db","processing.du_cpu_pct"],
        ["RADIO_INTERFERENCE","DU_PROCESSING_PRESSURE","ADMISSION_RESOURCE_PRESSURE"],
        "Site-level radio resource congestion.",
    ),
    "N2_PACKET_LOSS_LATENCY": spec(
        "NG_SIGNALLING","CU_DOMAIN",
        ["transport.n2_packet_loss_pct","transport.n2_latency_ms","sctp.retransmissions",
         "UECNTX.ConnEstabSucc.Cause"],
        ["transport.n2_util_pct","processing.cu_cp_cpu_pct","radio.sinr_db"],
        ["N2_CONGESTION","CU_CP_PROCESSING_PRESSURE","AMF_FACING_BOUNDARY"],
        "N2 packet-loss / latency impairment affecting NG signalling.",
    ),
    "CU_CP_PROCESSING_PRESSURE": spec(
        "NG_SIGNALLING","CU_DOMAIN",
        ["processing.cu_cp_cpu_pct","processing.cu_cp_control_queue_depth",
         "processing.cu_cp_control_delay_ms","UECNTX.ConnEstabSucc.Cause"],
        ["transport.n2_packet_loss_pct","transport.n2_latency_ms","radio.sinr_db"],
        ["N2_PACKET_LOSS_LATENCY","N2_CONGESTION","AMF_FACING_BOUNDARY"],
        "Shared CU-CP processing pressure affecting NG signalling.",
    ),
    "QOS_CONFIGURATION": spec(
        "DRB_ESTABLISHMENT","CELL_5QI",
        ["DRB.InitialEstabSucc.5QI","DRB.EstabSucc.5QI","config.qos_profile_state",
         "event.config_change"],
        ["radio.sinr_db","resource.dl_prb_util_pct","RRC.ConnEstabSucc.Cause"],
        ["FIVE_QI_SPECIFIC","RADIO_RESOURCE_CONGESTION","POOR_RADIO_QUALITY"],
        "Cell-local 5QI-specific QoS configuration issue.",
        event_expected=True,target_5qi="1",
    ),
    "RRC_CONFIGURATION": spec(
        "RRC_ESTABLISHMENT","CELL",
        ["RRC.ConnEstabSucc.Cause","config.rrc_profile_state","event.config_change"],
        ["radio.sinr_db","resource.dl_prb_util_pct","UECNTX.ConnEstabSucc.Cause"],
        ["RADIO_INTERFERENCE","RADIO_RESOURCE_CONGESTION","UPSTREAM_RACH"],
        "Cell-local RRC configuration issue.",
        event_expected=True,
    ),
    "AMF_FACING_BOUNDARY": spec(
        "NG_SIGNALLING","CU_DOMAIN_BOUNDARY",
        ["boundary.amf_reachable","boundary.amf_peer_state","UECNTX.ConnEstabSucc.Cause",
         "event.interface_alarm_state"],
        ["transport.n2_packet_loss_pct","processing.cu_cp_cpu_pct","radio.sinr_db"],
        ["N2_PACKET_LOSS_LATENCY","CU_CP_PROCESSING_PRESSURE","N2_PEER_CONFIGURATION"],
        "AMF-facing boundary / peer reachability condition as observed from the RAN; "
        "internal 5GC root cause not proven.",
        event_expected=True,
    ),
}

non_control = {k:v for k,v in INCIDENT_FAMILIES.items() if k != "HEALTHY_CONTROL"}
unknown_faults = sorted(set(non_control) - DECLARED_M05_00_FAULT_FAMILIES)

metric_requirements = set()
for s in non_control.values():
    metric_requirements.update(m for m in s["direct_change_metrics"] if not m.startswith("event."))
    metric_requirements.update(s["exclusion_metrics"])
missing_metrics = sorted(metric_requirements - observed_metrics)

design_failures = []
for family, s in non_control.items():
    if len(s["direct_change_metrics"]) < 2: design_failures.append(f"{family}: direct evidence <2")
    if len(s["exclusion_metrics"]) < 2: design_failures.append(f"{family}: exclusion evidence <2")
    if len(s["competing_hypotheses"]) < 2: design_failures.append(f"{family}: competitors <2")

print("=" * 108)
print("MODULE 5 — M05_03 CELL 05 — INCIDENT DESIGN CONTRACT")
print("=" * 108)
print("Formal case families                 :", len(INCIDENT_FAMILIES))
print("Fault families                       :", len(non_control))
print("Healthy controls                     : 1")
print("Unknown M05_00 fault families        :", unknown_faults)
print("Missing required telemetry metrics   :", missing_metrics)
print("Structural design failures           :", design_failures)
print("-" * 108)
for family, s in INCIDENT_FAMILIES.items():
    print(f"{family:<32} scope={s['scope_class']:<18} "
          f"direct={len(s['direct_change_metrics']):>2} "
          f"exclude={len(s['exclusion_metrics']):>2} "
          f"competitors={len(s['competing_hypotheses']):>2}")

if unknown_faults or missing_metrics or design_failures:
    raise RuntimeError("M05_03 incident family design is not benchmark-ready.")

M05_03_INCIDENT_DESIGN_PASS = True
print("\nM05_03_INCIDENT_DESIGN_PASS         :", M05_03_INCIDENT_DESIGN_PASS)


MODULE 5 — M05_03 CELL 05 — INCIDENT DESIGN CONTRACT
Formal case families                 : 8
Fault families                       : 7
Healthy controls                     : 1
Unknown M05_00 fault families        : []
Missing required telemetry metrics   : []
Structural design failures           : []
------------------------------------------------------------------------------------------------------------
HEALTHY_CONTROL                  scope=FULL_NETWORK       direct= 0 exclude= 0 competitors= 2
RADIO_INTERFERENCE               scope=CELL               direct= 4 exclude= 3 competitors= 3
RADIO_RESOURCE_CONGESTION        scope=SITE               direct= 5 exclude= 3 competitors= 3
N2_PACKET_LOSS_LATENCY           scope=CU_DOMAIN          direct= 4 exclude= 3 competitors= 3
CU_CP_PROCESSING_PRESSURE        scope=CU_DOMAIN          direct= 4 exclude= 3 competitors= 3
QOS_CONFIGURATION                scope=CELL_5QI           direct= 3 exclude= 3 competitors= 3
RRC_CONFIGURATION        

###### Observation

The incident design contract passed all structural checks, defining 7 controlled fault families plus 1 healthy control across cell, site, CU-domain and boundary scopes. Each fault family includes explicit direct evidence, exclusion evidence and plausible competing hypotheses, with all required telemetry supported by the existing M05_00/M05_01 observability model.


<a id="section-3-incident-schedule"></a>
# Section 3 — Incident Schedule and Healthy Copies


<a id="cell-06"></a>
##### Cell 06 — Deterministic 32-Case Schedule and Split

Creates opaque scenario IDs, non-overlapping 4-hour windows, deterministic target scopes, severity profiles and DEVELOPMENT/EVAL assignments. The scenario ID carries **no semantic clue** about the fault.


In [6]:
if not globals().get("M05_03_INCIDENT_DESIGN_PASS", False):
    raise RuntimeError("Cell 06 requires Cell 05.")

BASE_START = pd.Timestamp("2026-06-02T00:00:00Z")
WINDOW_SPACING_HOURS = 66
SEVERITY_MAX_BY_EPISODE = {1:0.65, 2:0.80, 3:0.95, 4:0.75}
INCIDENT_SHAPE = [0.40,0.70,1.00,1.00,1.00,1.00,0.70,0.40]
sites = sorted(CELL_MAP_DF["site_id"].unique().tolist())

def domain_record(cu_domain_id):
    return DOMAIN_MAP_DF.loc[
        DOMAIN_MAP_DF["cu_domain_id"] == cu_domain_id
    ].iloc[0].to_dict()

private_cases, timeline_rows, target_cell_rows = [], [], []
global_index = 0

for episode in range(1,5):
    for family_index, family in enumerate(CASE_FAMILIES):
        scenario_id = f"M05I{global_index+1:04d}"
        window_start = BASE_START + pd.Timedelta(hours=WINDOW_SPACING_HOURS*global_index)
        incident_start = window_start + pd.Timedelta(hours=1)
        incident_end = incident_start + pd.Timedelta(hours=2)
        window_end = window_start + pd.Timedelta(hours=4)
        split = "DEVELOPMENT" if episode <= 3 else "EVAL"
        max_severity = 0.0 if family == "HEALTHY_CONTROL" else SEVERITY_MAX_BY_EPISODE[episode]

        site_pos = (family_index*2 + episode*3) % len(sites)
        target_site = sites[site_pos]
        site_df = CELL_MAP_DF[CELL_MAP_DF["site_id"] == target_site].sort_values("sector_rank")
        sector = ((family_index + episode) % 3) + 1
        target_row = site_df[site_df["sector_rank"] == sector].iloc[0]
        target_domain = target_row["cu_domain_id"]
        domain = domain_record(target_domain)

        if family in {"RADIO_INTERFERENCE","QOS_CONFIGURATION","RRC_CONFIGURATION"}:
            target_rows = pd.DataFrame([target_row])
        elif family == "RADIO_RESOURCE_CONGESTION":
            target_rows = site_df
        elif family == "HEALTHY_CONTROL":
            target_rows = site_df.iloc[0:0]
        else:
            target_rows = CELL_MAP_DF[
                CELL_MAP_DF["cu_domain_id"] == target_domain
            ].sort_values(["site_id","sector_rank"])

        distractor_site = sites[(site_pos + 5) % len(sites)]
        distractor_df = CELL_MAP_DF[
            CELL_MAP_DF["site_id"] == distractor_site
        ].sort_values("sector_rank")
        distractor_domain = distractor_df.iloc[0]["cu_domain_id"]
        distractor_domain_rec = domain_record(distractor_domain)
        distractor_metric = [
            "processing.du_cpu_pct","radio.dl_bler_pct","transport.n2_util_pct"
        ][global_index % 3]

        private_cases.append({
            "scenario_id":scenario_id,"family_internal":family,
            "incident_present":INCIDENT_FAMILIES[family]["incident_present"],
            "episode":episode,"benchmark_split":split,
            "window_start_utc":window_start,"incident_start_utc":incident_start,
            "incident_end_utc":incident_end,"window_end_utc":window_end,
            "max_severity":max_severity,
            "target_site_id":None if family=="HEALTHY_CONTROL" else target_site,
            "target_sector_rank":None if family=="HEALTHY_CONTROL" else int(sector),
            "target_cu_domain_id":None if family=="HEALTHY_CONTROL" else target_domain,
            "target_cu_cp_id":None if family=="HEALTHY_CONTROL" else domain["cu_cp_id"],
            "target_n2_path_id":None if family=="HEALTHY_CONTROL" else domain["n2_path_id"],
            "target_amf_peer_id":None if family=="HEALTHY_CONTROL" else domain["amf_peer_id"],
            "target_5qi":INCIDENT_FAMILIES[family]["target_5qi"],
            "distractor_metric":None if family=="HEALTHY_CONTROL" else distractor_metric,
            "distractor_site_id":None if family=="HEALTHY_CONTROL" else distractor_site,
            "distractor_cu_domain_id":None if family=="HEALTHY_CONTROL" else distractor_domain,
            "distractor_n2_path_id":None if family=="HEALTHY_CONTROL" else distractor_domain_rec["n2_path_id"],
        })

        for tr in target_rows.itertuples(index=False):
            target_cell_rows.append({
                "scenario_id":scenario_id,
                "nr_cell_cu_id":tr.nr_cell_cu_id,
                "nr_cell_du_id":tr.nr_cell_du_id,
            })

        for i in range(16):
            ts = window_start + pd.Timedelta(minutes=15*i)
            if i < 4:
                phase, sev = "PRE", 0.0
            elif i < 12:
                phase, sev = "INCIDENT", INCIDENT_SHAPE[i-4]*max_severity
            else:
                phase, sev = "RECOVERY", 0.0
            timeline_rows.append({
                "scenario_id":scenario_id,"interval_start_utc":ts,
                "phase":phase,"severity":float(sev),
            })
        global_index += 1

PRIVATE_CASES_DF = pd.DataFrame(private_cases)
TIMELINE_DF = pd.DataFrame(timeline_rows)
TARGET_CELLS_DF = pd.DataFrame(target_cell_rows)

windows = PRIVATE_CASES_DF[
    ["scenario_id","window_start_utc","window_end_utc"]
].sort_values("window_start_utc").reset_index(drop=True)
overlaps = sum(
    windows.loc[i,"window_start_utc"] < windows.loc[i-1,"window_end_utc"]
    for i in range(1,len(windows))
)
split_counts = PRIVATE_CASES_DF.groupby(
    ["family_internal","benchmark_split"]
).size().unstack(fill_value=0)

telemetry_last = pd.Timestamp(runtime_summary.loc[0,"last_interval"])
checks = {
    "scenario_count_32":len(PRIVATE_CASES_DF)==32,
    "timeline_rows_512":len(TIMELINE_DF)==512,
    "opaque_ids_unique":PRIVATE_CASES_DF["scenario_id"].nunique()==32,
    "no_window_overlap":overlaps==0,
    "all_windows_inside_baseline":
        PRIVATE_CASES_DF["window_end_utc"].max() <= telemetry_last + pd.Timedelta(minutes=15),
    "three_development_per_family":bool((split_counts["DEVELOPMENT"]==3).all()),
    "one_eval_per_family":bool((split_counts["EVAL"]==1).all()),
    "healthy_zero_severity":bool((
        PRIVATE_CASES_DF.loc[
            PRIVATE_CASES_DF["family_internal"]=="HEALTHY_CONTROL","max_severity"
        ]==0
    ).all()),
}

print("=" * 108)
print("MODULE 5 — M05_03 CELL 06 — DETERMINISTIC EPISODE SCHEDULE")
print("=" * 108)
for name, passed in checks.items(): print(f"{'PASS' if passed else 'FAIL':<7} {name}")
print("-" * 108)
print("Benchmark cases                     :",len(PRIVATE_CASES_DF))
print("Timeline rows                       :",len(TIMELINE_DF))
print("DEVELOPMENT / EVAL                  :",
      int((PRIVATE_CASES_DF["benchmark_split"]=="DEVELOPMENT").sum()),"/",
      int((PRIVATE_CASES_DF["benchmark_split"]=="EVAL").sum()))
print("First case start                    :",PRIVATE_CASES_DF["window_start_utc"].min())
print("Last case end                       :",PRIVATE_CASES_DF["window_end_utc"].max())

failed=[n for n,p in checks.items() if not p]
if failed: raise RuntimeError("M05_03 episode schedule failed: "+", ".join(failed))

M05_03_EPISODE_SCHEDULE_PASS=True
print("\nM05_03_EPISODE_SCHEDULE_PASS        :",M05_03_EPISODE_SCHEDULE_PASS)


MODULE 5 — M05_03 CELL 06 — DETERMINISTIC EPISODE SCHEDULE
PASS    scenario_count_32
PASS    timeline_rows_512
PASS    opaque_ids_unique
PASS    no_window_overlap
PASS    all_windows_inside_baseline
PASS    three_development_per_family
PASS    one_eval_per_family
PASS    healthy_zero_severity
------------------------------------------------------------------------------------------------------------
Benchmark cases                     : 32
Timeline rows                       : 512
DEVELOPMENT / EVAL                  : 24 / 8
First case start                    : 2026-06-02 00:00:00+00:00
Last case end                       : 2026-08-26 10:00:00+00:00

M05_03_EPISODE_SCHEDULE_PASS        : True


###### Observation

The deterministic episode schedule passed all checks, creating 32 unique, non-overlapping benchmark cases across 512 timeline intervals. The split is fixed at 24 DEVELOPMENT and 8 held-out EVAL cases, with one EVAL case per family, all fully contained within the healthy baseline period and with zero severity correctly preserved for healthy controls.


<a id="cell-07"></a>
##### Cell 07 — Copy Healthy Case Windows into the M05_03 Runtime

The canonical 92-day Parquet dataset remains untouched. Only the 32 selected windows are copied into a temporary DuckDB table, with original typed values retained internally for later audit.


In [7]:
if not globals().get("M05_03_EPISODE_SCHEDULE_PASS", False):
    raise RuntimeError("Cell 07 requires Cell 06.")

con.register("timeline_input",TIMELINE_DF)
con.register("private_cases_input",PRIVATE_CASES_DF)
con.register("target_cells_input",TARGET_CELLS_DF)

con.execute("CREATE OR REPLACE TABLE m05_03_private_cases AS SELECT * FROM private_cases_input")
con.execute("CREATE OR REPLACE TABLE m05_03_target_cells AS SELECT * FROM target_cells_input")
con.execute("CREATE OR REPLACE TABLE m05_03_timeline AS SELECT * FROM timeline_input")

con.execute("""
CREATE OR REPLACE TABLE m05_03_working_telemetry AS
SELECT
    t.scenario_id,p.family_internal,t.phase,t.severity,
    h.*,
    h.value_int AS original_value_int,
    h.value_float AS original_value_float,
    h.value_bool AS original_value_bool,
    h.value_text AS original_value_text
FROM healthy_telemetry AS h
JOIN m05_03_timeline AS t
  ON h.interval_start_utc=t.interval_start_utc
JOIN m05_03_private_cases AS p USING (scenario_id)
""")

base_diag=con.execute("""
WITH x AS (
 SELECT scenario_id,COUNT(*) AS scenario_rows
 FROM m05_03_working_telemetry GROUP BY scenario_id
)
SELECT
 (SELECT COUNT(*) FROM m05_03_working_telemetry) AS rows,
 COUNT(*) AS scenarios,
 MIN(scenario_rows) AS min_rows_per_scenario,
 MAX(scenario_rows) AS max_rows_per_scenario
FROM x
""").df()

EXPECTED_CASE_ROWS=32*16*ROWS_PER_INTERVAL
phase_diag=con.execute("""
SELECT phase,COUNT(*) AS rows FROM m05_03_working_telemetry
GROUP BY phase ORDER BY phase
""").df()

checks={
 "expected_total_rows":int(base_diag.loc[0,"rows"])==EXPECTED_CASE_ROWS,
 "scenarios_32":int(base_diag.loc[0,"scenarios"])==32,
 "equal_rows_per_scenario":
     int(base_diag.loc[0,"min_rows_per_scenario"])==int(base_diag.loc[0,"max_rows_per_scenario"]),
}

print("="*108)
print("MODULE 5 — M05_03 CELL 07 — HEALTHY CASE-WINDOW COPY")
print("="*108)
print(base_diag.to_string(index=False))
print("\nPhase inventory\n"+"-"*108)
print(phase_diag.to_string(index=False))
print("-"*108)
print("Rows per healthy interval           :",ROWS_PER_INTERVAL)
print("Expected copied rows                :",f"{EXPECTED_CASE_ROWS:,}")
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 healthy-copy qualification failed: "+", ".join(failed))

M05_03_BASE_SLICE_PASS=True
print("\nM05_03_BASE_SLICE_PASS              :",M05_03_BASE_SLICE_PASS)


MODULE 5 — M05_03 CELL 07 — HEALTHY CASE-WINDOW COPY
   rows  scenarios  min_rows_per_scenario  max_rows_per_scenario
1091584         32                  34112                  34112

Phase inventory
------------------------------------------------------------------------------------------------------------
   phase   rows
INCIDENT 545792
     PRE 272896
RECOVERY 272896
------------------------------------------------------------------------------------------------------------
Rows per healthy interval           : 2132
Expected copied rows                : 1,091,584
PASS    expected_total_rows
PASS    scenarios_32
PASS    equal_rows_per_scenario

M05_03_BASE_SLICE_PASS              : True


###### Observation

The 32 benchmark case windows were successfully copied from the canonical healthy baseline, producing 1,091,584 observations with an identical 34,112 rows per scenario. The PRE, INCIDENT and RECOVERY phases reconcile exactly with the intended 1-hour / 2-hour / 1-hour episode structure, confirming that all scenarios begin from an unmodified healthy reference before controlled incident injection.


<a id="section-4-controlled-overlays"></a>
# Section 4 — Controlled Incident Overlays


<a id="cell-08"></a>
##### Cell 08 — Apply Numeric Incident Overlays

Numeric overlays modify only copied M05_03 rows in the active incident phase. Standardized success counters are scaled in coordinated families so attempt/success and Added-DRB hierarchy remain valid.

**Formal KPI values are never directly modified.**


In [8]:
if not globals().get("M05_03_BASE_SLICE_PASS",False):
    raise RuntimeError("Cell 08 requires Cell 07.")

CELL_CU_TARGET="""EXISTS(
 SELECT 1 FROM m05_03_target_cells tc
 WHERE tc.scenario_id=w.scenario_id AND tc.nr_cell_cu_id=w.entity_id
)"""
CELL_DU_TARGET="""EXISTS(
 SELECT 1 FROM m05_03_target_cells tc
 WHERE tc.scenario_id=w.scenario_id AND tc.nr_cell_du_id=w.entity_id
)"""
SITE_TARGET="""EXISTS(
 SELECT 1 FROM m05_03_private_cases pc
 WHERE pc.scenario_id=w.scenario_id AND pc.target_site_id=w.site_id
)"""
DOMAIN_TARGET="""EXISTS(
 SELECT 1 FROM m05_03_private_cases pc
 WHERE pc.scenario_id=w.scenario_id AND pc.target_cu_domain_id=w.cu_domain_id
)"""

def update_float(family,metric,scope,expr):
    con.execute(f"""
    UPDATE m05_03_working_telemetry AS w
    SET value_float={expr}
    WHERE phase='INCIDENT' AND family_internal='{family}'
      AND metric_name='{metric}' AND ({scope})
    """)

def update_int(family,metric,scope,expr,extra="TRUE"):
    con.execute(f"""
    UPDATE m05_03_working_telemetry AS w
    SET value_int=CAST(GREATEST(0,ROUND({expr})) AS BIGINT)
    WHERE phase='INCIDENT' AND family_internal='{family}'
      AND metric_name='{metric}' AND ({scope}) AND ({extra})
    """)

def scale_success(family,metrics,scope,reduction,extra="TRUE"):
    for metric in metrics:
        update_int(
            family,metric,scope,
            f"w.original_value_int*(1.0-{reduction}*w.severity)",
            extra,
        )

# RADIO INTERFERENCE — cell
update_float("RADIO_INTERFERENCE","radio.sinr_db",CELL_DU_TARGET,
             "w.original_value_float-9.0*w.severity")
update_float("RADIO_INTERFERENCE","radio.dl_bler_pct",CELL_DU_TARGET,
             "LEAST(100.0,w.original_value_float+12.0*w.severity)")
update_float("RADIO_INTERFERENCE","radio.ul_bler_pct",CELL_DU_TARGET,
             "LEAST(100.0,w.original_value_float+8.0*w.severity)")
scale_success("RADIO_INTERFERENCE",["RRC.ConnEstabSucc.Cause"],CELL_CU_TARGET,0.12)
scale_success("RADIO_INTERFERENCE",
              ["DRB.InitialEstabSucc.5QI","DRB.EstabSucc.5QI"],CELL_CU_TARGET,0.20)
scale_success("RADIO_INTERFERENCE",["DRB.ResumeSucc.5QI"],CELL_CU_TARGET,0.12)

# RADIO RESOURCE CONGESTION — site
for metric,inc in [
    ("resource.dl_prb_util_pct",35.0),("resource.ul_prb_util_pct",28.0),
    ("resource.scheduler_pressure_pct",40.0),
    ("resource.bearer_admission_pressure_pct",30.0),
]:
    update_float("RADIO_RESOURCE_CONGESTION",metric,SITE_TARGET,
                 f"LEAST(100.0,w.original_value_float+{inc}*w.severity)")
for metric,mult in [("load.connected_ues",0.55),("load.active_ues",0.65)]:
    update_int("RADIO_RESOURCE_CONGESTION",metric,SITE_TARGET,
               f"w.original_value_int*(1.0+{mult}*w.severity)")
scale_success("RADIO_RESOURCE_CONGESTION",["RRC.ConnEstabSucc.Cause"],SITE_TARGET,0.08)
scale_success("RADIO_RESOURCE_CONGESTION",
              ["DRB.InitialEstabSucc.5QI","DRB.EstabSucc.5QI"],SITE_TARGET,0.25)
scale_success("RADIO_RESOURCE_CONGESTION",["DRB.ResumeSucc.5QI"],SITE_TARGET,0.15)

# N2 PACKET LOSS / LATENCY — CU domain
update_float("N2_PACKET_LOSS_LATENCY","transport.n2_packet_loss_pct",DOMAIN_TARGET,
             "LEAST(100.0,w.original_value_float+6.0*w.severity)")
update_float("N2_PACKET_LOSS_LATENCY","transport.n2_latency_ms",DOMAIN_TARGET,
             "w.original_value_float+35.0*w.severity")
update_int("N2_PACKET_LOSS_LATENCY","sctp.retransmissions",DOMAIN_TARGET,
           "w.original_value_int+12.0*w.severity")
update_int("N2_PACKET_LOSS_LATENCY","sctp.heartbeat_failures",DOMAIN_TARGET,
           "w.original_value_int+3.0*w.severity")
scale_success("N2_PACKET_LOSS_LATENCY",["UECNTX.ConnEstabSucc.Cause"],DOMAIN_TARGET,0.25)

# CU-CP PROCESSING PRESSURE — CU domain
for metric,inc in [("processing.cu_cp_cpu_pct",35.0),("processing.cu_cp_memory_pct",25.0)]:
    update_float("CU_CP_PROCESSING_PRESSURE",metric,DOMAIN_TARGET,
                 f"LEAST(100.0,w.original_value_float+{inc}*w.severity)")
update_int("CU_CP_PROCESSING_PRESSURE","processing.cu_cp_control_queue_depth",DOMAIN_TARGET,
           "w.original_value_int*(1.0+3.0*w.severity)")
update_float("CU_CP_PROCESSING_PRESSURE","processing.cu_cp_control_delay_ms",DOMAIN_TARGET,
             "w.original_value_float*(1.0+3.0*w.severity)")
scale_success("CU_CP_PROCESSING_PRESSURE",["UECNTX.ConnEstabSucc.Cause"],DOMAIN_TARGET,0.22)
scale_success("CU_CP_PROCESSING_PRESSURE",["RRC.ConnEstabSucc.Cause"],DOMAIN_TARGET,0.04)

# QoS CONFIGURATION — cell / 5QI 1
qos_extra="CAST(w.dimension_5qi AS VARCHAR)='1'"
scale_success("QOS_CONFIGURATION",
              ["DRB.InitialEstabSucc.5QI","DRB.EstabSucc.5QI"],
              CELL_CU_TARGET,0.35,qos_extra)
scale_success("QOS_CONFIGURATION",["DRB.ResumeSucc.5QI"],
              CELL_CU_TARGET,0.20,qos_extra)

# RRC CONFIGURATION — cell
scale_success("RRC_CONFIGURATION",["RRC.ConnEstabSucc.Cause"],CELL_CU_TARGET,0.30)

# AMF-FACING BOUNDARY — CU domain
scale_success("AMF_FACING_BOUNDARY",["UECNTX.ConnEstabSucc.Cause"],DOMAIN_TARGET,0.30)

numeric_change_diag=con.execute("""
SELECT family_internal,phase,
 SUM(CASE WHEN COALESCE(
     ABS(COALESCE(value_float,CAST(value_int AS DOUBLE))-
         COALESCE(original_value_float,CAST(original_value_int AS DOUBLE))),0
 )>1e-12 THEN 1 ELSE 0 END) AS changed_numeric_rows
FROM m05_03_working_telemetry
GROUP BY family_internal,phase ORDER BY family_internal,phase
""").df()

outside=int(numeric_change_diag.loc[numeric_change_diag["phase"]!="INCIDENT",
                                     "changed_numeric_rows"].sum())
healthy=int(numeric_change_diag.loc[
    numeric_change_diag["family_internal"]=="HEALTHY_CONTROL","changed_numeric_rows"
].sum())
fault_active=numeric_change_diag[
    (numeric_change_diag["phase"]=="INCIDENT")&
    (numeric_change_diag["family_internal"]!="HEALTHY_CONTROL")
]
all_faults=(fault_active["family_internal"].nunique()==7 and
            bool((fault_active["changed_numeric_rows"]>0).all()))

print("="*108)
print("MODULE 5 — M05_03 CELL 08 — NUMERIC INCIDENT OVERLAYS")
print("="*108)
print(numeric_change_diag.to_string(index=False))
print("-"*108)
print("Numeric changes outside INCIDENT    :",outside)
print("Healthy-control numeric changes     :",healthy)
print("All 7 fault families changed        :",all_faults)

if outside or healthy or not all_faults:
    raise RuntimeError("Numeric overlay boundary validation failed.")

M05_03_NUMERIC_OVERLAY_PASS=True
print("\nM05_03_NUMERIC_OVERLAY_PASS         :",M05_03_NUMERIC_OVERLAY_PASS)


MODULE 5 — M05_03 CELL 08 — NUMERIC INCIDENT OVERLAYS
          family_internal    phase  changed_numeric_rows
      AMF_FACING_BOUNDARY INCIDENT                1440.0
      AMF_FACING_BOUNDARY      PRE                   0.0
      AMF_FACING_BOUNDARY RECOVERY                   0.0
CU_CP_PROCESSING_PRESSURE INCIDENT                3008.0
CU_CP_PROCESSING_PRESSURE      PRE                   0.0
CU_CP_PROCESSING_PRESSURE RECOVERY                   0.0
          HEALTHY_CONTROL INCIDENT                   0.0
          HEALTHY_CONTROL      PRE                   0.0
          HEALTHY_CONTROL RECOVERY                   0.0
   N2_PACKET_LOSS_LATENCY INCIDENT                1568.0
   N2_PACKET_LOSS_LATENCY      PRE                   0.0
   N2_PACKET_LOSS_LATENCY RECOVERY                   0.0
        QOS_CONFIGURATION INCIDENT                  96.0
        QOS_CONFIGURATION      PRE                   0.0
        QOS_CONFIGURATION RECOVERY                   0.0
       RADIO_INTERFERENCE INCIDENT

###### Observation

Numeric incident overlays were successfully applied to all 7 fault families only during their INCIDENT periods. PRE, RECOVERY and HEALTHY_CONTROL telemetry remained unchanged, confirming that the benchmark preserves clean healthy reference states while introducing controlled and family-specific fault signatures.


<a id="cell-09"></a>
##### Cell 09 — Configuration / Boundary State, Events and Non-Causal Distractors

Adds QoS/RRC configuration states, AMF-facing state evidence, controlled event records and one mild **unrelated operational distractor** per non-control case. Distractors never modify standardized PM counters.


In [9]:
if not globals().get("M05_03_NUMERIC_OVERLAY_PASS",False):
    raise RuntimeError("Cell 09 requires Cell 08.")

con.execute(f"""
UPDATE m05_03_working_telemetry w SET value_text='INCIDENT_PROFILE'
WHERE phase='INCIDENT' AND family_internal='QOS_CONFIGURATION'
  AND metric_name='config.qos_profile_state' AND ({CELL_CU_TARGET})
""")
con.execute(f"""
UPDATE m05_03_working_telemetry w SET value_text='INCIDENT_PROFILE'
WHERE phase='INCIDENT' AND family_internal='RRC_CONFIGURATION'
  AND metric_name='config.rrc_profile_state' AND ({CELL_CU_TARGET})
""")
con.execute(f"""
UPDATE m05_03_working_telemetry w
SET value_bool=CASE WHEN severity>=0.50 THEN FALSE ELSE original_value_bool END
WHERE phase='INCIDENT' AND family_internal='AMF_FACING_BOUNDARY'
  AND metric_name='boundary.amf_reachable' AND ({DOMAIN_TARGET})
""")
con.execute(f"""
UPDATE m05_03_working_telemetry w SET value_text='UNSTABLE'
WHERE phase='INCIDENT' AND family_internal='AMF_FACING_BOUNDARY'
  AND metric_name='boundary.amf_peer_state' AND ({DOMAIN_TARGET})
""")

event_rows=[]
for row in PRIVATE_CASES_DF.itertuples(index=False):
    if row.family_internal in {"QOS_CONFIGURATION","RRC_CONFIGURATION"}:
        target=TARGET_CELLS_DF.loc[
            TARGET_CELLS_DF["scenario_id"]==row.scenario_id,"nr_cell_cu_id"
        ].iloc[0]
        event_rows.append({
            "scenario_id":row.scenario_id,"event_time_utc":row.incident_start_utc,
            "event_metric_name":"event.config_change","entity_id":target,
            "site_id":row.target_site_id,"cu_domain_id":row.target_cu_domain_id,
            "state":"ACTIVE",
            "message":"Configuration change detected on the managed object.",
        })
    elif row.family_internal=="AMF_FACING_BOUNDARY":
        event_rows.append({
            "scenario_id":row.scenario_id,"event_time_utc":row.incident_start_utc,
            "event_metric_name":"event.interface_alarm_state","entity_id":row.target_amf_peer_id,
            "site_id":None,"cu_domain_id":row.target_cu_domain_id,"state":"ACTIVE",
            "message":"Intermittent peer/interface reachability alarm observed.",
        })
EVENTS_DF=pd.DataFrame(event_rows)

# Mild distractors outside causal target.
for case in PRIVATE_CASES_DF.itertuples(index=False):
    if case.family_internal=="HEALTHY_CONTROL": continue
    metric=case.distractor_metric
    if metric=="processing.du_cpu_pct":
        con.execute(f"""
        UPDATE m05_03_working_telemetry w
        SET value_float=LEAST(100.0,original_value_float+8.0*severity)
        WHERE scenario_id='{case.scenario_id}' AND phase='INCIDENT'
          AND metric_name='processing.du_cpu_pct' AND site_id='{case.distractor_site_id}'
        """)
    elif metric=="radio.dl_bler_pct":
        du=CELL_MAP_DF.loc[
            CELL_MAP_DF["site_id"]==case.distractor_site_id
        ].sort_values("sector_rank").iloc[0]["nr_cell_du_id"]
        con.execute(f"""
        UPDATE m05_03_working_telemetry w
        SET value_float=LEAST(100.0,original_value_float+1.5*severity)
        WHERE scenario_id='{case.scenario_id}' AND phase='INCIDENT'
          AND metric_name='radio.dl_bler_pct' AND entity_id='{du}'
        """)
    else:
        con.execute(f"""
        UPDATE m05_03_working_telemetry w
        SET value_float=LEAST(100.0,original_value_float+8.0*severity)
        WHERE scenario_id='{case.scenario_id}' AND phase='INCIDENT'
          AND metric_name='transport.n2_util_pct'
          AND entity_id='{case.distractor_n2_path_id}'
        """)

state_diag=con.execute("""
SELECT family_internal,phase,
 SUM(CASE WHEN value_text IS DISTINCT FROM original_value_text
               OR value_bool IS DISTINCT FROM original_value_bool
          THEN 1 ELSE 0 END) AS changed_state_rows
FROM m05_03_working_telemetry
GROUP BY family_internal,phase ORDER BY family_internal,phase
""").df()
outside=int(state_diag.loc[state_diag["phase"]!="INCIDENT","changed_state_rows"].sum())
expected=set(PRIVATE_CASES_DF.loc[
    PRIVATE_CASES_DF["family_internal"].isin(
        {"QOS_CONFIGURATION","RRC_CONFIGURATION","AMF_FACING_BOUNDARY"}
    ),"scenario_id"])
observed=set(EVENTS_DF["scenario_id"])

checks={
 "no_state_changes_outside_incident":outside==0,
 "events_only_for_expected_cases":observed==expected,
 "twelve_controlled_events":len(EVENTS_DF)==12,
 "healthy_control_has_no_events":
     not bool(set(PRIVATE_CASES_DF.loc[
         PRIVATE_CASES_DF["family_internal"]=="HEALTHY_CONTROL","scenario_id"
     ])&observed),
}

print("="*108)
print("MODULE 5 — M05_03 CELL 09 — CONTEXT / EVENTS / DISTRACTORS")
print("="*108)
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")
print("-"*108)
print("Controlled event rows               :",len(EVENTS_DF))
print("Cases with controlled events        :",len(observed))
print("State changes outside incident      :",outside)
print("Distractor policy                   : 1 mild operational distractor per non-control case")

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 context overlay validation failed: "+", ".join(failed))

M05_03_CONTEXT_OVERLAY_PASS=True
print("\nM05_03_CONTEXT_OVERLAY_PASS         :",M05_03_CONTEXT_OVERLAY_PASS)


MODULE 5 — M05_03 CELL 09 — CONTEXT / EVENTS / DISTRACTORS
PASS    no_state_changes_outside_incident
PASS    events_only_for_expected_cases
PASS    twelve_controlled_events
PASS    healthy_control_has_no_events
------------------------------------------------------------------------------------------------------------
Controlled event rows               : 12
Cases with controlled events        : 12
State changes outside incident      : 0
Distractor policy                   : 1 mild operational distractor per non-control case

M05_03_CONTEXT_OVERLAY_PASS         : True


###### Observation

Context, event and distractor overlays passed all validation checks. Controlled state changes remained confined to INCIDENT periods, exactly 12 expected cases generated one event each, healthy controls remained event-free, and every non-control case received one mild operational distractor to increase diagnostic realism without altering the true causal path.


<a id="section-5-sanitization-kpi"></a>
# Section 5 — Sanitization and Formal KPI Recalculation


<a id="cell-10"></a>
##### Cell 10 — Build Agent-Visible Evidence and Enforce Leakage Boundary

Creates sanitized telemetry/events. Internal family, severity, phase and original values are excluded, and text-bearing public fields are scanned for benchmark-answer vocabulary.


In [10]:
if not globals().get("M05_03_CONTEXT_OVERLAY_PASS", False):
    raise RuntimeError("Cell 10 requires Cell 09.")

con.execute("""
CREATE OR REPLACE TABLE m05_03_agent_telemetry AS
SELECT
    scenario_id,
    observation_id,
    environment,
    observation_type,
    evidence_origin,
    metric_name,
    is_standardized_metric,
    operational_category,
    entity_id,
    entity_namespace,
    entity_type,
    operational_scope,
    parent_entity_id,
    site_id,
    cu_domain_id,
    interval_start_utc,
    interval_end_utc,
    pm_interval_minutes,
    value_kind,
    value_int,
    value_float,
    value_bool,
    value_text,
    unit,
    dimension_cause,
    dimension_5qi,
    dimension_snssai,
    dimensions_json,
    quality,
    graph_node_id,
    investigation_stage,
    source_system,
    metadata_json
FROM m05_03_working_telemetry
""")

con.register("events_input", EVENTS_DF)
con.execute("""
CREATE OR REPLACE TABLE m05_03_agent_events AS
SELECT * FROM events_input
""")

FORBIDDEN_PUBLIC_TERMS = {
    "root_cause",
    "ground_truth",
    "fault_label",
    "expected_diagnosis",
    "correct_action",
    "benchmark_answer",
    "family_internal",
    "severity",
    "phase",
}

agent_cols = set(
    con.execute("DESCRIBE m05_03_agent_telemetry")
    .df()["column_name"]
    .astype(str)
)

event_cols = set(
    con.execute("DESCRIBE m05_03_agent_events")
    .df()["column_name"]
    .astype(str)
)

schema_hits = sorted(
    FORBIDDEN_PUBLIC_TERMS & (agent_cols | event_cols)
)

text_hits = int(con.execute("""
SELECT COUNT(*)
FROM m05_03_agent_telemetry
WHERE LOWER(COALESCE(value_text,'')) SIMILAR TO
      '%(root_cause|ground_truth|fault_label|expected_diagnosis|correct_action|benchmark_answer)%'
   OR LOWER(COALESCE(metadata_json,'')) SIMILAR TO
      '%(root_cause|ground_truth|fault_label|expected_diagnosis|correct_action|benchmark_answer)%'
   OR LOWER(COALESCE(dimensions_json,'')) SIMILAR TO
      '%(root_cause|ground_truth|fault_label|expected_diagnosis|correct_action|benchmark_answer)%'
""").fetchone()[0])

text_hits += int(con.execute("""
SELECT COUNT(*)
FROM m05_03_agent_events
WHERE LOWER(COALESCE(message,'')) SIMILAR TO
      '%(root_cause|ground_truth|fault_label|expected_diagnosis|correct_action|benchmark_answer)%'
""").fetchone()[0])

agent_rows = int(
    con.execute(
        "SELECT COUNT(*) FROM m05_03_agent_telemetry"
    ).fetchone()[0]
)

checks = {
    "agent_schema_has_no_hidden_fields": not schema_hits,
    "public_text_has_no_truth_vocabulary": text_hits == 0,
    "agent_row_count_preserved": agent_rows == EXPECTED_CASE_ROWS,
}

print("=" * 108)
print("MODULE 5 — M05_03 CELL 10 — AGENT-VISIBLE SANITIZATION / LEAKAGE GATE")
print("=" * 108)

for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")

print("-" * 108)
print("Agent-visible telemetry rows         :", f"{agent_rows:,}")
print("Agent-visible event rows             :", len(EVENTS_DF))
print("Forbidden schema hits                :", schema_hits)
print("Forbidden text hits                  :", text_hits)
print("Phase / severity visible to agent    : NO")
print("Root-cause labels visible to agent   : NO")

failed = [name for name, passed in checks.items() if not passed]

if failed:
    raise RuntimeError(
        "M05_03 truth-leakage gate failed: " + ", ".join(failed)
    )

M05_03_LEAKAGE_PASS = True

print(
    "\nM05_03_LEAKAGE_PASS                 :",
    M05_03_LEAKAGE_PASS
)

MODULE 5 — M05_03 CELL 10 — AGENT-VISIBLE SANITIZATION / LEAKAGE GATE
PASS    agent_schema_has_no_hidden_fields
PASS    public_text_has_no_truth_vocabulary
PASS    agent_row_count_preserved
------------------------------------------------------------------------------------------------------------
Agent-visible telemetry rows         : 1,091,584
Agent-visible event rows             : 12
Forbidden schema hits                : []
Forbidden text hits                  : 0
Phase / severity visible to agent    : NO
Root-cause labels visible to agent   : NO

M05_03_LEAKAGE_PASS                 : True


###### Observation

The agent-visible telemetry and event datasets passed the leakage gate. All 1,091,584 telemetry rows and 12 event records were preserved, while hidden benchmark fields such as phase, severity and root-cause labels were completely excluded from both schema and text content.


<a id="cell-11"></a>
##### Cell 11 — Recompute Formal Accessibility KPIs for Every Scenario

Reuses the **same deterministic M05_02 formula logic** on the sanitized scenario telemetry: control-plane aggregation, DRB hierarchy, Partial Accessibility, Total-RRC/RRC-Resume supporting ratios, Total Accessibility, and SubNetwork aggregation.

No KPI value is injected directly.


In [11]:
if not globals().get("M05_03_LEAKAGE_PASS",False):
    raise RuntimeError("Cell 11 requires Cell 10.")

con.execute("""
CREATE OR REPLACE TABLE m05_03_control AS
SELECT scenario_id,entity_id,ANY_VALUE(site_id) AS site_id,
       ANY_VALUE(cu_domain_id) AS cu_domain_id,interval_start_utc,
 SUM(CASE WHEN metric_name='RRC.ConnEstabAtt.Cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS rrc_conn_att_service,
 SUM(CASE WHEN metric_name='RRC.ConnEstabSucc.Cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS rrc_conn_succ_service,
 SUM(CASE WHEN metric_name='UECNTX.ConnEstabAtt.Cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS ng_att_service,
 SUM(CASE WHEN metric_name='UECNTX.ConnEstabSucc.Cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS ng_succ_service,
 SUM(CASE WHEN metric_name='RRC.ResumeAtt.Cause'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_att,
 SUM(CASE WHEN metric_name='RRC.ResumeSucc.Cause'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_succ,
 SUM(CASE WHEN metric_name='RRC.ResumeFallbackToSetupAtt.cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_fallback_att_service,
 SUM(CASE WHEN metric_name='RRC.ResumeSuccByFallback.cause' AND dimension_cause<>'mo-Signalling'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_fallback_succ_service,
 SUM(CASE WHEN metric_name='RRC.ResumeFallbackToSetupAtt.cause'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_fallback_att_all,
 SUM(CASE WHEN metric_name='RRC.ResumeSuccByFallback.cause'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS resume_fallback_succ_all,
 SUM(CASE WHEN metric_name='RRC.ReEstabFallbackToSetupAtt'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS reestab_fallback_att,
 SUM(CASE WHEN metric_name='RRC.ReEstabSuccWithoutUeContext'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS reestab_succ_without_ctx
FROM m05_03_agent_telemetry
WHERE metric_name IN (
 'RRC.ConnEstabAtt.Cause','RRC.ConnEstabSucc.Cause',
 'UECNTX.ConnEstabAtt.Cause','UECNTX.ConnEstabSucc.Cause',
 'RRC.ResumeAtt.Cause','RRC.ResumeSucc.Cause',
 'RRC.ResumeFallbackToSetupAtt.cause','RRC.ResumeSuccByFallback.cause',
 'RRC.ReEstabFallbackToSetupAtt','RRC.ReEstabSuccWithoutUeContext'
)
GROUP BY scenario_id,entity_id,interval_start_utc
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_drb AS
SELECT scenario_id,entity_id,ANY_VALUE(site_id) AS site_id,
       ANY_VALUE(cu_domain_id) AS cu_domain_id,interval_start_utc,
       CAST(dimension_5qi AS VARCHAR) AS five_qi,
 SUM(CASE WHEN metric_name='DRB.InitialEstabAtt.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS initial_att,
 SUM(CASE WHEN metric_name='DRB.InitialEstabSucc.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS initial_succ,
 SUM(CASE WHEN metric_name='DRB.EstabAtt.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS estab_att,
 SUM(CASE WHEN metric_name='DRB.EstabSucc.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS estab_succ,
 SUM(CASE WHEN metric_name='DRB.ResumeAtt.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS drb_resume_att,
 SUM(CASE WHEN metric_name='DRB.ResumeSucc.5QI'
          THEN COALESCE(CAST(value_int AS DOUBLE),value_float) ELSE 0 END) AS drb_resume_succ
FROM m05_03_agent_telemetry
WHERE metric_name IN (
 'DRB.InitialEstabAtt.5QI','DRB.InitialEstabSucc.5QI',
 'DRB.EstabAtt.5QI','DRB.EstabSucc.5QI',
 'DRB.ResumeAtt.5QI','DRB.ResumeSucc.5QI'
)
GROUP BY scenario_id,entity_id,interval_start_utc,dimension_5qi
""")
con.execute("ALTER TABLE m05_03_drb ADD COLUMN added_att DOUBLE")
con.execute("UPDATE m05_03_drb SET added_att=estab_att-initial_att")
con.execute("ALTER TABLE m05_03_drb ADD COLUMN added_succ DOUBLE")
con.execute("UPDATE m05_03_drb SET added_succ=estab_succ-initial_succ")

con.execute("""
CREATE OR REPLACE TABLE m05_03_control_ratios AS
SELECT *,
 (rrc_conn_succ_service+resume_fallback_succ_service+reestab_succ_without_ctx)/
 NULLIF(rrc_conn_att_service+resume_fallback_att_service+reestab_fallback_att,0)
 AS rrc_total_setup_sr,
 resume_succ/NULLIF(resume_att-resume_fallback_att_all,0) AS rrc_resume_sr
FROM m05_03_control
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_partial AS
SELECT d.scenario_id,d.entity_id,d.site_id,d.cu_domain_id,d.interval_start_utc,d.five_qi,
 100.0*(c.rrc_conn_succ_service/NULLIF(c.rrc_conn_att_service,0))
      *(c.ng_succ_service/NULLIF(c.ng_att_service,0))
      *(d.estab_succ/NULLIF(d.estab_att,0))
 AS partial_drb_accessibility_pct
FROM m05_03_drb d
JOIN m05_03_control c USING(scenario_id,entity_id,interval_start_utc)
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_total AS
SELECT d.scenario_id,d.entity_id,d.site_id,d.cu_domain_id,d.interval_start_utc,d.five_qi,
 d.initial_att,d.initial_succ,d.added_att,d.added_succ,d.drb_resume_att,d.drb_resume_succ,
 c.rrc_total_setup_sr,
 c.ng_succ_service/NULLIF(c.ng_att_service,0) AS ng_connection_sr,
 c.rrc_resume_sr,
 d.initial_att/NULLIF(
   c.rrc_total_setup_sr*(c.ng_succ_service/NULLIF(c.ng_att_service,0)),0
 ) AS initial_service_intent,
 d.drb_resume_att/NULLIF(c.rrc_resume_sr,0) AS resume_service_intent,
 d.initial_succ+d.added_succ+d.drb_resume_succ AS total_success_numerator,
 (
   d.initial_att/NULLIF(
     c.rrc_total_setup_sr*(c.ng_succ_service/NULLIF(c.ng_att_service,0)),0
   )
   +d.added_att
   +d.drb_resume_att/NULLIF(c.rrc_resume_sr,0)
 ) AS total_service_intent_denominator,
 100.0*(d.initial_succ+d.added_succ+d.drb_resume_succ)/
 NULLIF(
   d.initial_att/NULLIF(
     c.rrc_total_setup_sr*(c.ng_succ_service/NULLIF(c.ng_att_service,0)),0
   )
   +d.added_att
   +d.drb_resume_att/NULLIF(c.rrc_resume_sr,0),
   0
 ) AS total_drb_accessibility_pct
FROM m05_03_drb d
JOIN m05_03_control_ratios c USING(scenario_id,entity_id,interval_start_utc)
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_cell_kpis AS
SELECT p.scenario_id,p.entity_id,p.site_id,p.cu_domain_id,p.interval_start_utc,p.five_qi,
       p.partial_drb_accessibility_pct,t.total_drb_accessibility_pct
FROM m05_03_partial p
JOIN m05_03_total t USING(
 scenario_id,entity_id,site_id,cu_domain_id,interval_start_utc,five_qi
)
ORDER BY scenario_id,interval_start_utc,entity_id,five_qi
""")

con.execute("""
CREATE OR REPLACE TABLE m05_03_subnetwork_kpis AS
SELECT scenario_id,interval_start_utc,five_qi,
 AVG(partial_drb_accessibility_pct) AS partial_drb_accessibility_pct,
 AVG(total_drb_accessibility_pct) AS total_drb_accessibility_pct,
 COUNT(*) AS contributing_nr_cell_cu
FROM m05_03_cell_kpis
GROUP BY scenario_id,interval_start_utc,five_qi
ORDER BY scenario_id,interval_start_utc,five_qi
""")

diag=con.execute("""
SELECT COUNT(*) AS cell_kpi_rows,COUNT(DISTINCT scenario_id) AS scenarios,
 COUNT(DISTINCT entity_id) AS cells,COUNT(DISTINCT five_qi) AS five_qi_values,
 MIN(partial_drb_accessibility_pct) AS partial_min_pct,
 AVG(partial_drb_accessibility_pct) AS partial_mean_pct,
 MAX(partial_drb_accessibility_pct) AS partial_max_pct,
 MIN(total_drb_accessibility_pct) AS total_min_pct,
 AVG(total_drb_accessibility_pct) AS total_mean_pct,
 MAX(total_drb_accessibility_pct) AS total_max_pct
FROM m05_03_cell_kpis
""").df()

print("="*108)
print("MODULE 5 — M05_03 CELL 11 — FORMAL SCENARIO KPI DERIVATION")
print("="*108)
print(diag.round(6).to_string(index=False))
print("-"*108)
print("Formal KPI values directly injected : NO")
print("Formula source                      : M05_02 deterministic logic")

M05_03_SCENARIO_KPI_PASS=True
print("\nM05_03_SCENARIO_KPI_PASS            :",M05_03_SCENARIO_KPI_PASS)


MODULE 5 — M05_03 CELL 11 — FORMAL SCENARIO KPI DERIVATION
 cell_kpi_rows  scenarios  cells  five_qi_values  partial_min_pct  partial_mean_pct  partial_max_pct  total_min_pct  total_mean_pct  total_max_pct
         46080         32     30               3        65.315388          97.58608            100.0      70.663885       98.565915          100.0
------------------------------------------------------------------------------------------------------------
Formal KPI values directly injected : NO
Formula source                      : M05_02 deterministic logic

M05_03_SCENARIO_KPI_PASS            : True


###### Observation

Formal Accessibility KPIs were successfully recomputed for all 46,080 scenario/cell/5QI combinations using the unchanged M05_02 deterministic formulas. No KPI values were directly injected; the observed degradation, including minima of 65.32% Partial and 70.66% Total Accessibility, therefore emerges solely from the controlled PM-counter changes introduced by the incident benchmark.


<a id="cell-12"></a>
##### Cell 12 — Formal KPI Completeness, Mathematical Validity and Upstream Reproduction

Verifies exact `32 × 30 × 16 × 3 = 46,080` cell-KPI rows, positive denominators, valid 0–100% ranges, Added-DRB hierarchy, all 30 SubNetwork contributors, and exact reproduction of M05_02 in non-injected windows.


In [12]:
if not globals().get("M05_03_SCENARIO_KPI_PASS", False):
    raise RuntimeError("Cell 12 requires Cell 11.")

m05_02_kpi_path_sql = str(NR_CELL_KPI_PATH).replace("\\", "/")

con.execute(f"""
CREATE OR REPLACE VIEW m05_02_cell_kpis_reference AS
SELECT * FROM read_parquet('{m05_02_kpi_path_sql}')
""")

EXPECTED_KPI_ROWS = 32 * 30 * 16 * 3

# ------------------------------------------------------------------
# 1. Formal KPI completeness and valid ranges
# ------------------------------------------------------------------

formal = con.execute("""
SELECT
    COUNT(*) AS rows,
    SUM(
        CASE
            WHEN partial_drb_accessibility_pct IS NULL
              OR NOT isfinite(partial_drb_accessibility_pct)
              OR partial_drb_accessibility_pct < 0
              OR partial_drb_accessibility_pct > 100
            THEN 1 ELSE 0
        END
    ) AS partial_failures,
    SUM(
        CASE
            WHEN total_drb_accessibility_pct IS NULL
              OR NOT isfinite(total_drb_accessibility_pct)
              OR total_drb_accessibility_pct < 0
              OR total_drb_accessibility_pct > 100
            THEN 1 ELSE 0
        END
    ) AS total_failures
FROM m05_03_cell_kpis
""").df()

# ------------------------------------------------------------------
# 2. Denominator and Added-DRB hierarchy validation
# ------------------------------------------------------------------

hier = con.execute("""
SELECT
    SUM(
        CASE
            WHEN total_service_intent_denominator <= 0
              OR total_service_intent_denominator IS NULL
              OR NOT isfinite(total_service_intent_denominator)
            THEN 1 ELSE 0
        END
    ) AS denominator_failures,

    SUM(
        CASE
            WHEN added_att < 0
              OR added_succ < 0
              OR added_succ > added_att
            THEN 1 ELSE 0
        END
    ) AS added_drb_failures

FROM m05_03_total
""").df()

# ------------------------------------------------------------------
# 3. SubNetwork contributor completeness
# ------------------------------------------------------------------

sub = con.execute("""
SELECT
    MIN(contributing_nr_cell_cu) AS min_cells,
    MAX(contributing_nr_cell_cu) AS max_cells
FROM m05_03_subnetwork_kpis
""").df()

# ------------------------------------------------------------------
# 4. Exact reproduction of M05_02 in untouched periods
# ------------------------------------------------------------------

repro = con.execute("""
WITH c AS (

    SELECT
        k.scenario_id,
        t.phase,
        pc.family_internal,

        ABS(
            k.partial_drb_accessibility_pct
            - r.partial_drb_accessibility_pct
        ) AS pd,

        ABS(
            k.total_drb_accessibility_pct
            - r.total_drb_accessibility_pct
        ) AS td

    FROM m05_03_cell_kpis k

    JOIN m05_03_timeline t
      ON k.scenario_id = t.scenario_id
     AND k.interval_start_utc = t.interval_start_utc

    JOIN m05_03_private_cases pc
      ON k.scenario_id = pc.scenario_id

    JOIN m05_02_cell_kpis_reference r
      ON k.entity_id = r.entity_id
     AND k.interval_start_utc = r.interval_start_utc
     AND k.five_qi = CAST(r.five_qi AS VARCHAR)
)

SELECT
    MAX(
        CASE
            WHEN phase IN ('PRE', 'RECOVERY')
            THEN pd ELSE 0
        END
    ) AS pre_recovery_partial_max_diff,

    MAX(
        CASE
            WHEN phase IN ('PRE', 'RECOVERY')
            THEN td ELSE 0
        END
    ) AS pre_recovery_total_max_diff,

    MAX(
        CASE
            WHEN family_internal = 'HEALTHY_CONTROL'
            THEN pd ELSE 0
        END
    ) AS healthy_partial_max_diff,

    MAX(
        CASE
            WHEN family_internal = 'HEALTHY_CONTROL'
            THEN td ELSE 0
        END
    ) AS healthy_total_max_diff

FROM c
""").df()

# ------------------------------------------------------------------
# 5. Validation gates
# ------------------------------------------------------------------

tol = 1e-10

checks = {
    "expected_cell_kpi_rows_46080":
        int(formal.loc[0, "rows"]) == EXPECTED_KPI_ROWS,

    "partial_range_valid":
        int(formal.loc[0, "partial_failures"]) == 0,

    "total_range_valid":
        int(formal.loc[0, "total_failures"]) == 0,

    "total_denominators_valid":
        int(hier.loc[0, "denominator_failures"]) == 0,

    "added_drb_hierarchy_valid":
        int(hier.loc[0, "added_drb_failures"]) == 0,

    "subnetwork_all_30_cells":
        int(sub.loc[0, "min_cells"]) == 30
        and int(sub.loc[0, "max_cells"]) == 30,

    "pre_recovery_reproduces_m05_02":
        float(repro.loc[0, "pre_recovery_partial_max_diff"]) <= tol
        and float(repro.loc[0, "pre_recovery_total_max_diff"]) <= tol,

    "healthy_control_reproduces_m05_02":
        float(repro.loc[0, "healthy_partial_max_diff"]) <= tol
        and float(repro.loc[0, "healthy_total_max_diff"]) <= tol,
}

# ------------------------------------------------------------------
# 6. Output
# ------------------------------------------------------------------

print("=" * 108)
print("MODULE 5 — M05_03 CELL 12 — FORMAL KPI VALIDATION")
print("=" * 108)

for name, passed in checks.items():
    print(f"{'PASS' if passed else 'FAIL':<7} {name}")

print("-" * 108)

print(
    "Expected / observed KPI rows        :",
    f"{EXPECTED_KPI_ROWS:,} / {int(formal.loc[0, 'rows']):,}"
)

print("\nM05_02 reproduction diagnostics\n" + "-" * 108)
print(repro.to_string(index=False))

failed = [name for name, passed in checks.items() if not passed]

if failed:
    raise RuntimeError(
        "M05_03 formal KPI validation failed: "
        + ", ".join(failed)
    )

M05_03_KPI_VALIDATION_PASS = True

print(
    "\nM05_03_KPI_VALIDATION_PASS          :",
    M05_03_KPI_VALIDATION_PASS
)

MODULE 5 — M05_03 CELL 12 — FORMAL KPI VALIDATION
PASS    expected_cell_kpi_rows_46080
PASS    partial_range_valid
PASS    total_range_valid
PASS    total_denominators_valid
PASS    added_drb_hierarchy_valid
PASS    subnetwork_all_30_cells
PASS    pre_recovery_reproduces_m05_02
PASS    healthy_control_reproduces_m05_02
------------------------------------------------------------------------------------------------------------
Expected / observed KPI rows        : 46,080 / 46,080

M05_02 reproduction diagnostics
------------------------------------------------------------------------------------------------------------
 pre_recovery_partial_max_diff  pre_recovery_total_max_diff  healthy_partial_max_diff  healthy_total_max_diff
                           0.0                          0.0                       0.0                     0.0

M05_03_KPI_VALIDATION_PASS          : True


###### Observation

Formal KPI validation passed all checks across the 46,080 expected cell/5QI records. KPI ranges, denominators, Added-DRB hierarchy and SubNetwork aggregation remain mathematically valid, while PRE, RECOVERY and HEALTHY_CONTROL periods reproduce the authoritative M05_02 KPIs exactly with zero numerical difference.


<a id="section-6-diagnosability"></a>
# Section 6 — Causal Diagnosability and Truth Separation


<a id="cell-13"></a>
##### Cell 13 — Causal Signature and Exclusion-Evidence Validation

For every non-control scenario, at least two declared direct evidence metrics must actually change in the intended causal scope while declared exclusion evidence remains unchanged there. Healthy controls must contain zero injected changes.


In [13]:
if not globals().get("M05_03_KPI_VALIDATION_PASS",False):
    raise RuntimeError("Cell 13 requires Cell 12.")

def changed_expr(a="w"):
    return f"""(
      COALESCE(ABS(
        COALESCE({a}.value_float,CAST({a}.value_int AS DOUBLE))-
        COALESCE({a}.original_value_float,CAST({a}.original_value_int AS DOUBLE))
      ),0)>1e-12
      OR {a}.value_bool IS DISTINCT FROM {a}.original_value_bool
      OR {a}.value_text IS DISTINCT FROM {a}.original_value_text
    )"""

def scope_clause(family):
    sc=INCIDENT_FAMILIES[family]["scope_class"]
    if sc in {"CELL","CELL_5QI"}:
        return "(w.site_id=pc.target_site_id OR w.cu_domain_id=pc.target_cu_domain_id)"
    if sc=="SITE":
        return "w.site_id=pc.target_site_id"
    if sc in {"CU_DOMAIN","CU_DOMAIN_BOUNDARY"}:
        return "w.cu_domain_id=pc.target_cu_domain_id"
    return "TRUE"

audit=[]
for case in PRIVATE_CASES_DF.itertuples(index=False):
    family=case.family_internal
    s=INCIDENT_FAMILIES[family]

    if family=="HEALTHY_CONTROL":
        changed=int(con.execute(f"""
        SELECT COUNT(*) FROM m05_03_working_telemetry w
        WHERE scenario_id='{case.scenario_id}' AND {changed_expr()}
        """).fetchone()[0])
        audit.append({
            "scenario_id":case.scenario_id,"family_internal":family,
            "changed_positive_metrics":0,"declared_direct_metrics":0,
            "changed_exclusion_rows":0,"healthy_injected_changes":changed,
            "positive_evidence_pass":changed==0,"exclusion_evidence_pass":True,
        })
        continue

    sc=scope_clause(family)
    positive_changed=0
    for metric in s["direct_change_metrics"]:
        extra=""
        if s["target_5qi"] is not None and metric.startswith("DRB."):
            extra=f"AND CAST(w.dimension_5qi AS VARCHAR)='{s['target_5qi']}'"
        n=int(con.execute(f"""
        SELECT COUNT(*) FROM m05_03_working_telemetry w
        JOIN m05_03_private_cases pc USING(scenario_id)
        WHERE w.scenario_id='{case.scenario_id}' AND w.phase='INCIDENT'
          AND w.metric_name='{metric}' AND ({sc}) {extra}
          AND {changed_expr()}
        """).fetchone()[0])
        positive_changed += int(n>0)

    exclusion_changes=0
    for metric in s["exclusion_metrics"]:
        exclusion_changes += int(con.execute(f"""
        SELECT COUNT(*) FROM m05_03_working_telemetry w
        JOIN m05_03_private_cases pc USING(scenario_id)
        WHERE w.scenario_id='{case.scenario_id}' AND w.phase='INCIDENT'
          AND w.metric_name='{metric}' AND ({sc}) AND {changed_expr()}
        """).fetchone()[0])

    audit.append({
        "scenario_id":case.scenario_id,"family_internal":family,
        "changed_positive_metrics":positive_changed,
        "declared_direct_metrics":len(s["direct_change_metrics"]),
        "changed_exclusion_rows":exclusion_changes,"healthy_injected_changes":0,
        "positive_evidence_pass":positive_changed>=2,
        "exclusion_evidence_pass":exclusion_changes==0,
    })

INJECTION_AUDIT_DF=pd.DataFrame(audit)
family_audit=INJECTION_AUDIT_DF.groupby("family_internal").agg(
    scenarios=("scenario_id","count"),
    min_changed_positive_metrics=("changed_positive_metrics","min"),
    exclusion_change_rows=("changed_exclusion_rows","sum"),
    healthy_injected_changes=("healthy_injected_changes","sum"),
    positive_pass=("positive_evidence_pass","all"),
    exclusion_pass=("exclusion_evidence_pass","all"),
).reset_index()

checks={
 "all_fault_cases_have_2plus_positive_metrics":
     bool(INJECTION_AUDIT_DF.loc[
         INJECTION_AUDIT_DF["family_internal"]!="HEALTHY_CONTROL","positive_evidence_pass"
     ].all()),
 "all_target_exclusion_evidence_unchanged":
     bool(INJECTION_AUDIT_DF["exclusion_evidence_pass"].all()),
 "healthy_controls_unmodified":
     int(INJECTION_AUDIT_DF.loc[
         INJECTION_AUDIT_DF["family_internal"]=="HEALTHY_CONTROL","healthy_injected_changes"
     ].sum())==0,
}

print("="*108)
print("MODULE 5 — M05_03 CELL 13 — CAUSAL SIGNATURE VALIDATION")
print("="*108)
print(family_audit.to_string(index=False))
print("-"*108)
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 causal signature validation failed: "+", ".join(failed))

M05_03_CAUSAL_SIGNATURE_PASS=True
print("\nM05_03_CAUSAL_SIGNATURE_PASS        :",M05_03_CAUSAL_SIGNATURE_PASS)


MODULE 5 — M05_03 CELL 13 — CAUSAL SIGNATURE VALIDATION
          family_internal  scenarios  min_changed_positive_metrics  exclusion_change_rows  healthy_injected_changes  positive_pass  exclusion_pass
      AMF_FACING_BOUNDARY          4                             3                      0                         0           True            True
CU_CP_PROCESSING_PRESSURE          4                             4                      0                         0           True            True
          HEALTHY_CONTROL          4                             0                      0                         0           True            True
   N2_PACKET_LOSS_LATENCY          4                             4                      0                         0           True            True
        QOS_CONFIGURATION          4                             3                      0                         0           True            True
       RADIO_INTERFERENCE          4                          

###### Observation

Causal-signature validation passed across all 32 scenarios. Every fault family produced at least two intended direct-evidence changes while all declared exclusion evidence remained unchanged in the target scope, and healthy controls remained fully unmodified. This confirms that the benchmark preserves distinguishable causal patterns rather than generic KPI degradation.


<a id="cell-14"></a>
##### Cell 14 — Diagnosability and Competing-Hypothesis Gate

A formal incident is admitted only if its evidence is diagnostically discriminating. This cell also confirms that the intended affected KPI population degrades during each non-control incident relative to its own pre-window.


In [14]:
if not globals().get("M05_03_CAUSAL_SIGNATURE_PASS",False):
    raise RuntimeError("Cell 14 requires Cell 13.")

impact=[]
for case in PRIVATE_CASES_DF.itertuples(index=False):
    family=case.family_internal
    if family=="HEALTHY_CONTROL":
        impact.append({
            "scenario_id":case.scenario_id,"family_internal":family,
            "pre_total_mean_pct":np.nan,"incident_total_mean_pct":np.nan,
            "delta_pct_points":np.nan,"kpi_impact_pass":True,
        })
        continue

    s=INCIDENT_FAMILIES[family]
    target_cells=TARGET_CELLS_DF.loc[
        TARGET_CELLS_DF["scenario_id"]==case.scenario_id,"nr_cell_cu_id"
    ].tolist()
    if not target_cells:
        raise RuntimeError(f"No KPI target cells for {case.scenario_id}")
    qcells=", ".join(f"'{x}'" for x in target_cells)
    q5="" if s["target_5qi"] is None else f"AND k.five_qi='{s['target_5qi']}'"

    d=con.execute(f"""
    SELECT
      AVG(CASE WHEN t.phase='PRE' THEN k.total_drb_accessibility_pct END) AS pre_mean,
      AVG(CASE WHEN t.phase='INCIDENT' THEN k.total_drb_accessibility_pct END) AS incident_mean
    FROM m05_03_cell_kpis k
    JOIN m05_03_timeline t
      ON k.scenario_id=t.scenario_id AND k.interval_start_utc=t.interval_start_utc
    WHERE k.scenario_id='{case.scenario_id}' AND k.entity_id IN ({qcells}) {q5}
    """).df()
    pre=float(d.loc[0,"pre_mean"]); inc=float(d.loc[0,"incident_mean"])
    impact.append({
        "scenario_id":case.scenario_id,"family_internal":family,
        "pre_total_mean_pct":pre,"incident_total_mean_pct":inc,
        "delta_pct_points":inc-pre,"kpi_impact_pass":inc<pre,
    })

KPI_IMPACT_DF=pd.DataFrame(impact)
event_ids=set(EVENTS_DF["scenario_id"])
structural=[]
for family,s in non_control.items():
    if len(s["direct_change_metrics"])<2:structural.append(f"{family}: direct evidence")
    if len(s["exclusion_metrics"])<2:structural.append(f"{family}: exclusion evidence")
    if len(s["competing_hypotheses"])<2:structural.append(f"{family}: competitors")
    if s["event_expected"]:
        ids=set(PRIVATE_CASES_DF.loc[
            PRIVATE_CASES_DF["family_internal"]==family,"scenario_id"
        ])
        if not ids.issubset(event_ids):structural.append(f"{family}: missing expected event")

family_impact=KPI_IMPACT_DF[
    KPI_IMPACT_DF["family_internal"]!="HEALTHY_CONTROL"
].groupby("family_internal").agg(
    cases=("scenario_id","count"),
    mean_pre_pct=("pre_total_mean_pct","mean"),
    mean_incident_pct=("incident_total_mean_pct","mean"),
    mean_delta_pp=("delta_pct_points","mean"),
    all_cases_degrade=("kpi_impact_pass","all"),
).reset_index()

checks={
 "structural_diagnosability_complete":not structural,
 "every_non_control_case_degrades_target_kpi":
     bool(KPI_IMPACT_DF.loc[
         KPI_IMPACT_DF["family_internal"]!="HEALTHY_CONTROL","kpi_impact_pass"
     ].all()),
 "healthy_control_cases_4":
     int((PRIVATE_CASES_DF["family_internal"]=="HEALTHY_CONTROL").sum())==4,
}

print("="*108)
print("MODULE 5 — M05_03 CELL 14 — DIAGNOSABILITY GATE")
print("="*108)
print(family_impact.round(6).to_string(index=False))
print("-"*108)
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")
print("Structural failures                 :",structural)

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 diagnosability gate failed: "+", ".join(failed))

M05_03_DIAGNOSABILITY_PASS=True
print("\nM05_03_DIAGNOSABILITY_PASS          :",M05_03_DIAGNOSABILITY_PASS)


MODULE 5 — M05_03 CELL 14 — DIAGNOSABILITY GATE
          family_internal  cases  mean_pre_pct  mean_incident_pct  mean_delta_pp  all_cases_degrade
      AMF_FACING_BOUNDARY      4     99.555954          89.611974      -9.943980               True
CU_CP_PROCESSING_PRESSURE      4     99.547060          91.908264      -7.638796               True
   N2_PACKET_LOSS_LATENCY      4     99.559662          91.438906      -8.120756               True
        QOS_CONFIGURATION      4     99.413694          81.504302     -17.909392               True
       RADIO_INTERFERENCE      4     99.495736          85.852537     -13.643199               True
RADIO_RESOURCE_CONGESTION      4     99.519929          84.581621     -14.938308               True
        RRC_CONFIGURATION      4     99.563129          89.521952     -10.041177               True
------------------------------------------------------------------------------------------------------------
PASS    structural_diagnosability_complete


###### Observation

The diagnosability gate passed for all benchmark families. Every non-control scenario produced a measurable target-KPI degradation, while structural evidence and competing-hypothesis definitions remained complete. The variation in degradation magnitude across fault families supports realistic diagnosis based on causal evidence rather than KPI severity alone.


<a id="cell-15"></a>
##### Cell 15 — Build Public Benchmark Cases and Private Ground Truth

The public contract tells the future agent **what task to perform**, not what happened. Private truth stores the injected condition, expected diagnosis, competitors and scoring reference.


In [15]:
if not globals().get("M05_03_DIAGNOSABILITY_PASS",False):
    raise RuntimeError("Cell 15 requires Cell 14.")

PUBLIC_TASK=(
 "Investigate the 5G RAN Accessibility state during the supplied observation window. "
 "Determine whether a genuine incident exists. If an incident exists, identify the most "
 "likely fault family and affected scope using both supporting evidence and evidence that "
 "rules out plausible alternatives. Do not infer a deeper network-domain root cause than "
 "the available observations support."
)
EXPECTED_RESPONSE_SCHEMA={
 "incident_present":"boolean","fault_family":"string_or_null",
 "affected_scope":"string_or_null","supporting_evidence":"list",
 "excluded_hypotheses":"list","confidence":"0_to_1","rationale":"string",
}

public_cases=[];private_truth=[]
for case in PRIVATE_CASES_DF.itertuples(index=False):
    public_cases.append({
        "scenario_id":case.scenario_id,
        "window_start_utc":case.window_start_utc.isoformat(),
        "window_end_utc":case.window_end_utc.isoformat(),
        "pm_interval_minutes":15,"task":PUBLIC_TASK,
        "available_evidence":[
            "formal Accessibility KPIs","standardized PM counters",
            "operational radio/resource telemetry","processing telemetry",
            "transport/SCTP telemetry","configuration state","events","topology context",
        ],
        "expected_response_schema":EXPECTED_RESPONSE_SCHEMA,
    })
    s=INCIDENT_FAMILIES[case.family_internal]
    target_cells=TARGET_CELLS_DF.loc[
        TARGET_CELLS_DF["scenario_id"]==case.scenario_id,
        ["nr_cell_cu_id","nr_cell_du_id"]
    ].to_dict(orient="records")
    private_truth.append({
        "scenario_id":case.scenario_id,"benchmark_split":case.benchmark_split,
        "incident_present":bool(case.incident_present),
        "root_cause_family":case.family_internal,
        "target_component":s["target_component"],"scope_class":s["scope_class"],
        "target_site_id":case.target_site_id,"target_cu_domain_id":case.target_cu_domain_id,
        "target_cells":target_cells,"target_5qi":case.target_5qi,
        "incident_start_utc":case.incident_start_utc.isoformat(),
        "incident_end_utc":case.incident_end_utc.isoformat(),
        "max_severity":float(case.max_severity),
        "expected_diagnosis":s["expected_diagnosis"],
        "positive_metrics":s["positive_metrics"],
        "exclusion_metrics":s["exclusion_metrics"],
        "competing_hypotheses":s["competing_hypotheses"],
        "distractor_metric":case.distractor_metric,
        "distractor_site_id":case.distractor_site_id,
    })

PUBLIC_CASES_SEMANTIC={
 "artifact_id":"module5_m05_03_benchmark_cases_v1","module_id":"M05_03",
 "role":"AGENT_VISIBLE_BENCHMARK_CASE_CONTRACT","cases":public_cases,
}
PUBLIC_CASES_SEMANTIC_SHA=canonical_sha256(PUBLIC_CASES_SEMANTIC)
PUBLIC_CASES_PAYLOAD={**PUBLIC_CASES_SEMANTIC,
 "created_utc":datetime.now(timezone.utc).isoformat(),
 "semantic_sha256":PUBLIC_CASES_SEMANTIC_SHA}

PRIVATE_TRUTH_SEMANTIC={
 "artifact_id":"module5_m05_03_ground_truth_v1","module_id":"M05_03",
 "role":"PRIVATE_EVALUATION_GROUND_TRUTH","agent_visible":False,"cases":private_truth,
}
PRIVATE_TRUTH_SEMANTIC_SHA=canonical_sha256(PRIVATE_TRUTH_SEMANTIC)
PRIVATE_TRUTH_PAYLOAD={**PRIVATE_TRUTH_SEMANTIC,
 "created_utc":datetime.now(timezone.utc).isoformat(),
 "semantic_sha256":PRIVATE_TRUTH_SEMANTIC_SHA}

serialized=json.dumps(PUBLIC_CASES_PAYLOAD,sort_keys=True).lower()
forbidden=[
 "root_cause","ground_truth","fault_label","expected_diagnosis","correct_action",
 "benchmark_answer","family_internal","severity","phase"
]
hits=sorted(t for t in forbidden if t in serialized)

checks={
 "public_cases_32":len(public_cases)==32,
 "private_truth_cases_32":len(private_truth)==32,
 "public_cases_no_truth_fields":not hits,
 "private_artifact_not_agent_visible":PRIVATE_TRUTH_SEMANTIC["agent_visible"] is False,
}
print("="*108)
print("MODULE 5 — M05_03 CELL 15 — PUBLIC / PRIVATE TRUTH SEPARATION")
print("="*108)
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")
print("-"*108)
print("Public-case semantic SHA            :",PUBLIC_CASES_SEMANTIC_SHA)
print("Private-truth semantic SHA          :",PRIVATE_TRUTH_SEMANTIC_SHA)
print("Public forbidden-term hits          :",hits)
print("Private truth available to agent    : NO")

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 truth separation failed: "+", ".join(failed))

M05_03_TRUTH_SEPARATION_PASS=True
print("\nM05_03_TRUTH_SEPARATION_PASS        :",M05_03_TRUTH_SEPARATION_PASS)


MODULE 5 — M05_03 CELL 15 — PUBLIC / PRIVATE TRUTH SEPARATION
PASS    public_cases_32
PASS    private_truth_cases_32
PASS    public_cases_no_truth_fields
PASS    private_artifact_not_agent_visible
------------------------------------------------------------------------------------------------------------
Public-case semantic SHA            : fde8cfaca098da32a16e01cf277487f331d956a715adcee609433de1e31555fd
Private-truth semantic SHA          : 2567c2da9c652f61632be0663752ab2d269a656e1d97c70a64b2553be4741482
Public forbidden-term hits          : []
Private truth available to agent    : NO

M05_03_TRUTH_SEPARATION_PASS        : True


###### Observation

Public/private truth separation passed for all 32 benchmark cases. Agent-visible case definitions contain no hidden diagnostic fields, while the complete ground truth remains isolated in the private benchmark layer with independent semantic provenance for later evaluation.


<a id="cell-16"></a>
##### Cell 16 — DEVELOPMENT / EVAL Isolation and ML Development Labels

Only the 24 DEVELOPMENT cases receive a development-label artifact. The eight held-out EVAL answers remain exclusively inside private ground truth.

**Development guardrail:** `scenario_id` and absolute timestamps are identifiers/context only and must not be used as predictive ML features. M05_05 may use DEVELOPMENT labels for offline training, but held-out EVAL truth remains private.

In [16]:
if not globals().get("M05_03_TRUTH_SEPARATION_PASS",False):
    raise RuntimeError("Cell 16 requires Cell 15.")

DEVELOPMENT_LABELS_DF=pd.DataFrame([
 {
  "scenario_id":t["scenario_id"],"incident_present":t["incident_present"],
  "fault_family":t["root_cause_family"],"scope_class":t["scope_class"],
  "target_5qi":t["target_5qi"],
 }
 for t in private_truth if t["benchmark_split"]=="DEVELOPMENT"
])

eval_ids=set(PRIVATE_CASES_DF.loc[
    PRIVATE_CASES_DF["benchmark_split"]=="EVAL","scenario_id"
])
dev_ids=set(DEVELOPMENT_LABELS_DF["scenario_id"])

checks={
 "development_labels_24":len(DEVELOPMENT_LABELS_DF)==24,
 "eval_cases_8":len(eval_ids)==8,
 "no_eval_id_in_development_labels":not bool(eval_ids&dev_ids),
 "three_development_per_family":
     bool((DEVELOPMENT_LABELS_DF.groupby("fault_family").size()==3).all()),
 "all_eight_families_in_development":
     DEVELOPMENT_LABELS_DF["fault_family"].nunique()==8,
}

print("="*108)
print("MODULE 5 — M05_03 CELL 16 — DEVELOPMENT / EVAL ISOLATION")
print("="*108)
for n,p in checks.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")
print("-"*108)
print("DEVELOPMENT labels                  :",len(DEVELOPMENT_LABELS_DF))
print("Held-out EVAL cases                 :",len(eval_ids))
print("EVAL answers in development labels  : NO")

failed=[n for n,p in checks.items() if not p]
if failed:raise RuntimeError("M05_03 split isolation failed: "+", ".join(failed))

M05_03_SPLIT_ISOLATION_PASS=True
print("\nM05_03_SPLIT_ISOLATION_PASS         :",M05_03_SPLIT_ISOLATION_PASS)


MODULE 5 — M05_03 CELL 16 — DEVELOPMENT / EVAL ISOLATION
PASS    development_labels_24
PASS    eval_cases_8
PASS    no_eval_id_in_development_labels
PASS    three_development_per_family
PASS    all_eight_families_in_development
------------------------------------------------------------------------------------------------------------
DEVELOPMENT labels                  : 24
Held-out EVAL cases                 : 8
EVAL answers in development labels  : NO

M05_03_SPLIT_ISOLATION_PASS         : True


###### Observation

The DEVELOPMENT/EVAL isolation passed all checks. Exactly 24 labelled DEVELOPMENT cases are available across all 8 case families, while the 8 held-out EVAL cases remain excluded from development labels, preserving an independent benchmark for later agent evaluation.


<a id="section-7-persistence-closeout"></a>
# Section 7 — Persistence, Manifest and Closeout


<a id="cell-17"></a>
##### Cell 17 — Immutable Benchmark Output Persistence

Creates new M05_03 artifacts only. If a versioned path already exists, an identical byte artifact is verified; a different artifact causes failure rather than silent overwrite. Parquet products are ordered before serialization.


In [17]:
if not globals().get("M05_03_SPLIT_ISOLATION_PASS",False):
    raise RuntimeError("Cell 17 requires Cell 16.")

import shutil

M05_03_BENCHMARK_DIR.mkdir(parents=True,exist_ok=True)
M05_03_PRIVATE_DIR.mkdir(parents=True,exist_ok=True)
M05_03_MANIFEST_DIR.mkdir(parents=True,exist_ok=True)

AGENT_TELEMETRY_PATH=M05_03_BENCHMARK_DIR/"module5_m05_03_agent_visible_telemetry_v1.parquet"
CELL_KPI_OUTPUT_PATH=M05_03_BENCHMARK_DIR/"module5_m05_03_agent_visible_cell_kpis_v1.parquet"
SUBNETWORK_KPI_OUTPUT_PATH=M05_03_BENCHMARK_DIR/"module5_m05_03_agent_visible_subnetwork_kpis_v1.parquet"
EVENTS_OUTPUT_PATH=M05_03_BENCHMARK_DIR/"module5_m05_03_agent_visible_events_v1.parquet"
PUBLIC_CASES_PATH=M05_03_BENCHMARK_DIR/"module5_m05_03_benchmark_cases_v1.json"

PRIVATE_TRUTH_PATH=M05_03_PRIVATE_DIR/"module5_m05_03_ground_truth_v1.json"
DEVELOPMENT_LABELS_PATH=M05_03_PRIVATE_DIR/"module5_m05_03_development_labels_v1.parquet"
INJECTION_AUDIT_PATH=M05_03_PRIVATE_DIR/"module5_m05_03_injection_audit_summary_v1.parquet"

ROADMAP_AMENDMENT_PATH=M05_03_MANIFEST_DIR/"module5_m05_03_roadmap_amendment_v1.json"

TEMP_DIR=Path("/content/m05_03_persistence_temp")
TEMP_DIR.mkdir(parents=True,exist_ok=True)

def persist_temp_immutable(temp_path,destination):
    temp_path=Path(temp_path);destination=Path(destination)
    new_sha=sha256_file(temp_path)
    if destination.exists():
        if sha256_file(destination)!=new_sha:
            raise FileExistsError(f"Different artifact already exists at {destination}")
        operation="VERIFIED_EXISTING"
    else:
        shutil.copy2(temp_path,destination)
        operation="CREATED"
    return {
        "path":str(destination),"operation":operation,
        "bytes":destination.stat().st_size,
        "artifact_sha256":sha256_file(destination),
    }

def persist_json_semantic_immutable(payload,destination):
    destination=Path(destination)
    serialized=json.dumps(payload,indent=2,sort_keys=True,ensure_ascii=False)+"\n"
    if destination.exists():
        existing=load_json(destination)
        if existing.get("semantic_sha256")!=payload.get("semantic_sha256"):
            raise FileExistsError(f"Different semantic JSON artifact already exists at {destination}")
        operation="VERIFIED_EXISTING"
    else:
        destination.write_text(serialized,encoding="utf-8")
        operation="CREATED"
    return {
        "path":str(destination),"operation":operation,
        "bytes":destination.stat().st_size,
        "artifact_sha256":sha256_file(destination),
        "semantic_sha256":payload.get("semantic_sha256"),
    }

def copy_query(query,temp_name):
    p=TEMP_DIR/temp_name
    if p.exists():p.unlink()
    ps=str(p).replace("\\","/")
    con.execute(f"COPY ({query}) TO '{ps}' (FORMAT PARQUET, COMPRESSION ZSTD)")
    return p

agent_temp=copy_query("""
 SELECT * FROM m05_03_agent_telemetry
 ORDER BY scenario_id,interval_start_utc,metric_name,entity_id,
          COALESCE(dimension_cause,''),
          COALESCE(CAST(dimension_5qi AS VARCHAR),''),
          COALESCE(dimension_snssai,'')
""","agent_visible_telemetry.parquet")

cell_temp=copy_query("""
 SELECT * FROM m05_03_cell_kpis
 ORDER BY scenario_id,interval_start_utc,entity_id,five_qi
""","agent_visible_cell_kpis.parquet")

sub_temp=copy_query("""
 SELECT * FROM m05_03_subnetwork_kpis
 ORDER BY scenario_id,interval_start_utc,five_qi
""","agent_visible_subnetwork_kpis.parquet")

events_temp=copy_query("""
 SELECT * FROM m05_03_agent_events
 ORDER BY scenario_id,event_time_utc,event_metric_name,entity_id
""","agent_visible_events.parquet")

con.register("development_labels_input",DEVELOPMENT_LABELS_DF)
con.execute("CREATE OR REPLACE TABLE m05_03_development_labels AS SELECT * FROM development_labels_input")
dev_temp=copy_query("SELECT * FROM m05_03_development_labels ORDER BY scenario_id",
                    "development_labels.parquet")

con.register("injection_audit_input",INJECTION_AUDIT_DF)
con.execute("CREATE OR REPLACE TABLE m05_03_injection_audit AS SELECT * FROM injection_audit_input")
audit_temp=copy_query("SELECT * FROM m05_03_injection_audit ORDER BY scenario_id",
                      "injection_audit.parquet")

OUTPUT_PERSISTENCE={
 "agent_visible_telemetry":persist_temp_immutable(agent_temp,AGENT_TELEMETRY_PATH),
 "agent_visible_cell_kpis":persist_temp_immutable(cell_temp,CELL_KPI_OUTPUT_PATH),
 "agent_visible_subnetwork_kpis":persist_temp_immutable(sub_temp,SUBNETWORK_KPI_OUTPUT_PATH),
 "agent_visible_events":persist_temp_immutable(events_temp,EVENTS_OUTPUT_PATH),
 "benchmark_cases":persist_json_semantic_immutable(PUBLIC_CASES_PAYLOAD,PUBLIC_CASES_PATH),
 "private_ground_truth":persist_json_semantic_immutable(PRIVATE_TRUTH_PAYLOAD,PRIVATE_TRUTH_PATH),
 "development_labels":persist_temp_immutable(dev_temp,DEVELOPMENT_LABELS_PATH),
 "injection_audit":persist_temp_immutable(audit_temp,INJECTION_AUDIT_PATH),
 "roadmap_amendment":persist_json_semantic_immutable(
     ROADMAP_AMENDMENT_PAYLOAD,ROADMAP_AMENDMENT_PATH
 ),
}

print("="*108)
print("MODULE 5 — M05_03 CELL 17 — IMMUTABLE OUTPUT PERSISTENCE")
print("="*108)
for name,r in OUTPUT_PERSISTENCE.items():
    print(f"\n{name}\n"+"-"*108)
    print("Operation                           :",r["operation"])
    print("Bytes                               :",f"{r['bytes']:,}")
    print("SHA-256                             :",r["artifact_sha256"])
    print("Path                                :",r["path"])

M05_03_OUTPUT_PERSISTENCE_PASS=True
print("\nM05_03_OUTPUT_PERSISTENCE_PASS      :",M05_03_OUTPUT_PERSISTENCE_PASS)


MODULE 5 — M05_03 CELL 17 — IMMUTABLE OUTPUT PERSISTENCE

agent_visible_telemetry
------------------------------------------------------------------------------------------------------------
Operation                           : CREATED
Bytes                               : 18,323,056
SHA-256                             : e7ecf55940a32dacabe8df9ccc4f133351b5288bf17e352237906155f9231ff4
Path                                : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_03/benchmark/module5_m05_03_agent_visible_telemetry_v1.parquet

agent_visible_cell_kpis
------------------------------------------------------------------------------------------------------------
Operation                           : CREATED
Bytes                               : 536,758
SHA-256                             : 9b54d281938bcfdec1d3bea76821d7ca0b160ab80036f3ca2f5e49977a2e85c5
Path                                : /content/drive/MyDrive/Telecom_AI_Engineering_Platform/Module_5/M05_03/benc

###### Observation

All M05_03 benchmark, private-truth and provenance artifacts were successfully persisted with independent SHA-256 identities. Agent-visible telemetry, KPIs, events and public cases remain physically separated from ground truth and development labels, establishing a durable and reproducible benchmark for subsequent MCP and agent stages.


<a id="cell-18"></a>
##### Cell 18 — Incident Benchmark Manifest and Validation Receipt

Binds upstream semantic identities, the roadmap amendment, benchmark design, split counts, persisted artifact hashes, standards/synthetic boundaries and all validation gates. Only a fully passing receipt authorizes M05_04.


In [18]:
if not globals().get("M05_03_OUTPUT_PERSISTENCE_PASS",False):
    raise RuntimeError("Cell 18 requires Cell 17.")

MANIFEST_PATH=M05_03_MANIFEST_DIR/"module5_m05_03_incident_benchmark_manifest_v1.json"
RECEIPT_PATH=M05_03_MANIFEST_DIR/"module5_m05_03_validation_receipt_v1.json"

manifest_semantic={
 "artifact_id":"module5_m05_03_incident_benchmark_manifest_v1",
 "module_id":"M05_03","module_role":"CONTROLLED_INCIDENTS_AND_BENCHMARK",
 "upstream_root_of_trust":{
   "m05_01_freeze_semantic_sha256":EXPECTED["m05_01_freeze_semantic_sha256"],
   "canonical_telemetry_semantic_sha256":EXPECTED["canonical_telemetry_semantic_sha256"],
   "m05_02_kpi_manifest_semantic_sha256":EXPECTED["m05_02_kpi_manifest_semantic_sha256"],
   "m05_02_validation_receipt_semantic_sha256":
       EXPECTED["m05_02_validation_receipt_semantic_sha256"],
 },
 "roadmap_amendment":{
   "decision":ROADMAP_AMENDMENT_SEMANTIC["decision"],
   "semantic_sha256":M05_03_ROADMAP_AMENDMENT_SEMANTIC_SHA,
   "sionna_used":False,
 },
 "benchmark_design":{
   "families":CASE_FAMILIES,"family_count":len(CASE_FAMILIES),
   "scenario_count":len(PRIVATE_CASES_DF),
   "development_cases":int((PRIVATE_CASES_DF["benchmark_split"]=="DEVELOPMENT").sum()),
   "held_out_eval_cases":int((PRIVATE_CASES_DF["benchmark_split"]=="EVAL").sum()),
   "case_window_hours":4,"pm_interval_minutes":15,"cell_kpi_rows":EXPECTED_KPI_ROWS,
 },
 "truth_separation":{
   "agent_visible_truth_labels":False,"private_truth_separate":True,
   "eval_labels_in_development_artifact":False,
   "future_telemetry_mcp_may_load_private_dir":False,
 },
 "outputs":OUTPUT_PERSISTENCE,
 "standards_and_synthetic_boundary":{
   "formal_partial_kpi":"TS 28.554 Clause 6.2.4",
   "formal_total_kpi":"TS 28.554 Clause 6.2.7",
   "formal_kpis_recomputed_from_pm":True,
   "fault_severity_is_synthetic":True,
   "synthetic_thresholds_claimed_as_3gpp":False,
   "direct_kpi_injection":False,
 },
}
M05_03_MANIFEST_SEMANTIC_SHA=canonical_sha256(manifest_semantic)
manifest_payload={**manifest_semantic,
 "created_utc":datetime.now(timezone.utc).isoformat(),
 "semantic_sha256":M05_03_MANIFEST_SEMANTIC_SHA}

validation_gates={
 "upstream_restore":bool(M05_03_UPSTREAM_RESTORE_PASS),
 "benchmark_contract":bool(M05_03_BENCHMARK_CONTRACT_PASS),
 "telemetry_runtime":bool(M05_03_TELEMETRY_RUNTIME_PASS),
 "topology":bool(M05_03_TOPOLOGY_PASS),
 "incident_design":bool(M05_03_INCIDENT_DESIGN_PASS),
 "episode_schedule":bool(M05_03_EPISODE_SCHEDULE_PASS),
 "base_slice":bool(M05_03_BASE_SLICE_PASS),
 "numeric_overlay":bool(M05_03_NUMERIC_OVERLAY_PASS),
 "context_overlay":bool(M05_03_CONTEXT_OVERLAY_PASS),
 "leakage":bool(M05_03_LEAKAGE_PASS),
 "scenario_kpi":bool(M05_03_SCENARIO_KPI_PASS),
 "kpi_validation":bool(M05_03_KPI_VALIDATION_PASS),
 "causal_signature":bool(M05_03_CAUSAL_SIGNATURE_PASS),
 "diagnosability":bool(M05_03_DIAGNOSABILITY_PASS),
 "truth_separation":bool(M05_03_TRUTH_SEPARATION_PASS),
 "split_isolation":bool(M05_03_SPLIT_ISOLATION_PASS),
 "output_persistence":bool(M05_03_OUTPUT_PERSISTENCE_PASS),
}

receipt_semantic={
 "artifact_id":"module5_m05_03_validation_receipt_v1","module_id":"M05_03",
 "incident_benchmark_manifest_semantic_sha256":M05_03_MANIFEST_SEMANTIC_SHA,
 "validation_gates":validation_gates,
 "all_validation_gates_pass":all(validation_gates.values()),
 "authorized_next_stage":"M05_04_TELEMETRY_MCP_SERVICE",
}
M05_03_VALIDATION_RECEIPT_SEMANTIC_SHA=canonical_sha256(receipt_semantic)
receipt_payload={**receipt_semantic,
 "created_utc":datetime.now(timezone.utc).isoformat(),
 "semantic_sha256":M05_03_VALIDATION_RECEIPT_SEMANTIC_SHA}

MANIFEST_PERSISTENCE=persist_json_semantic_immutable(manifest_payload,MANIFEST_PATH)
RECEIPT_PERSISTENCE=persist_json_semantic_immutable(receipt_payload,RECEIPT_PATH)
M05_03_PERSISTENCE_PASS=bool(receipt_payload["all_validation_gates_pass"])

print("="*108)
print("MODULE 5 — M05_03 CELL 18 — MANIFEST + VALIDATION RECEIPT")
print("="*108)
print("Benchmark manifest semantic SHA     :",M05_03_MANIFEST_SEMANTIC_SHA)
print("Validation receipt semantic SHA     :",M05_03_VALIDATION_RECEIPT_SEMANTIC_SHA)
print("All validation gates pass           :",receipt_payload["all_validation_gates_pass"])
print("Authorized next stage               :",receipt_payload["authorized_next_stage"])
print("M05_03_PERSISTENCE_PASS             :",M05_03_PERSISTENCE_PASS)

if not M05_03_PERSISTENCE_PASS:
    raise RuntimeError("M05_03 validation receipt contains a failed gate.")


MODULE 5 — M05_03 CELL 18 — MANIFEST + VALIDATION RECEIPT
Benchmark manifest semantic SHA     : 005232cb9326334e9a03f0a751b6eff325ffad4bc13c42caf48df8773193f7e7
Validation receipt semantic SHA     : 59a0658f880fae4f8acea6358ad74702839a46eeb46e4c17e48b6c9013f8daca
All validation gates pass           : True
Authorized next stage               : M05_04_TELEMETRY_MCP_SERVICE
M05_03_PERSISTENCE_PASS             : True


###### Observation

The M05_03 benchmark manifest and validation receipt were successfully created with fixed semantic identities. All validation gates passed, confirming the benchmark is complete, reproducible and ready for downstream use. The authorized next stage is formally recorded as `M05_04_TELEMETRY_MCP_SERVICE`.


<a id="cell-19"></a>
##### Cell 19 — M05_03 Closeout and M05_04 Handover

The final cell verifies the complete benchmark chain. M05_04 may restore only the **agent-visible benchmark directory** plus M05_03 manifest/receipt; it must not load the private truth directory into the Telemetry MCP runtime.


In [19]:
if not globals().get("M05_03_PERSISTENCE_PASS",False):
    raise RuntimeError("Cell 19 requires Cell 18.")

closeout_gates={
 "M05_03_UPSTREAM_RESTORE_PASS":M05_03_UPSTREAM_RESTORE_PASS,
 "M05_03_BENCHMARK_CONTRACT_PASS":M05_03_BENCHMARK_CONTRACT_PASS,
 "M05_03_TELEMETRY_RUNTIME_PASS":M05_03_TELEMETRY_RUNTIME_PASS,
 "M05_03_TOPOLOGY_PASS":M05_03_TOPOLOGY_PASS,
 "M05_03_INCIDENT_DESIGN_PASS":M05_03_INCIDENT_DESIGN_PASS,
 "M05_03_EPISODE_SCHEDULE_PASS":M05_03_EPISODE_SCHEDULE_PASS,
 "M05_03_BASE_SLICE_PASS":M05_03_BASE_SLICE_PASS,
 "M05_03_NUMERIC_OVERLAY_PASS":M05_03_NUMERIC_OVERLAY_PASS,
 "M05_03_CONTEXT_OVERLAY_PASS":M05_03_CONTEXT_OVERLAY_PASS,
 "M05_03_LEAKAGE_PASS":M05_03_LEAKAGE_PASS,
 "M05_03_SCENARIO_KPI_PASS":M05_03_SCENARIO_KPI_PASS,
 "M05_03_KPI_VALIDATION_PASS":M05_03_KPI_VALIDATION_PASS,
 "M05_03_CAUSAL_SIGNATURE_PASS":M05_03_CAUSAL_SIGNATURE_PASS,
 "M05_03_DIAGNOSABILITY_PASS":M05_03_DIAGNOSABILITY_PASS,
 "M05_03_TRUTH_SEPARATION_PASS":M05_03_TRUTH_SEPARATION_PASS,
 "M05_03_SPLIT_ISOLATION_PASS":M05_03_SPLIT_ISOLATION_PASS,
 "M05_03_OUTPUT_PERSISTENCE_PASS":M05_03_OUTPUT_PERSISTENCE_PASS,
 "M05_03_PERSISTENCE_PASS":M05_03_PERSISTENCE_PASS,
}
failed=[n for n,p in closeout_gates.items() if not p]

print("="*108)
print("MODULE 5 — M05_03 CLOSEOUT")
print("="*108)
for n,p in closeout_gates.items():print(f"{'PASS' if p else 'FAIL':<7} {n}")
print("-"*108)
print("M05_01 freeze semantic SHA          :",EXPECTED["m05_01_freeze_semantic_sha256"])
print("M05_02 KPI manifest semantic SHA    :",EXPECTED["m05_02_kpi_manifest_semantic_sha256"])
print("Roadmap amendment semantic SHA      :",M05_03_ROADMAP_AMENDMENT_SEMANTIC_SHA)
print("M05_03 benchmark manifest SHA       :",M05_03_MANIFEST_SEMANTIC_SHA)
print("M05_03 validation receipt SHA       :",M05_03_VALIDATION_RECEIPT_SEMANTIC_SHA)
print("-"*108)

if failed:raise RuntimeError("M05_03 closeout blocked by: "+", ".join(failed))

M05_03_CLOSEOUT_PASS=True
print("M05_03_CLOSEOUT_PASS                :",M05_03_CLOSEOUT_PASS)
print("Benchmark cases                     : 32")
print("DEVELOPMENT / held-out EVAL         : 24 / 8")
print("Next notebook                       : M05_04_Telemetry_MCP_Service_v1.ipynb")
print("M05_01 artifacts modified           : NO")
print("M05_02 artifacts modified           : NO")
print("Sionna introduced                   : NO — DEFERRED")
print("ML / LLM inference introduced       : NO")
print("Formal KPI values directly injected : NO")
print("Private truth exposed to agent      : NO")
print("M05_04 may load private/ directory   : NO")
print("="*108)


MODULE 5 — M05_03 CLOSEOUT
PASS    M05_03_UPSTREAM_RESTORE_PASS
PASS    M05_03_BENCHMARK_CONTRACT_PASS
PASS    M05_03_TELEMETRY_RUNTIME_PASS
PASS    M05_03_TOPOLOGY_PASS
PASS    M05_03_INCIDENT_DESIGN_PASS
PASS    M05_03_EPISODE_SCHEDULE_PASS
PASS    M05_03_BASE_SLICE_PASS
PASS    M05_03_NUMERIC_OVERLAY_PASS
PASS    M05_03_CONTEXT_OVERLAY_PASS
PASS    M05_03_LEAKAGE_PASS
PASS    M05_03_SCENARIO_KPI_PASS
PASS    M05_03_KPI_VALIDATION_PASS
PASS    M05_03_CAUSAL_SIGNATURE_PASS
PASS    M05_03_DIAGNOSABILITY_PASS
PASS    M05_03_TRUTH_SEPARATION_PASS
PASS    M05_03_SPLIT_ISOLATION_PASS
PASS    M05_03_OUTPUT_PERSISTENCE_PASS
PASS    M05_03_PERSISTENCE_PASS
------------------------------------------------------------------------------------------------------------
M05_01 freeze semantic SHA          : 4a9f6ecec30613c160b618dfe50e11e63b8f4c8c24d06eac351d5275c744a968
M05_02 KPI manifest semantic SHA    : 3b0d6271c0aba98d3cf0ac3907ec21fea7fc113ba865ae8f6f0cdf864dd5104e
Roadmap amendment semantic 

###### Observation

M05_03 completed successfully with all 18 validation gates passing. The final benchmark contains 32 controlled cases with 24 DEVELOPMENT and 8 held-out EVAL scenarios, while preserving immutable M05_01/M05_02 lineage, formal KPI derivation integrity and strict separation of agent-visible evidence from private ground truth. The validated handover authorizes `M05_04_TELEMETRY_MCP_SERVICE`.


#### M05_03 Handover Principle

After successful execution, M05_04 should consume:

```text
M05_03/benchmark/
M05_03/manifests/module5_m05_03_incident_benchmark_manifest_v1.json
M05_03/manifests/module5_m05_03_validation_receipt_v1.json
```

and explicitly reject:

```text
M05_03/private/
```

from the agent-facing Telemetry MCP runtime.

> **The benchmark harness may know the answer; the agent may not.**

For later specialist-model development, DEVELOPMENT labels may be consumed only in the offline training/evaluation workflow; `scenario_id`, benchmark timestamps and all held-out EVAL truth must be excluded from predictive features and agent-facing runtime context.